### ISSUE TITLE
Help Wanted - Awesome Infosec

### ISSUE THREAD

**Issue by generalleger** [sindresorhus/awesome#1003]
I wasn't sure where else to post this - I recently put online an **awesome** list of free cybersecurity resources.  https://github.com/keitersecurity/awesome-infosec

I put up the repo, but since I am kinda obscure on Github, I haven't gotten a lot of the benefit of the 30-day maturation period. So, I figured I would post here to see if anyone had feedback for me.

One thing I know I need to do is add the awesome badge, but I am waiting to do that until I know I am reasonably sure it will pass the **awesome** pull request guidelines.  Thanks!

**Comment by arbox** [comment]
Hi @generalleger ,

as I can judge your list missed some of the points. Please read again about contributing here in the contribution file and in the pull request template. Go through all the steps and check if they are done for your list. Feel free to add badges before you submit the pull request.

**Comment by generalleger** [comment]
@arbox - Thanks very much.  I think there are some areas where it can be cleaned up for sure.  Thanks for the feedback.  If there is anything specific that you think might be a little subtle for me to catch, please feel free to share!  Thanks again!

**Comment by peterhuerlimann** [comment]
Hi,

Maybe the content could be 'merged' into the efforts over at https://github.com/onlurking/awesome-infosec by @onlurking or https://github.com/sbilly/awesome-security by @sbilly ?
