### ISSUE TITLE
Not Awesome ES6 Classes

### ISSUE THREAD

**Issue by infinnie** [sindresorhus/awesome#1005]
I suggest https://github.com/joshburgess/not-awesome-es6-classes be included as well.

**Comment by JesseTG** [comment]
I feel like this would be better for the individual JavaScript lists.

**Comment by sindresorhus** [comment]
I think it would be a better fit for https://github.com/sorrycc/awesome-javascript

Also, while it has many good points, it focuses too much on the React specific use-case and also fails to weigh in some of the upsides of the class syntax.
