### ISSUE TITLE
Templates for hosting awesome pages in gh-pages?

### ISSUE THREAD

**Issue by aschrijver** [sindresorhus/awesome#1006]
Due to the amount of awesome pages around I can't google on templates to create a nice `gh-pages` version of the awesome repo, like React Native has: http://www.awesome-react-native.com

Are any of these around? Not sure about the license of the RN one..

If they exist is would be nice if they were mentioned in 'Creating a list' section, or somewhere accessible from the readme.

**Comment by aschrijver** [comment]
PS in RN Awesome especially the amount of stars each entry has gotten is a valuable addition.

**Comment by sindresorhus** [comment]
Not that I'm aware of. I'm also not interested in documenting templates as I personally don't see much value in such websites. Stars are just a measure of popularity, not necessarily quality.

You could ask the Awesome React Native maintainers to open-source their template as a separate project maybe.

**Comment by aschrijver** [comment]
Thanks for your time, will do!
