### ISSUE TITLE
Why are related lists not in Security section?

### ISSUE THREAD

**Issue by fsacer** [sindresorhus/awesome#1008]
Why are are not related lists of some of related lists added in Security section. To find awesome stuff you have to browse through related sections of awesome lists. Why are those lists not added at top level of security section or maybe there could be a subsection for related lists that would make it easier to search with tools like [Awesome search](https://awesomelists.top). This is probably a problem with other awesomelists too. Examples of such lists include: https://github.com/onlurking/awesome-infosec, https://github.com/coreb1t/awesome-pentest-cheat-sheets, https://github.com/Cugu/awesome-forensics, https://github.com/enaqx/awesome-pentest and many more.

Maybe there could be a common format for related lists and those would get automattically included in a subsection maybe. But that is probably no-go if you want those lists curated, but I think something should be done to include more of these lists because there is vast amounts of those which are in related sections and are great but are not in the top list.

**Comment by sindresorhus** [comment]
Either those lists were not submitted yet or they were previously declined. If they were not previously declined, feel free to submit them if they follow the [guidelines](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md). One list per pull request.

**Comment by fsacer** [comment]
@sindresorhus Could you reconsider https://github.com/enaqx/awesome-pentest, PR https://github.com/sindresorhus/awesome/pull/841, looks like this list has fixed those concerns from PR.
