### ISSUE TITLE
Best section to add Shopping cart

### ISSUE THREAD

**Issue by hosein2398** [sindresorhus/awesome#1026]
Guys I made a repo , [Here](https://github.com/hosein2398/awesome-shopping-cart) it is , and I'm trying to make it better.
I will fork this repo to add my link to that and I was wondering where is best section to add this, [business](https://github.com/sindresorhus/awesome#business) or [miscellaneous](https://github.com/sindresorhus/awesome#miscellaneous) ?
And I was also wondering  that do you guys think  `Shopping carts ` is  a good name for that or `e-Commerce platforms` is better?

**Comment by sindresorhus** [comment]
@hosein2398 What you have is not an Awesome list. It's just a table comparison of different shopping cart solutions.
