### ISSUE TITLE
Localized Content

### ISSUE THREAD

**Issue by iamchathu** [sindresorhus/awesome#1040]
In [awesome-jwt](https://github.com/iamchathu/awesome-jwt) list, there is an issue about adding localized content.

https://github.com/iamchathu/awesome-jwt/issues/2

What will be the better way? Create another readme-ru-.md may be?

**Comment by sindresorhus** [comment]
> Create another readme-ru.md may be?

Yes, but only if someone can commit to maintaining it, so try inviting that person to your list and make them in charge of maintaining the localized version.
