### ISSUE TITLE
Mentioned in Awesome badge/shield

### ISSUE THREAD

**Issue by jerone** [sindresorhus/awesome#1048]
I love awesome lists and I recently noticed that one of my projects was mentioned in an Awesome list. To promote Awesome I looked for a badge to show that I'm proud to be mentioned. The only [Awesome badge](https://github.com/sindresorhus/awesome/blob/master/media/badge.svg) is for lists. I'm looking for a badge for being mentioned in a list.

Looking at [Shields.io](http://shields.io/) there wasn't such a thing, but the available API made the following possible:

![mentioned in awesome](https://img.shields.io/badge/-mentioned_in_awesome-CCA6C4.svg?colorA=CCA6C4&colorB=261120&logoWidth=20&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI%2BICAgIDxwYXRoIGZpbGw9IiMyNjExMjAiIGQ9Ik0xOS4xNCA0LjVMMTQuMjMgMGwtLjY5Ljc1IDQuMDkgMy43NUgxLjUxTDUuNi43NSA0LjkxIDAgMCA0LjV2Mi45N0MwIDguODEgMS4yOSA5LjkgMi44OCA5LjloMy4wM2MxLjU5IDAgMi44OC0xLjA5IDIuODgtMi40M1Y1LjUyaDEuNTd2MS45NWMwIDEuMzQgMS4yOSAyLjQzIDIuODggMi40M2gzLjAzYzEuNTkgMCAyLjg4LTEuMDkgMi44OC0yLjQzbC0uMDEtMi45N3oiLz48L3N2Zz4%3D)
```
https://img.shields.io/badge/-mentioned_in_awesome-CCA6C4.svg?colorA=CCA6C4&colorB=261120&logoWidth=20&logo=data%3Aimage%2Fsvg%2Bxml%3Bbase64%2CPHN2ZyB3aWR0aD0iMjAiIGhlaWdodD0iMTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI%2BICAgIDxwYXRoIGZpbGw9IiMyNjExMjAiIGQ9Ik0xOS4xNCA0LjVMMTQuMjMgMGwtLjY5Ljc1IDQuMDkgMy43NUgxLjUxTDUuNi43NSA0LjkxIDAgMCA0LjV2Mi45N0MwIDguODEgMS4yOSA5LjkgMi44OCA5LjloMy4wM2MxLjU5IDAgMi44OC0xLjA5IDIuODgtMi40M1Y1LjUyaDEuNTd2MS45NWMwIDEuMzQgMS4yOSAyLjQzIDIuODggMi40M2gzLjAzYzEuNTkgMCAyLjg4LTEuMDkgMi44OC0yLjQzbC0uMDEtMi45N3oiLz48L3N2Zz4%3D
```

What you think about this idea, or is such a thing already possible...

Maybe a cooperation with Shields.io?

**Comment by sindresorhus** [comment]
How about this?

## SVG

<img src="https://dsc.cloud/sindresorhus/mentioned-badge.svg" width="110">

## Close-up

<img src="https://dsc.cloud/sindresorhus/mentioned-badge.svg" width="330">

*Don't use this yet! It's not final.*

**Comment by jerone** [comment]
Like it. 

Small advantage of using Shield.io is that it can be postfixed with the awesome-list name, e.g. ![](https://camo.githubusercontent.com/be52aa97eca7305a8f26b1cfd142d41278421e07/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f2d6d656e74696f6e65645f696e5f617765736f6d655f75736572736372697074732d4343413643342e7376673f636f6c6f72413d43434136433426636f6c6f72423d323631313230266c6f676f57696474683d3230266c6f676f3d64617461253341696d616765253246737667253242786d6c25334262617365363425324350484e325a79423361575230614430694d6a41694947686c6157646f644430694d544169494868746247357a50534a6f644852774f693876643364334c6e637a4c6d39795a7938794d4441774c334e325a794925324249434167494478775958526f49475a706247773949694d794e6a45784d6a416949475139496b30784f5334784e4341304c6a564d4d5451754d6a4d674d4777744c6a59354c6a6331494451754d446b674d7934334e5567784c6a5578544455754e6934334e5341304c6a6b78494441674d4341304c6a56324d6934354e304d77494467754f4445674d5334794f5341354c6a6b674d6934344f4341354c6a6c6f4d7934774d324d784c6a5535494441674d6934344f4330784c6a4135494449754f4467744d6934304d3159314c6a5579614445754e5464324d5334354e574d77494445754d7a51674d5334794f5341794c6a517a494449754f4467674d6934304d32677a4c6a417a597a45754e546b674d4341794c6a67344c5445754d446b674d6934344f4330794c6a517a624330754d4445744d6934354e336f694c7a34384c334e325a7a34253344)

But I can go either way.

**Comment by sindresorhus** [comment]
@jerone That badge looks way too long though, and would be even longer for most other awesome lists, which have longer names than `userscripts`. Better to just say `awesome` and rather link it to the specific list.

**Comment by jerone** [comment]
[**@sindresorhus**](https://github.com/sindresorhus) commented on [Oct 13, 2017, 7:06 PM GMT+2](https://github.com/sindresorhus/awesome/issues/1048#issuecomment-336511155 "2017-10-13T17:06:05Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone) That badge looks way too long though, and would be even longer for most other awesome lists, which have longer names than `userscripts`. Better to just say `awesome` and rather link it to the specific list.

Fully agree 👍

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/awesome/commit/797812a80964486b5633361766b528b1359e516b
