### ISSUE TITLE
[question] Add travis CI to verify links in readme.md on PR

### ISSUE THREAD

**Issue by coolbrg** [sindresorhus/awesome#1065]
Hi @sindresorhus ,

It would be great if we setup Travis CI to quickly verify the links at least. I have read the issue #683 and found quite lot of tasks to be done there . Setting CI is very quick and do most of important work of verifying links.

Let me know WDYT about it? Happy to send PR for it.

**Comment by sindresorhus** [comment]
That's the plan, but it's not ready yet: https://github.com/sindresorhus/awesome/pull/1394
