### ISSUE TITLE
AwesomeOpenSource

### ISSUE THREAD

**Issue by jeffreyjackson** [sindresorhus/awesome#107]
We are creating a github org for all awesome open source repos.  I am working with a few individuals who are also managing their own awesome repos, and I think to gain more traction we need to work together.  What are your thoughts about collectively moving your awesome repos to https://github.com/AwesomeOpenSource

The idea is that visibility for these repos would be increased due to more traffic to the org.  What are your thoughts?  Let me know if there is anything you'd like to discuss!

**Comment by sindresorhus** [comment]
Thanks for the offer, but not really interested :)
