### ISSUE TITLE
Help wanted adding a list

### ISSUE THREAD

**Issue by rivermont** [sindresorhus/awesome#1072]
I would like to add the [Hack-with-Github/Awesome-Hacking](https://github.com/Hack-with-Github/Awesome-Hacking) list, but have a couple problems.

* It's not mine. Therefore I can't edit things like GitHub topics.
* Incorrect formatting. Awesome-Hacking does not conform to most of the guidelines required to be on *this* list, but I don't feel comfortable redesigning their entire list just to have it here.
* List of lists. Are lists of other lists of actual things accepted here? Can't really tell.

Thanks!

**Comment by Jogai** [comment]
Fork it, change it, send in a pull request there. Or maybe raise an issue about it (first).

**Comment by aleksandar-todorovic** [comment]
Hmmmm... seems more of a meta list to me (kind of like this list) than a list of awesome items.

There were also previous attempts at adding this list (see #597 for example). 

And I know for a fact that these guys are cool and happy to receive contributions (for example, see https://github.com/Hack-with-Github/Awesome-Hacking/issues/2, https://github.com/Hack-with-Github/Awesome-Hacking/pull/3/, https://github.com/Hack-with-Github/Awesome-Hacking/pull/5), so I'm gonna go ahead and agree with @Jogai. You should raise the issue in their repository. :smile:
