### ISSUE TITLE
Awesome Hacking

### ISSUE THREAD

**Issue by Chan9390** [sindresorhus/awesome#1088]
Hey @sindresorhus ,

I wanted to include [**Awesome Hacking**](https://github.com/Hack-with-Github/Awesome-Hacking) repository under *Security* category, but there already exists another repository named *Hacking*.

Any idea on how to add the repo to the list ?

**Comment by aleksandar-todorovic** [comment]
There have already been at least two attempts of adding that list here: #1072 #597

**Comment by Chan9390** [comment]
Oh didnt notice that. Will try the third time :smile:

**Comment by Chan9390** [comment]
Closing this as the PR was never merged.
