### ISSUE TITLE
Awesome mentioned in a science journal

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#1101]
Leaving it here in case anyone is interested in reading it:

### [The appropriation of GitHub for curation](https://peerj.com/articles/cs-134.pdf)

> GitHub is a widely used online collaborative software development environment. In this paper, we describe curation projects as a new category of GitHub project that collects, evaluates, and preserves resources for software developers.

> We investigate:
> 1. what motivates software developers to curate resources;
> 2. why curation has occurred on GitHub;
> 3. how curated resources are used by software developers; and
> 4. how the GitHub platform could better support these practices.

> We conduct in-depth interviews with 16 software developers, each of whom hosts curation projects on GitHub. Our results suggest that the motivators that inspire software developers to curate resources on GitHub are similar to those that motivate them to participate in the development of open source projects. Convenient tools (e.g., Markdown syntax and Git version control system) and the opportunity to address professional needs of a large number of peers attract developers to engage in curation projects on GitHub. Benefits of curating on GitHub include learning opportunities, support for development work, and professional interaction. However, curation is limited by GitHub’s document structure, format, and a lack of key features, such as search. In light of this, we propose design possibilities to encourage and improve appropriations of GitHub for curation.

---

Feel free to discuss it below if desired.

**Comment by tdogg6669** [comment]
https://github.com/wtgtybhertgeghgtwtg
