### ISSUE TITLE
Arrange the lists in alphabetical Order.

### ISSUE THREAD

**Issue by najela** [sindresorhus/awesome#112]
Hey I think it will be a great idea to arrange this list in an alphabetical order. E.g 

#### Back-end development
- Django
- Play1 Framework
- CakePHP
- Symfony2
- Laravel

*Becomes*

#### Back-end development
- CakePHP
- Django
- Laravel
- Play1 Framework
- Symfony2

**Comment by sindresorhus** [comment]
I prefer the current sorting.

**Comment by rapito** [comment]
+1 najela

**Comment by najela** [comment]
@rapito  Lets hope @sindresorhus changes his mind ;)
