### ISSUE TITLE
In need of help: awesome-cli (and soon awesome-bot)

### ISSUE THREAD

**Issue by jacc** [sindresorhus/awesome#1147]
I saw something about creating a bot that would detect if a list is suitable for posting. I've quickly created awesome-cli to do just that. Currently it only checks if the README is there, but when I wake up I will do much more. Please contribute! https://github.com/jacc/awesome-cli

**Comment by sindresorhus** [comment]
There's already https://github.com/sindresorhus/awesome-lint ;)

**Comment by jacc** [comment]
@sindresorhus I tried!
