### ISSUE TITLE
"HEIC Converter" mentioned in README is not actually free

### ISSUE THREAD

**Issue by magicgoose** [sindresorhus/awesome#1153]
Free software should have a free license (GPL for example). But the license for the "HEIC Converter" cannot be found anywhere.

If the application is only available on Mac App Store and no source code is published, then it's [by definition not free](https://www.gnu.org/philosophy/free-sw.en.html) (maybe only free as in free beer). Please fix the README.

**Comment by sindresorhus** [comment]
Free is an overloaded word. It's more common to think of it like "free as in free beer".
