### ISSUE TITLE
Awesome wasm

### ISSUE THREAD

**Issue by rail-ka** [sindresorhus/awesome#1165]
[mbasso/awesome-wasm](https://github.com/mbasso/awesome-wasm) - Awesome WebAssembly (wasm) list.
I did not find a mention of wasm, and also WebAssembly in the repository, I suggest adding this repository to the list, it is currently the only list.
I also suggest discussing what category the technology falls into.

**Comment by sindresorhus** [comment]
Submit a PR adding it, and ensure you read and adhere to https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-to-this-list and https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

// @mbasso
