### ISSUE TITLE
Question about list format: can you use tables?

### ISSUE THREAD

**Issue by dbohdan** [sindresorhus/awesome#1170]
How strict are the stylistic requirements on the list format; do awesome lists have to be bullet-point lists? I have two list-things that are actually mostly Markdown tables:
* https://github.com/dbohdan/structured-text-tools
* https://github.com/dbohdan/automatic-api

Would either qualify as an awesome list with how they use tables right now?

## Small Screenshots of the Lists
<details>
<summary>List 1</summary>
<img src="https://user-images.githubusercontent.com/3179832/34360977-b3c25998-ea6e-11e7-96af-c8747d78eea3.png">
</details>
<details>
<summary>List 2</summary>
<img src="https://user-images.githubusercontent.com/3179832/34360980-bb058e8c-ea6e-11e7-80a5-f498e27199d6.png">
</details>

**Comment by sindresorhus** [comment]
I don't think Markdown tables are generally appropriate as they are difficult to create and maintain, with their verbose syntax, and they don't really work visually on mobile: 

![markdown](https://user-images.githubusercontent.com/170270/34377193-4085b574-eaf0-11e7-938e-65ae8e2657d6.png)

**Comment by dbohdan** [comment]
Good point about mobile. I agree that the tables are harder to maintain. It would be much better if GitHub Markdown included a vertical markup syntax for tables (i.e., one where the individual lines are cells, not rows). For the automatic API repo I keep the data in YAML files and use a script to generate the table from them, which eases the pain significantly.

I could easily get rid of the tables with only two columns, but I think the other tables are worth it, especially the automatic API one, because they let the reader immediately see the differences between similar tools and save clicks. Would you add the lists to yours with these tables unchanged?

**Comment by sindresorhus** [comment]
Awesome lists should also not be generated.

**Comment by dbohdan** [comment]
Got it. Thanks for the feedback! I won't be submitting them, but I'll look into making my lists more mobile-friendly.
