### ISSUE TITLE
awesome-web-security has most of its resources in Chinese

### ISSUE THREAD

**Issue by n1trux** [sindresorhus/awesome#1176]
… so why does it belong on this list?

https://github.com/qazbnm456/awesome-web-security

@qazbnm456

**Comment by sindresorhus** [comment]
@qazbnm456 ⬆️ You shouldn't mix languages. If you want to also include Chinese resources, do it in a separate readme.

**Comment by qazbnm456** [comment]
@sindresorhus Of course, I'll make the change. Thanks 👍

**Comment by qazbnm456** [comment]
@sindresorhus Done! PTAL, thanks.
