### ISSUE TITLE
Please add the list of "Open Source Clones of Popular Games"

### ISSUE THREAD

**Issue by mdtrooper** [sindresorhus/awesome#118]
I have been working in script to do:

yaml + mustache_template -> markdown

And it is finish.

https://github.com/mdtrooper/osgameclones

**Comment by sindresorhus** [comment]
Why your list over the original?

// @piranha

**Comment by mdtrooper** [comment]
Good point, because the original repo the yaml data is used to generate a list outside of github.

It is in http://osgameclones.com, it is a good page with a javascript to load images and filter/search box.

But my repo fork have a script to generate a README.md (maybe more ugly), but it is in github as equal of other github lists in your awesome list.

**Comment by sindresorhus** [comment]
I'm good with including if you intend to keep it up to date and fix the script to include the images include as markdown images instead of just links. PR welcome then ;)

**Comment by mdtrooper** [comment]
Yes, the README.md is updated (when I see new changes in the original fork, I update the repo)

But the images in the file is some dificult, because there are a lot of images and github has not a ajax for to load the images. And it is very slow, you can check it in this version of file (in a commit from some days):

https://github.com/mdtrooper/osgameclones/blob/79225e9aca0b8304d95acdd6c02a98f79d95f889/README.md
