### ISSUE TITLE
Why is Ripple under decentralized systems? It's centralized.

### ISSUE THREAD

**Issue by ralphtheninja** [sindresorhus/awesome#1184]

**Comment by itrack** [comment]
Not rly, it's start like centralized system but now is decentralized.

**Comment by OvermindDL1** [comment]
> Not rly, it's start like centralized system but now is decentralized.

Where is the reference of that?  Last I saw it was still controlled via a limited set of backing nodes?  (An example is that 'you' cannot directly add a new block to the blockchain, you have to go through one of the backing nodes, which control everything that pass through them, I.E. 'you' do not own any ripple, they do and they just let you own some of it but can take it back at any time they wish.)

**Comment by tomatopeel** [comment]
Yeah what the hell? Of _all_ the cryptoX projects... Ripple? Lol...

**Comment by tomatopeel** [comment]
I guess I should at least link something https://bitcointalk.org/index.php?topic=2664078.0

**Comment by sindresorhus** [comment]
Closing as nobody has included any real evidence either way. If it's actually the case, open a PR moving it and include actual evidence.
