### ISSUE TITLE
Add link to awesome-developer-streams

### ISSUE THREAD

**Issue by clarkio** [sindresorhus/awesome#1193]
I wanted to open an issue first to make sure you thought it made sense to add here and confirm the correct section it should be under. Would it be appropriate to add in the Miscellaneous section?

https://github.com/bnb/awesome-developer-streams

**Comment by sindresorhus** [comment]
Ensure you're following the guidelines https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md and https://github.com/sindresorhus/awesome-lint and then do a PR.

**Comment by sindresorhus** [comment]
> Would it be appropriate to add in the Miscellaneous section?

Yes
