### ISSUE TITLE
Awesome Geospatial

### ISSUE THREAD

**Issue by sacridini** [sindresorhus/awesome#1196]
I want to add a geospatial/GIS/Remote Sensing list of tools/resources but I do not know in which category I can add this.

the link to the list: https://github.com/sacridini/Awesome-Geospatial

any thoughts?

**Comment by legodude17** [comment]
Just a thought, can you describe what geospatial is at the top of the list.

**Comment by sindresorhus** [comment]
If you don't find a suitable category, just add it to `Miscellaneous`. Make sure you're following https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md first though. I see many points not followed.
