### ISSUE TITLE
Harbour programming languages

### ISSUE THREAD

**Issue by rjopek** [sindresorhus/awesome#1204]
Hi,

I am sending a request to attach my listed:
https://github.com/rjopek/harbour-list

A programming language Harbour is easy to learn for even a novice developer. Its code is easy to read and you can do a lot of things just by looking at it. Also, you can execute a lot of complex functionalities with ease, thanks to the standard library.

Only for information purposes you can download it here:
[Harbour 3.4](https://github.com/vszakats/harbour-core)
[Harbour 3.2](https://github.com/harbour/core)

Thank you
Rafał

**Comment by sindresorhus** [comment]
Please read https://github.com/sindresorhus/awesome/blob/master/create-list.md and https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md and ensure you follow them, then submit a PR.
