### ISSUE TITLE
About awesome-scalability

### ISSUE THREAD

**Issue by binhnguyennus** [sindresorhus/awesome#1208]
I've been curating [awesome-scalability](https://github.com/binhnguyennus/awesome-scalability) for a bit shy of one and half months. It's a list of selected readings to illustrate scalability, availability, and stability design patterns in back-end development. So far it's gotten a decent number of stars; wherein your repo would this belong?

**Comment by flexdinesh** [comment]
I second this request. I have been going through the awesome-scalability repo as well and it's pretty great. Having it in the awesome list sounds like a good idea.

**Comment by sindresorhus** [comment]
Closing as #1200 was closed for unknown reasons.
