### ISSUE TITLE
Awesome Websites

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/awesome#1210]
No, not some other websites

Websites like http://awesomelists.top/

Recently someone launched https://www.prettyawesomelists.com/ & it looks freaking awesome

A simple heading like `View Website Version` or another awesome list would do the job. What do you think?

**Comment by timzallmann** [comment]
Thanks for the praise for my little side project (I made it). Would be fantastic to have a link to it from this super list. 

P.S. If you have any feedback, feature ideas, questions, etc. let me know.

**Comment by sindresorhus** [comment]
Yup. Really well done, @timzallmann! I think we can add a new section to the bottom of the readme for Awesome-related websites/tools. PR welcome :)
