### ISSUE TITLE
Consider appending `#readme` to all awesome lists links

### ISSUE THREAD

**Issue by nikitavoloboev** [sindresorhus/awesome#1227]
This will jump straight to the `readme` of the awesome list which is the most important part in an awesome list.

Like for example in [node.js awesome list](https://github.com/sindresorhus/awesome-nodejs#readme).

What do you think?

**Comment by peterhuerlimann** [comment]
PR #1343 would add the '#readme' to all the links, where appropriate, if its desired by @sindresorhus.
