### ISSUE TITLE
Proposal to add awesome-nlp to the list

### ISSUE THREAD

**Issue by keon** [sindresorhus/awesome#1236]
@sindresorhus 
I made the issue #677 some time ago and never really got the time to get back to it.
Since then we have gained active contributors (@NirantK and @the-ethan-hunt) who made the repo up-to-date.
We believe that we are finally ready to submit our repo here and be listed as one of the awesome-lists. 
I think we can replace 'Speech and Natural Language Processing' repo since it has not been updated for more than three years and a lot of its links are not working.

Thanks,
Keon

**Comment by NirantK** [comment]
@sindresorhus just checking in since it has been a month since opening this issue

**Comment by sindresorhus** [comment]
Ensure you follow the guidelines and then do a PR.
