### ISSUE TITLE
Effective Altruism link 404

### ISSUE THREAD

**Issue by JayAndCatchFire** [sindresorhus/awesome#1250]
The link to the Effective Altruism awesome list is dead.
https://github.com/sheonhan/awesome-effective-altruism

Shall we try to find a fork, resurrect it with the Wayback Machine, or just remove it from the list?

**Comment by JayAndCatchFire** [comment]
I'm going to make a PR to just remove it.  That seems like the most logical choice at this point.

**Comment by pokeball99** [comment]
the latest archive of this list is from [October 21](https://web.archive.org/web/20171021200848/https://github.com/sheonhan/awesome-effective-altruism) of last year if anyone wishes to recreate it
