### ISSUE TITLE
Add swag-for-dev?

### ISSUE THREAD

**Issue by swapagarwal** [sindresorhus/awesome#1251]
Creating an issue for people to chime in on whether we should add https://github.com/swapagarwal/swag-for-dev to this list (as per https://github.com/swapagarwal/swag-for-dev/issues/12)..

**Comment by sindresorhus** [comment]
Sure. It's a cool list. Just make sure you follow the [guideliens](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md) and then do a PR ;)
