### ISSUE TITLE
Proposal to add Awesome engineering Vlog (youtube, vimeo etc)

### ISSUE THREAD

**Issue by hasft** [sindresorhus/awesome#1255]
I don't know if this is a good idea or not. But i want to see a list of awesome software engineering vlog

**Comment by vsreelekshmi** [comment]
I think it is a valid point.It is hard to find useful software engineering vlogs.

**Comment by nikitavoloboev** [comment]
I made a curated list on [various interesting blogs](https://github.com/learn-anything/blogs#readme) that solves this. Not an awesome list though.

**Comment by DevFlicks** [comment]
@nikitavoloboev You might wanna fix the links in the summary.

**Comment by nikitavoloboev** [comment]
@DevFlicks Which summary?

**Comment by DevFlicks** [comment]
@nikitavoloboev Sorry, I had opened #1299 and replied to you instead of replying there. Here's the repo: https://github.com/vinsgo/awesome-ethereum
