### ISSUE TITLE
Proposal to add awesome-blazor to the list

### ISSUE THREAD

**Issue by AdrienTorris** [sindresorhus/awesome#1256]
Proposal to add the [awesome-blazor](https://github.com/AdrienTorris/awesome-blazor) repo to the list, in the [Front-End development](https://github.com/sindresorhus/awesome#front-end-development) chapter.

For information, Blazor is an experimental .NET web framework using C#/Razor and HTML that runs in the browser with WebAssembly.

**Comment by sindresorhus** [comment]
Closing as there's no need for both an issue and a PR. PRs are issues.
