### ISSUE TITLE
Offering the option to use flat badges

### ISSUE THREAD

**Issue by bokub** [sindresorhus/awesome#1258]
In the [awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md), two badges are available for awesome lists and mentioned-in-awesome repos, with the following warning: *The badge should not be modified in any way.*

![Awesome](https://awesome.re/badge.svg) ![Mentioned in Awesome Node.js](https://awesome.re/mentioned-badge.svg)

In my humble opinion, this style is starting to look a bit old, and I see a lot of people using the *flat-square* badges from shields.io: ![Flat-square](https://img.shields.io/badge/style-flat--square-brightgreen.svg?longCache=true&style=flat-square) (I use them myself)

I made my own versions of the awesome badges, with a flat style.
I haven't added a single thing, only removed the gradient, the shadows and the round corners.

![Awesome](https://rawgit.com/bokub/95a3fbad9279d4ef34de2b4070622229/raw/badge-flat.svg) ![Mentioned in Awesome Node.js](https://rawgit.com/bokub/95a3fbad9279d4ef34de2b4070622229/raw/mentioned-badge-flat.svg)

The SVG code can be found in [this gist](https://gist.github.com/bokub/95a3fbad9279d4ef34de2b4070622229)

**I think it would be great if people had a choice. What do you think?**

**Comment by bokub** [comment]
Hi @sindresorhus! What's your opinion on this?

**Comment by sindresorhus** [comment]
Yes, good idea, can you do a PR adding it to the repo and the Awesome manifest? Make sure to run the new badges through https://jakearchibald.github.io/svgomg/
