### ISSUE TITLE
List of useful Git Hook and .gitignore files

### ISSUE THREAD

**Issue by vsaw** [sindresorhus/awesome#128]
I thinks these ones would make a great addition to the list

- https://github.com/pre-commit/pre-commit
- https://github.com/github/gitignore

Given the fact that by then a number of Git related items are in the list maybe it makes sense to move Git (and possibly GitHub) to a separate section?

**Comment by sindresorhus** [comment]
To be clear, this repo is a list of other lists of some kind of resource. None of the links above fits that category.
