### ISSUE TITLE
Adding Back to Top Link

### ISSUE THREAD

**Issue by ErEllison** [sindresorhus/awesome#1281]
Hi there ,
this awesome library is very awesome awesome ....
but is has a single problem , which is back to top link after each subject
please any one can handle that 
just simple as it is , it could be so much helpful
what i'm asking is to add a simple back to top link after every Bunch of contents....
thank you very much for creating this awesome awesome awesome library ....
by the way this post should be badged via enhancement tag, but i don't know how to add that tag , so i skipped it ....

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm not interested littering the list with lots of "back to top" links. On macOS, you can press Cmd+ArrowUp to scroll to the top. I'm sure there is a similar keyboard shortcut on other OSes. If you went to a suggestion from the Table of Contents, you can just press Cmd+ArrowLeft to go back to the Table of Contents.
