### ISSUE TITLE
I made a tool: mmarkdown

### ISSUE THREAD

**Issue by albinotonnina** [sindresorhus/awesome#1283]
# Hello! 
I made this little javascript tool recently: 

https://github.com/albinotonnina/mmarkdown

<img src="https://user-images.githubusercontent.com/37283/39442518-6670e04a-4ca9-11e8-8a91-22c9ff73e100.png" width="128" />

What it does is so simple that I will just paste here the description of the project:
> mmarkdown:
> Interpret mmd fenced code blocks in a markdown file and generate a cooler version of it.

It could be useful for big projects like this one, that rely almost entirely on markdown files as an output.

An example in the wild:
https://github.com/albinotonnina/css-in-js/tree/mmarkdown

Using mmarkdown (and node.js) I made a little app to fetch and process data from npm and github (given a json list of package/repositories) and generate an updated markdown file. 

You could add some sort of automation to update the markdown file programmatically.

It could be interesting or not. I thought it was worth showing it to you. 😀

Thanks and keep up the great work here!

**Comment by sindresorhus** [comment]
I'm sure it's a cool tool, but the way to convince someone to use your tool is to show what problems it solves for this exact project, not just copy-paste a generic message you also posted elsewhere (https://github.com/awesomedata/awesome-public-datasets/issues/361).

**Comment by albinotonnina** [comment]
Hello, 
Thanks for your response. 
This is oss, I’m not selling a product. I’m sharing something I did and you could see potential in it or not see it. If you closed this issue and stop others from generating a discussion from it because you feel offended by the copy and paste well, it’s fine, but to me it looks a bit silly.

**Comment by sindresorhus** [comment]
I didn't say you were selling your product, but you're clearly trying to promote it.

**Comment by sindresorhus** [comment]
> IN THIS PARTICULAR PROJECT, you could make a simple webapp to manage submissions, with sorting and filtering and voting that would output data that mmarkdown would use to generate the awesome readme file.

I appreciate the suggestion, but Awesome lists should not be generated.

**Comment by albinotonnina** [comment]
Thanks again for the response.
Given this requirement, there is no use for this tool in this project and no possibility for discussion.
