### ISSUE TITLE
O'Reilly Media Inc

### ISSUE THREAD

**Issue by vsaw** [sindresorhus/awesome#129]
I noticed that Books and Repositories of O'Reilly are missing. Since their [public GitHub repositories](https://github.com/oreillymedia) not only contain lots of great tools but also some collaborative books like

- https://github.com/oreillymedia/97-things-every-agile-developer-should-know
- https://github.com/oreillymedia/keep-up-to-date
- https://github.com/oreillymedia/opencv-processing-book
- https://github.com/oreillymedia/open_government
- http://weareallaweso.me/

**Comment by sindresorhus** [comment]
Thanks for the suggestions, but some of these are books and the lists aren't very comprehensive, so going to pass.
