### ISSUE TITLE
you dont know js

### ISSUE THREAD

**Issue by h-nazzal** [sindresorhus/awesome#130]
why not add ["you dont know js"](https://github.com/getify/You-Dont-Know-JS) book series. seriously one of the best recent books for JavaScript.

**Comment by arthurvr** [comment]
Isn't this more of a request for [awesome-javascript](https://github.com/sorrycc/awesome-javascript)?

**Comment by h-nazzal** [comment]
are both of these lists linked together?! 
if not then i see you have a variety of things listed in here.which include a lot of javascript stuff.

**Comment by sindresorhus** [comment]
Yup

**Comment by h-nazzal** [comment]
@sindresorhus then i guess there should be a better description of what does this list include.
i bet it will be very helpful to others :)

**Comment by sindresorhus** [comment]
Clearer how? For me it's quite clear: 

> A curated list of awesome **lists**

**Comment by h-nazzal** [comment]
ahhh .. forget it .. i misread that .. sorry !!! 
should have a better reading skills ! :(
