### ISSUE TITLE
Proposal to add awesome-db-tools

### ISSUE THREAD

**Issue by mgramin** [sindresorhus/awesome#1306]
github.com/mgramin/awesome-db-tools

This is a list of database tools (ide, cli, managing, monitoring, migrations, modellers, visualization etc)

**Comment by legodude17** [comment]
@mgramin Please open a pull request

**Comment by mgramin** [comment]
@legodude17  pull request #1307

**Comment by mgramin** [comment]
Waiting 30 days....
