### ISSUE TITLE
Make child windows sticky if parent is sticky

### ISSUE THREAD

**Issue by nanangarsyad** [sindresorhus/awesome#1312]
I wanted to make the child window to inherit the traits of the parent window.
In my case I made the parent window sticky in hopping I could use it across many tags. But in my surprise the child window popped up from its parent not showing in my current workspace (tag).

Here's the sequences I did, 
1. Open a window (apps) in a specified tag/workspace  (e.g tag 1)
2. Make that window sticky
3. Move to to other tag/workspace
4. Open child window (pop up windows) from parent apps.

Here's the awesome i used.

```
$ awesome --version
awesome v4.2 (Human after all)
 • Compiled against Lua 5.3.3 (running with Lua 5.3)
 • D-Bus support: ✔
 • execinfo support: ✔
 • xcb-randr version: 1.5
 • LGI version: 0.9.2
```

Here's the screen cast,
![awesome-stiky-popup-issue](https://user-images.githubusercontent.com/7588442/40357585-ddd8e418-5de6-11e8-98e4-9e51cdf6f6ab.gif)

Thank you

**Comment by ChristienGuy** [comment]
@nanangarsyad This repo is for a curated list of awesome lists. It looks like you've mistaken it for something else. 

Did you mean to go to https://github.com/awesomeWM/awesome ?

**Comment by nanangarsyad** [comment]
oh... sorry.
I thought this was awesome wm. I'll close this issue.
But thanks for the link thought.  I'll put it there.
