### ISSUE TITLE
Moving to GitLab?

### ISSUE THREAD

**Issue by ramnes** [sindresorhus/awesome#1324]

**Comment by vasilukwolf** [comment]
Oh no, =( Microsoft no no no. Ruby and Github please live

**Comment by sindresorhus** [comment]
I don't like the acquisition either, but I don't plan to move to GitLab.

I'll elaborate on my thoughts about it here when I have time: https://github.com/sindresorhus/ama/issues/548

**Comment by ramnes** [comment]
Will watch this, thank you.
