### ISSUE TITLE
Awesome Pretty List

### ISSUE THREAD

**Issue by PaulRosset** [sindresorhus/awesome#1338]
Hello :)

I've built a website to facilitate the browsing, searchability and beautify the awesome list from this repository.
- [Website](https://awesome.paulrossethings.com/)
- [Github](https://github.com/PaulRosset/awesome-list-pretty)

The data that are used on the website are extracted directly from [this repository](https://github.com/sindresorhus/awesome/).
I would really appreciate if you guys tell me about what you think about this ?

I hope this project will improve the awesome list :)

**Comment by legodude17** [comment]
@PaulRosset This is really cool!

**Comment by lukasz-madon** [comment]
looks good, but it doesn't provide much more that using cmd+F, does it?

https://awesomelists.top/

**Comment by PaulRosset** [comment]
Hey @lukasz-madon :)
Yeah for the moment it doesn't provide much more than cmd+F, only a better and more pleasant interface to browse but I'm very open to new features that we could implement on top of it.
It would be cool if all the awesome list could respect a certain strict format on their README, it would be easier to parse.

 https://awesomelists.top/ this one looks very cool too!

**Comment by sindresorhus** [comment]
Very cool! Happy to list it in a new section at the bottom of the readme. Do a PR ;)
