### ISSUE TITLE
Would anyone be interested: "Awesome list of hardware for Kali Linux"?

### ISSUE THREAD

**Issue by CecileGS** [sindresorhus/awesome#1354]
Excuse me for wasting your time if it turns out that there already exists an Awesome List or online database that already covers what I am proposing - I did not take much time in doing sufficient research to know if this is the case - but I just created a new public repo for the purpose of sharing this type of knowledge.

https://github.com/CecileGS/awesome-kali-linux-hardware

In a nutshell... An "Awesome list of recommended laptops, wifi chipsets, and such for Kali Linux!"

I will admit however, that I am totally new to the editorial/submission process and quality guidelines of the Awesome project. I don't know:
-what license to use
-if there is a styling guideline that I need to follow
-much about Kali Linux, as I have never actually used it before but I am also extremely interested in using it for pentesting; therefore, I will need to enlist the help of security experts and experienced Kali Linux users to make this list a reality
-if this repo is redundant, let alone if this is something that would even be remotely appreciated or wanted by anyone (i.e. I am wasting my time by attempting to solve a problem that does not exist or need a solution to)

Any help, pointers, and tips for me are very much appreciated!! I would also request the green light approval status for me to proceed, from either the maintainer (preferably) or some other high profile contributor to the Awesome project.

**Comment by CecileGS** [comment]
Also idk how to add labels to issues in this tracker. Can someone add the `list request` and `help wanted` labels for me?

**Comment by sindresorhus** [comment]
The requirements for a list is listed here: https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

Usually, you start a list when you know a topic very well and want to share the resources and knowledge you have gathered. It doesn't really work to create an empty list and hope that people will come by and help out.

Instead, try to find some people in the Kali Linux community to start the list with.

**Comment by CecileGS** [comment]
>  It doesn't really work to create an empty list and hope that people will come by and help out.

Okay yeah that makes sense, and I am in full agreement with the point. I have neither the experience nor expert knowledge to contribute to my own list meaningfully so I guess I will delete the repo for now. Thank you.

**Comment by Jrmufunwa** [comment]
How do I install Kali Linux on Samsung A05s..?
