### ISSUE TITLE
Suggestion: Create new sub Title: Internet of Things

### ISSUE THREAD

**Issue by GermanBluefox** [sindresorhus/awesome#1372]
There are some projects related with IoT and Smarthome.
I suggest to create extra Chapter for that named **Internet of Things**.
Just now I can add to it: 
- https://github.com/hobbyquaker/awesome-mqtt, 
- https://github.com/hobbyquaker/awesome-homematic, 
- https://github.com/hobbyquaker/awesome-iot, 
- https://github.com/hobbyquaker/awesome-lego,
- https://github.com/frenck/awesome-home-assistant 
- and I preparing ioBroker awesome list https://github.com/ioBroker/awesome-iobroker

**Comment by sindresorhus** [comment]
We only create new categories when something that is **already in the list** can be combined into a new category.

**Comment by GermanBluefox** [comment]
All items except awesome-iot and awesome-iobroker are already in your list.
