### ISSUE TITLE
Add awesome-transformer

### ISSUE THREAD

**Issue by SkyAndCloud** [sindresorhus/awesome#1391]
[awesome-transformer](https://github.com/SkyAndCloud/awesome-transformer), should classified into `Deep Learning`。
Transformer is a powerful model applied in sequence to sequence learning. However, when I was using transformer as my baseline in NMT research I found no good & reliable guide to reproduce approximate result as reported in original paper(even official tensor2tensor implementation), which means my research would be unauthentic. I searched on the Internet, found some implementations, obtained some performance-reproducable approaches and other learning materials, which eventually formed this project.
I hope more researchers can benefit from it.

**Comment by sindresorhus** [comment]
Make sure you follow https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md, then do a pull request.
