### ISSUE TITLE
Add DevOps / continuous release / production environment / code & release process / ...

### ISSUE THREAD

**Issue by 7hibault** [sindresorhus/awesome#1403]
I can't find the proper term for that, but it would be awesome to add an awesome list of tools and resources for the "code & release process" (which is usually called DevOps these days).  This would include topics related to source control management, continuous integration, testing, provisioning, deployment, containers, release orchestration, cloud, analytics, monitoring, security, collaboration... and many more?

**Comment by Gillespie59** [comment]
What about this awesome list : https://github.com/AcalephStorage/awesome-devops

You can contribute if you want to add stuff.
