### ISSUE TITLE
awesome-piracy

### ISSUE THREAD

**Issue by jjzr3** [sindresorhus/awesome#1418]
Is this allowed to be added here? This is cool. But if this isn't allowed, sorry. My bad.
https://github.com/Igglybuff/awesome-piracy

**Comment by sindresorhus** [comment]
Nah, I don't want to encourage piracy.

**Comment by jjzr3** [comment]
I see.

**Comment by jjzr3** [comment]
How can I delete this?

**Comment by vitalkanev** [comment]
You can't delete github issues, I assume. But maybe lock this issue?
