### ISSUE TITLE
Wexflow - Yet another workflow engine and task scheduler

### ISSUE THREAD

**Issue by aelassas** [sindresorhus/awesome#1427]
Can you add [Wexflow](https://github.com/aelassas/Wexflow) to the list please? 

Wexflow is an open source extensible workflow engine and task scheduler with a cross-platform manager and designer. The goal of Wexflow is to automate recurring tasks without user intervention. Wexflow aims to make automations, workflow processes, long-running processes and interactions between systems, applications and folks easy, straightforward and clean.

**Comment by sindresorhus** [comment]
That’s not an Awesome list.
