### ISSUE TITLE
More categories

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#143]
The `Miscellaneous` category is getting pretty large. Would be nice to split some of it out into more categories.

Suggestions?

**Comment by kevva** [comment]
I think there are enough editors to create an own category for them (`Editors`).

**Comment by arthurvr** [comment]
> I think there are enough editors to create an own category for them (Editors).

I only see three (or am I missing some?). We have other categories with only three items as well, so :+1:.

**Comment by kevva** [comment]
Indeed, but `Editors` might be quite interesting for some people and having them in misc could be hard to find.

**Comment by cmmata** [comment]
You could add a category 'Software' for example. You've got Sublime Text, Vim, Emacs, Sketch, .. Another one could be 'Development Resources' to complement Front-end and back-end. You have Git cheat sheet, Dev env, Styleguides, Boilerplate projects, Json, REST, ..

**Comment by vamshisuram** [comment]
You could separate Browser-extensions as a category. Would like to add the following collection to it. Take a look at https://github.com/vamshisuram/awesome-browser-extensions

**Comment by syedumeralishah** [comment]
How can I maintain portfolio .

**Comment by hbt** [comment]
@sindresorhus I'd like to second @cmmata 

We can easily extract a software section out of the current misc. Lists that focus on specific software e.g vim, sublime text, git, emacs, zsh, docker etc. 

@sindresorhus if idea is approved, I will send you a PR. Let me know.

Thanks

**Comment by sindresorhus** [comment]
I made a bunch of categories in https://github.com/sindresorhus/awesome/commit/fe43829d57b9f5f18a5f35907cca81c92e712769 Any improvements to that or more categories welcome :)

**Comment by hbt** [comment]
@sindresorhus 
Looks good. I think we could benefit from a table of contents to discover the big sections instead of scrolling.

**Comment by sindresorhus** [comment]
@hbt done in https://github.com/sindresorhus/awesome/commit/78bddd6b16911fb013c6cad9dcff54606055f2d6

**Comment by hbt** [comment]
@sindresorhus 
great stuff man

**Comment by sindresorhus** [comment]
Any other suggestions for improvements more than welcome :)

**Comment by vamshisuram** [comment]
@sindresorhus awesome is awesomer..! ;)

**Comment by sindresorhus** [comment]
I think we're good now. Happy to receive more category suggestions, but no point in keeping this issue open.
