### ISSUE TITLE
Add awesome-docs

### ISSUE THREAD

**Issue by hipstersmoothie** [sindresorhus/awesome#1435]
There doesn't seem to be an awesome-docs. https://github.com/PharkMillups/beautiful-docs/ is pretty well established

**Comment by sindresorhus** [comment]
It has not been maintained for years though. Someone should fork it or create a new list.

If anyone decides to go for it, ensure you read and follow: https://github.com/sindresorhus/awesome/blob/master/create-list.md

**Comment by ADubhlaoich** [comment]
I'll get something going soon, since this still evidently has yet to be done.
