### ISSUE TITLE
ListList service and Awesome lists

### ISSUE THREAD

**Issue by aschrijver** [sindresorhus/awesome#1438]
I created this issue separately from [How to grow Awesome?](https://github.com/sindresorhus/awesome/issues/784) as a reaction to @maltsev 's https://github.com/sindresorhus/awesome/issues/784#issuecomment-432389273 presenting the [ListList](https://listlist.net/) service.

I think @maltsev created a great project here that has potential to grow the reach of Awesome to a broader public than Github users. I [proposed](https://github.com/sindresorhus/awesome/issues/784#issuecomment-384223195) having a tool to generate a HTML page of an awesome list, which @sindresorhus found to be overkill (a valid point, I can understand).

The ListList service however, adds an aggregated view to this, plus - importantly - the RSS feed feature, which I think is real added value to Awesome (I am a great proponent of the [decentralized web](https://community.humanetech.com/t/towards-the-vision-of-the-decentralized-web/530), and this fits in).

@maltsev just [PR'ed](https://github.com/engagingspaces/awesome-humane-tech/pull/5) a feed badge to my [awesome-humane-tech](https://github.com/engagingspaces/awesome-humane-tech) list, but before merging I have some things (improvements, discussion points) I'd like to bring up:

- I could not find a repo for the ListList project (maybe it is on Gitlab). For me to add ListList badge, I'd like the project to be open-sourced, just like all other awesome list repo's

- There is no clear license on the ListList page. My list and the top-level one (and most others probably) live in the public domain. I'd like ListList to have a public domain license too.

- The ListList drops the Awesome branding. There is no awesome logo, and the collection is called _"A curated list of spectacular lists"_ .

- With code repositories the number of stars says nothing about the quality of the project. But with awesome lists they do. The stars are a direct reflection how useful/valuable people think the list is. With ListList people don't land on the repo README anymore, and be less inclined to drill-down and give a star. I think ListList should have a starring capability that makes this just as easy again.

- And the last point stems from my [Humane Tech](https://humanetech.com) focus: When subscribing by email, people should know your Privacy Policy. Also there is Google Tag Manager tracker on the page and use of sentry.io. Not having a PP would probably put you in breach of EU GDPR.

Note: @maltsev please don't take this as undue criticism. I love your project, but think these things need a honest discussion.

**Comment by maltsev** [comment]
> please don't take this as undue criticism. I love your project, but think these things need a honest discussion.

Sure. You have totally valid points. Below I'm going to try to answer each of them. Let me know if you or any other user have any questions.

---

> I could not find a repo for the ListList project (maybe it is on Gitlab)

I just created it: [maltsev/listlist](https://github.com/maltsev/listlist). Feel free to open issues!

> For me to add ListList badge, I'd like the project to be open-sourced, just like all other awesome list repo's

Sorry, but currently I don't plan to open-source it.

> There is no clear license on the ListList page

I'll think about the proper license that will suit me. It won't be CC0, though. There is also this thing that different lists have different licenses and many of them don't have a license at all. So I can't license the whole website under one license. 

> The ListList drops the Awesome branding

I consider ListList as a separate project and not a representation of Awesome lists (like [AwesomeSearch](https://awesomelists.top/)). Currently [this repository serves](https://github.com/sindresorhus/awesome) as the only lists source for my service, but in the future I might add more sources or even allow curators to create lists on ListList itself.

Therefore I don't think it's a good idea to affiliate ListList with Awesome lists.


> and the collection is called "A curated list of spectacular lists" 

Try to reload the main page and it'll change ;-)


> I think ListList should have a starring capability that makes this just as easy again

As far as I know there is no way to star a Github repository on a third-party website. So a user must open the repository on github.com and only then they should be able to star it. I've added "View on Github" link to every list on ListList for that purpose already. I'll think how to make it more actionable, though. On the other hand, I don't want to implement my own starring (yet) as it'd just duplicate the Github one and definitely would be less popular.


> When subscribing by email, people should know your Privacy Policy

I published it: [https://listlist.net/privacy](https://listlist.net/privacy)

**Comment by sindresorhus** [comment]
> Sorry, but currently I don't plan to open-source it.

Open source is what the Awesome project is all about...

> Therefore I don't think it's a good idea to affiliate ListList with Awesome lists.

But you want Awesome lists to affiliate themselves with ListList by including a your badge.

---

You state in your privacy policy that you will not share user's email with anyone, but you don't say what you will use the emails for yourself. That should be clearly stated. For example, if you intend on using the emails for any other purpose than sending Awesome list updates.

**Comment by maltsev** [comment]
> You state in your privacy policy that you will not share user's email with anyone, but you don't say what you will use the emails for yourself.

Thanks for the advice! I added that part.


> But you want Awesome lists to affiliate themselves with ListList by including a your badge.

By *being affiliated* I meant that it's a separate project and isn't related to the Awesome project(s).

By adding a badge or just a plaintext link a list owner gives an easy way for list readers to subscribe to the list's updates. I don't think it makes ListList affiliated with the Awesome project (same way as Travis, Gitter, and other badges don't imply affiliation). Though, I agree that ListList itself looks similar to your list of awesome lists which might make people think they're related. If you want to make the distinction between the two projects clearer I'm happy to discuss that!

**Comment by sindresorhus** [comment]
Closing as the ListList project has since shut down.
