### ISSUE TITLE
Searchable Awesome

### ISSUE THREAD

**Issue by ThePixelDeveloper** [sindresorhus/awesome#1441]
Thought I'd share something I've been working on in small parts of my spare time. 

**Awesome Indexed**

https://awesome-indexed.mathew-davies.co.uk

**Why?**

I was looking for alternatives to a service, so wanted to find all mentions of it to look for something better. It can also be used for other purposes, ie. A search for "Symfony" will return podcasts, jobs, tools and so on ...

It's also different from the other "Search" projects in that it searches the content which has more value to me.

---

It's super simple, hopefully useful to others. It certainly was for me.

Enjoy. 

Ps. If this is the wrong place to post, feel free to remove. Also happy to hear suggestions.

**Comment by sindresorhus** [comment]
We could create a section at the bottom of the readme here for Awesome-related tools. Wanna do a PR?

I think the Awesome Indexed main page should have a short tagline on what it is and also link back to the Awesome repo.

**Comment by ThePixelDeveloper** [comment]
@sindresorhus Yeah can do. I'll make sure to update the website in the next few days and create a PR for it. I'll keep you informed 👍

**Comment by ThePixelDeveloper** [comment]
@sindresorhus Done and Done. See PR https://github.com/sindresorhus/awesome/pull/1529
