### ISSUE TITLE
Add datproject to decentralized-systems

### ISSUE THREAD

**Issue by alshell7** [sindresorhus/awesome#1453]
Dat is a distributed data community and a unique distributed network allows users to store data where they want by decentralizing storage. **Awesome** isn't it?❤️

Repository : https://github.com/datproject/dat
Request for adding in : [#decentralized-systems](https://github.com/sindresorhus/awesome#decentralized-systems)

**Comment by sindresorhus** [comment]
This repo lists Awesome lists, not awesome projects.
