### ISSUE TITLE
awesome-more

### ISSUE THREAD

**Issue by manishkk** [sindresorhus/awesome#1455]
Add awesome-mpc (multiparty computation) related to cryptography
https://github.com/rdragos/awesome-mpc

Add awesome-self-stabilization related to distributed algorithms
https://github.com/manishkk/awesome-Self-stabilization

Add awesome-distributed-systems
https://github.com/theanalyst/awesome-distributed-systems

Add awesome-rust
https://github.com/rust-unofficial/awesome-rust

Add awesome-dynamic-analysis 
https://github.com/mre/awesome-dynamic-analysis

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-an-awesome-list

If the list complies to the guidelines, do an individual PR per list.
