### ISSUE TITLE
Awesome Power BI Heroes

### ISSUE THREAD

**Issue by NajiElKotob** [sindresorhus/awesome#1464]
https://github.com/NajiElKotob/Awesome-Power-BI-Heroes

Thank you,

**Comment by sindresorhus** [comment]
Not much content yet.

https://github.com/sindresorhus/awesome/blob/master/create-list.md

**Comment by NajiElKotob** [comment]
You are right, would you please check the updated list https://github.com/NajiElKotob/Awesome-Power-BI

**Comment by NajiElKotob** [comment]
Hello, I added new useful and selected sections to https://github.com/NajiElKotob/Awesome-Power-BI Would you please check and let me know if it is acceptable now.
