### ISSUE TITLE
Add Regex

### ISSUE THREAD

**Issue by aloisdg** [sindresorhus/awesome#147]
Hello,

I made an [awesome-regex](https://github.com/aloisdg/awesome-regex).
Where should I add it? What is the best category?

Thank you and feel free to contribute too :)

**Comment by sindresorhus** [comment]
Nowhere yet. You just made the list. Give it some time (some weeks or a month). Add more content. Improve it. Then submit a pull request to the `Miscellaneous` section.

**Comment by aloisdg** [comment]
Ok sure.
