### ISSUE TITLE
Awesome Roadmaps

### ISSUE THREAD

**Issue by ugurozturk** [sindresorhus/awesome#1470]
Hi, there is amazing roadmaps in the github. So i have feeling nice if there would be awesome roadmaps. 

Examples
https://github.com/kamranahmedse/developer-roadmap
https://github.com/adam-golab/react-developer-roadmap
https://github.com/BohdanOrlov/iOS-Developer-Roadmap

**Comment by viniciusfm1** [comment]
I would like to contribute to this.

**Comment by viniciusfm1** [comment]
Nice!
