### ISSUE TITLE
Awesome lists to evaluate add: Interview Questions, JavaScript Crypto Libraries, Linux Software, Creative Resources for Developer and Designer

### ISSUE THREAD

**Issue by ivangsosa** [sindresorhus/awesome#1473]
Hi. I pass some lists that I have in bookmarks. Best regards.

https://github.com/MaximAbramchuck/awesome-interview-questions
https://github.com/gabrielizalo/Awesome-JavaScript-Crypto-Libraries
https://github.com/luongvo209/Awesome-Linux-Software
https://github.com/gztchan/awesome-design

**Comment by sindresorhus** [comment]
There's a clear process for adding lists: https://github.com/sindresorhus/awesome/blob/master/contributing.md#adding-an-awesome-list One list per PR when they comply with the guidelines :)
