### ISSUE TITLE
Is there a list for wikis?

### ISSUE THREAD

**Issue by Kreijstal** [sindresorhus/awesome#1509]
I'd like something like a list where these projects belong
- https://github.com/rstacruz/cheatsheets/ Amazing wiki about cheatsheets
- https://github.com/open-source-ideas/open-source-ideas what it says.

**Comment by sindresorhus** [comment]
Those are not really wiki's though, so not clear what this request really is about, but the best way to ensure something exists is to create it yourself ;)
