### ISSUE TITLE
Local awesome lists

### ISSUE THREAD

**Issue by Stichoza** [sindresorhus/awesome#153]
I noticed some localized awesome lists that contain packages/libs specific to certain countries. Local bank APIs, cellular operator services, localizations, language packs, etc.

Example: https://github.com/Stichoza/awesome-georgia

What about adding separate category like **Local Lists**? I think it will encourage local open-source communities.

**Comment by thiagotgo90** [comment]
I think that's a great idea. Some services, like bank's API are really local. If someone find any API for the Brazilian bank, i would appreciate ;)

**Comment by sindresorhus** [comment]
I'll consider it if more lists like this comes up. Keeping this issue open for discovery.

**Comment by tedder** [comment]
I'm thinking I'll create one for my local area, which will help make the category make sense.

**Comment by Stichoza** [comment]
@tedder @thiagotgo90 Nice! Go for it guys. That kind of awesome lists will strongly encourage and build local open-source communities.

I'm from [Georgia (country)](http://en.wikipedia.org/wiki/Georgia_(country)) and here is no such thing "oss community", everyone is sitting in their caves coding without interacting to the outer world. Everyone is re-creating same things over and over again. That's sucks.

So that's my idea in general.

**Comment by aleksandar-todorovic** [comment]
Awesome idea!

I'll create a local list for my country and maybe one more country in a day or two.

**Comment by Stichoza** [comment]
@aleksandar-todorovic Cool! :+1:

**Comment by sindresorhus** [comment]
Found this one: https://github.com/rubysg/singapore 

//@JuanitoFatas

**Comment by tedder** [comment]
I created a list for Portland Oregon (USA) because of this issue/pull request:

https://github.com/tedder/awesome-portland-oregon-tech/blob/master/README.md

**Comment by JuanitoFatas** [comment]
> Found this one: https://github.com/rubysg/singapore

This one is mostly a guidebook if you are visiting Singapore. 

Will curate a list of services in Singapore and report here. @sindresorhus Thanks for the mention :smile:

**Comment by aleksandar-todorovic** [comment]
I created one for Bosnia & Herzegovina as well. It's called [awesome-bosnia](https://github.com/aleksandar-todorovic/awesome-bosnia).

It's not really full of content at the moment, but I will update it regularly.

**Comment by JuanitoFatas** [comment]
For Singapore is https://webuild.sg. Always fresh and updating, no stale static list :blush:

**Comment by louy2** [comment]
You English speaking morons :laughing: Don't forget to do i10n!

**Comment by getsadzeg** [comment]
@Stichoza რაც მაგრები ვართ ქართველები ვართო ნათქვამია
I think it's awesome idea. Please add [awesome-georgian-talks](https://github.com/getsadzeg/awesome-georgian-talks) when you do the local thing.

**Comment by davisonio** [comment]
From what I understand, "Local" lists will be lists related to a specific place or collection of places - countries, places, events, languages (e.g. Awesome France, Awesome Coffee Shops in London and Awesome Russian).

Lists we already have listed which might go into Local:
- https://github.com/RichardLitt/awesome-conferences
- https://github.com/RichardLitt/endangered-languages
- https://github.com/dav009/awesome-spanish-nlp
- https://github.com/diasdavid/awesome-hacking-spots

Lists we could add and go under this category (might need work):
- https://github.com/Stichoza/awesome-georgia
- https://github.com/rubysg/singapore
- https://github.com/tedder/awesome-portland-oregon-tech
- https://github.com/aleksandar-todorovic/awesome-bosnia
- https://webuild.sg/
- https://github.com/getsadzeg/awesome-georgian-talks
- https://github.com/planetopendata/awesome-world

**Comment by getsadzeg** [comment]
@davisionio

I dream Github to have upvote button.

**Comment by coderyi** [comment]
chinese ,https://github.com/AntBranch/awesome-github

**Comment by dikiaap** [comment]
@davisonio I create new one https://github.com/GitIndonesia/awesome-indonesia-repo
I think it's good for this list request.

**Comment by kodie** [comment]
I thought this was a cool idea: https://github.com/AwesomeCities

**Comment by alexx518** [comment]
Awesome Modern C++
https://github.com/rigtorp/awesome-modern-cpp

**Comment by fingerslide** [comment]
I wish i knew what was feally going on here.sex???? No... Hum wromg place too bad.
