### ISSUE TITLE
Consider merging with bayandin/awesome-awesomeness

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/awesome#157]
It would be nice to merge efforts.
Clickable link: https://github.com/bayandin/awesome-awesomeness
/cc @bayandin

**Comment by sindresorhus** [comment]
That list is pretty inactive. Look at last commit date and the PR queue.

Happy to have it merged in here though.

**Comment by waldyrious** [comment]
Fair enough, but why close this issue? The suggestion was merge with, not merge into; the direction of the merge is surely something that can and should be discussed. I would say that e.g. if a PR is opened to add the entries here, its merging should close this issue.

Anyway, I've pinged @bayandin, who was active [as recently as last week](https://github.com/bayandin?tab=activity) so I'd suggest we at least give it a couple days for him to voice his thoughts here. Please consider reopening :)

**Comment by waldyrious** [comment]
God, I hate github abandonware. Thanks for the patience @sindresorhus :)
