### ISSUE TITLE
would love to add some free theme collection list 

### ISSUE THREAD

**Issue by mehedi-sharif** [sindresorhus/awesome#1570]
In here there should be a list for free and premium themes , and also some web development tools . Would love to contribute . 
Thanks

**Comment by leomaurodesenv** [comment]
Hello @mehedi-sharif ,
You can search for `web` in this awesome list and find a lot of amazing lists which you can contribute with themes!
For example, see [Front-end Development](https://github.com/sindresorhus/awesome#front-end-development).

Feel free to contribute to a list, be sure with requirements of contributing, each list have one style.

**Comment by zoidbergwill** [comment]
@mehedi-sharif What kind of themes were you thinking of?

Maybe we can close this issue since it needs more information?

**Comment by AAMetatron** [comment]
Your Awesome
