### ISSUE TITLE
Would make sense adding awesome-* lists for learning languages?

### ISSUE THREAD

**Issue by luizdamim** [sindresorhus/awesome#1572]
I started learning German recently and have collected a huge amount of material related to it: dictionaries, courses, Youtube channels, etc.

How about creating awesome lists for learning (non programming) languages?

**Comment by RandyHBH** [comment]
HI @luizdamim, I'm very interested in this subject, maybe you can share with me these materials

**Comment by Jogai** [comment]
See if you can work with https://github.com/willianpaixao/awesome-german or https://github.com/Frederick-S/awesome-german
I think there is no restriction to include language awesome lists.

**Comment by sindresorhus** [comment]
Language lists we welcome. Just sure you put a lot of work into the list.

**Comment by Jogai** [comment]
I think we should make @willianpaixao and @Frederick-S aware of this conversation 🔔 😉

**Comment by willianpaixao** [comment]
Haha, nice.

Well, my repo is IMHO quite stable already. Can't think of something big that isn't already there (that I know or used myself).
And as an Open Source code/documentation you can simply snatch the Markdown here. I would just ask to be mentioned in the footnote.

**Comment by luizdamim** [comment]
I searched for awesome-german lists before opening this issue but haven't found one.

The list from @willianpaixao is more complete than I have, but I have some links he's missing. I'll just colab with him to improve it.

I'll also open a PR to add a **Languages** section to this awesome list of awesome topics so people can find and start contributing. 😎 

Thank you all.
