### ISSUE TITLE
Review pull_request_template.md and create-list.md

### ISSUE THREAD

**Issue by missmatsuko** [sindresorhus/awesome#1575]
create-list.md has at least 1 rule that's not in pull_request_template.md and could get missed by people making a PR:
```
Your awesome list should be named awesome-list-name"
```

I think these files could either be combined, or the PR template could be simplified (without removing rules), and create-list.md could have more details about each requirement.

I think if the PR template were more like a checklist or form, people would be able to follow it better.

I can give it a try, if you're ok with this suggestion.

**Comment by zoidbergwill** [comment]
Having one canonical list with all the rules sounds valuable to me

**Comment by sindresorhus** [comment]
> I think if the PR template were more like a checklist or form, people would be able to follow it better.

It used to be in checkbox form, but almost everyone checked stuff without actually adhering to it, so it ended up being a useless effort.

**Comment by sindresorhus** [comment]
> I think these files could either be combined, or the PR template could be simplified (without removing rules), and create-list.md could have more details about each requirement.

Good point. Fixed :)
