### ISSUE TITLE
awesome-oss-sdgs  & CC0 license trick

### ISSUE THREAD

**Issue by AdrienLemaire** [sindresorhus/awesome#1598]
Hi,

I'm creating a new awesome list for "Awesome Open Source projects dedicated to tackling global challenges", and looking at the [Requirements for your Awesome list](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-awesome-list), it took me a while to figure out the proper way to add the license to the repo.

The trick is in [this comment](https://github.com/github/choosealicense.com/issues/496#issuecomment-341561904).

After creating a github repo, we can simply go `https://github.com/<user>/<repo>/community/license/new?branch=master&template=cc0-1.0`, and it will nicely appear in [the LICENSE page](https://github.com/Fandekasp/awesome-oss-sdgs/blob/master/LICENSE).

Adding this trick to the "Has an appropriate license" section of the doc could be useful for future contributors. Also, being more specific about the `please add comment with just the word unicorn` part could avoid some errors. I added the comment [in the git commit](https://github.com/Fandekasp/awesome-oss-sdgs/commit/ffcb7d229c22120172ca27d17c880fa737f6b456), and I doubt you'll notice it when I submit the repo next month.

**Comment by sindresorhus** [comment]
Thanks for bringing this up. I've decided to change the license guidelines: https://github.com/sindresorhus/awesome/commit/b9338ca9226bf2dabacb46a847dd5f9db1856821
