### ISSUE TITLE
Awesome list for country?

### ISSUE THREAD

**Issue by jerrychong25** [sindresorhus/awesome#1602]
Hi all,

I am creating [Awesome Malaysia](https://github.com/jerrychong25/awesome-malaysia) for curated list for all Malaysia resources.

I would like to add this into awesome list, however there is no country section for adding so.

May I know where should this added into?

Thanks.

**Comment by sindresorhus** [comment]
`Miscellaneous` until there are other country-related lists.

**Comment by jerrychong25** [comment]
> `Miscellaneous` until there are other country-related lists.

Noted with thanks!
