### ISSUE TITLE
awesome-c no longer maintained on GitHub

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome#167]
awesome-c list is no longer on GitHub.

Maybe we should link the new location of this list?
Or someone should continue supporting the development of this list on GitHub?

Anyway, I don't think that this repository should link to that awesome-c repository anymore.

**Comment by sindresorhus** [comment]
Removed. Lists should be on GitHub as the whole point of them are community collaboration.

Keeping this open to encourage someone to create another one.

-

C list not on GitHub: https://notabug.org/koz.ross/awesome-c

**Comment by aleksandar-todorovic** [comment]
We do not need to create a new one. Since the GNU license of the list allows people to fork it as long as the forks are being licensed under the same license, I did so.

I'm more than happy to continue maintaining this list.

***
[https://github.com/aleksandar-todorovic/awesome-c](https://github.com/aleksandar-todorovic/awesome-c)

**Comment by sindresorhus** [comment]
:+1: Link changed to yours ;)
