### ISSUE TITLE
Semantic PR names?

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/awesome#1678]
For the title format [PR requirement](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md#requirements-for-your-pull-request), am I able to use a semantic variation or is it strictly as documented? (example: `feat: Add Swift` instead of `Add Swift`)

cc @sindresorhus

**Comment by sindresorhus** [comment]
It should be exactly as documented. No `feat:`.
