### ISSUE TITLE
Awesome CLI

### ISSUE THREAD

**Issue by umutphp** [sindresorhus/awesome#1695]
Many thanks to @sindresorhus and all the other list owners and contributors for such a great value.

I created a CLI tool to hang around awesome lists. I hope you all enjoy it :).

[https://github.com/umutphp/awesome-cli](https://github.com/umutphp/awesome-cli)

**Comment by sindresorhus** [comment]
Nice work! It's an interesting prototype. However, I'm not sure I would use it. It seems a bit too inconvenient to scroll through long lists and hierarchies. I think what it needs is a search. Then you could quickly get to what you want. Also maybe a "Recent" list so you can quickly get to the lists you usually visit.

Another fun idea would be a "Surprise me" functionality, which would pick either a random list or a random item from a list and show it. Something like [this](https://chrome.google.com/webstore/detail/stumbleuponawesome/dhfmgppomdaagdcbpccdfjpopgikcdge?authuser=3).

**Comment by umutphp** [comment]
Hi @sindresorhus, many thanks for the feedbacks :).

Search, "surprise me" and "recent" functionalities are added to he roadmap 👍

**Comment by sindresorhus** [comment]
Great! I'm going to close this issue, but feel free to submit it to the Related section when the CLI is more than 30 days old.

https://github.com/sindresorhus/awesome#related
