### ISSUE TITLE
Request to have my list added as an awesome-software-engineer list

### ISSUE THREAD

**Issue by niem94** [sindresorhus/awesome#1698]
Hi, I am currently making an all-in-one list with all the stuff I find relevant and usable as a student studying software engineering. I would love my list to be an awesome list, but I am not entirely sure it fits. I don't want my list to visit to many other lists, as I find it very user friendly, that everything is in one place, so people don't have to scatter through lists to find what they are looking for. This said, I am open for it, as long as the other lists lives up to expectations.

The list is here, and Is currently a wip, which I plan to maintain for many years to come: 

https://github.com/niem94/my-software-engineer-list

If the list can be considered an awesome list, I will of course rename it and add tags/banners to reflect that. 

Hope to hear from you 🤞 🤞

**Comment by simskij** [comment]
Thank you for the submission! 🙏🏼

While being a **great resource** which you've apparently put **a lot**  of effort into producing,  I personally feel that this deviates a bit too much from the concept that is an awesome-list.

**Comment by benohanlon** [comment]
Reading through it, it is pretty awesome but reads more like an index of lists rather than a list. What I'd like to see is a real list for each of these in his index.

**Comment by niem94** [comment]
> Reading through it, it is pretty awesome but reads more like an index of lists rather than a list. What I'd like to see is a real list for each of these in his index.

I’d like to do that. I propose that I move all main sections to their own lists, and make the software-engineer-list be a list of topics. Is that what you want aswell?

**Comment by niem94** [comment]
> Thank you for the submission! 🙏🏼
> 
> While being a **great resource** which you've apparently put **a lot** of effort into producing, I personally feel that this deviates a bit too much from the concept that is an awesome-list.

Thanks for your honesty! I would like to move towards it being an awesome list, so i will see what i can do :-)

**Comment by niem94** [comment]
I made some changes in the develop branch, so the my-software-engineer is just an index of the lists I find relevant as a software engineer. I will iterate further on the actual lists, which I hope can become awesome lists when they are more complete.

**Comment by jdickey** [comment]
@niem94 Don't get discouraged! I read your page as an awesome list of &lists*, rather than as a list of *sites*, which is what I've always thought the Awesome Lists were shooting for.

Maybe take *each* of your lists, find the existing Awesome List that list comes closest to matching, and then submit PRs to *that* list for each link you'd like to add that's not already in the list you're submitting PRs for. If you think any of your lists don't match the topic of *any* existing Awesome List, then maybe submit a PR  back to awesome-lists seeking to add your new list. I think that's what @benohanlon was [suggesting](#issuecomment-593306493).

Again, great stuff here! From just another ordinary list-follower, thanks!

**Comment by niem94** [comment]
> @niem94 Don't get discouraged! I read your page as an awesome list of &lists*, rather than as a list of _sites_, which is what I've always thought the Awesome Lists were shooting for.
> 
> Maybe take _each_ of your lists, find the existing Awesome List that list comes closest to matching, and then submit PRs to _that_ list for each link you'd like to add that's not already in the list you're submitting PRs for. If you think any of your lists don't match the topic of _any_ existing Awesome List, then maybe submit a PR back to awesome-lists seeking to add your new list. I think that's what @benohanlon was [suggesting](#issuecomment-593306493).
> 
> Again, great stuff here! From just another ordinary list-follower, thanks!

No worry, i am/was not discouraged :-) I use the lists as a way to keep notes during my studies, so i’m not interested In doing PRs for other lists, as the format and time spent is important for me.

I agree with your suggestion, and it is also what i am currently aiming for. In short, I will keep my own public lists for now, and might submit those that do not exist as awesome lists, or make PRS for those that do when time allows it :-)
