### ISSUE TITLE
awesome-awesome-covid19 or all seperately?

### ISSUE THREAD

**Issue by tomByrer** [sindresorhus/awesome#1736]
I was going to make an (not) "awesome-coronavirus" list, but seems several others beat me to it, so I made this instead:

https://github.com/tomByrer/awesome-awesome-covid19

I could add this single link, or link add all the other lists directly?

TIA :)

**Comment by Jogai** [comment]
I'd say name it awesome-anticorona(measures) or try to get everyone working on one central list.

**Comment by sindresorhus** [comment]
I prefer to pick the best list (both content and maintenance) and that list can then link to the alternatives.

**Comment by tomByrer** [comment]
He wasn't interested in either.
