### ISSUE TITLE
Change Redux link

### ISSUE THREAD

**Issue by KODerFunk** [sindresorhus/awesome#1741]
Existed link to https://github.com/brillout/awesome-redux is outdated (last commit on 14 Mar 2017) and have only 315 stars.

Need change to more actual https://github.com/xgrommx/awesome-redux (last commit on 4 Mar 2020 and have ~12000 stars).

**Comment by sindresorhus** [comment]
PR welcome. Ensure the list adheres to https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md
