### ISSUE TITLE
Add Awesome KubeCon

### ISSUE THREAD

**Issue by mlycore** [sindresorhus/awesome#1748]
Hi, I'd like to open a pull request for [awesome-kubecon](github.com/mlycore/awesome-kubecon) in a category of cloud-native, it's a collection of every KubeCon speeches since 2016. People who are interested in cloud native would easily goto the KubeCon speech video and slide under different topics.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/master/create-list.md
