### ISSUE TITLE
.

### ISSUE THREAD

**Issue by lclcpg2018** [sindresorhus/awesome#1755]

**Comment by sindresorhus** [comment]
Make a better one, follow the guidelines, and I’m happy to replace it.

**Comment by Jogai** [comment]
There were PR's merged at the end of last year. Instead of creating one, I recommend trying to contribute to the existing one.



> Make a better one, follow the guidelines, and I’m happy to replace it.

Why is this the immediate reaction? The minecraft community might know it without coming from the awesome list. I think its better to try to collaborate on one instead of forking/replacing existing ones.

**Comment by karx** [comment]
Yeah, the awesome Minecraft list is seriously outdated @lclcpg2018 .

Let's start/continue this discussion at the current [awesome-minecraft](https://github.com/bs-community/awesome-minecraft) repo and see if the maintainers are active and ready to collaborate.

I have justed raised [a new PR](https://github.com/bs-community/awesome-minecraft/pull/4) to add Fabric under Mod tools, to start this process.

Iff the original maintainers are unresponsive we can think of creating a new one. @Jogai

**Comment by g-plane** [comment]
Hello everyone, I'm one of the maintainers of "Awesome Minecraft" repository. I'm sorry about that the list hasn't been updated actively. However, the list is still under maintained, but we're lack of enough sources to collect more and make the list full.

**Comment by ThexXTURBOXx** [comment]
I think, [my PR](https://github.com/bs-community/awesome-minecraft/pull/14) will resolve this for now. If even more stuff is needed: The sections do exist now and one can just add new stuff to it
