### ISSUE TITLE
Add a Natural Science theme?

### ISSUE THREAD

**Issue by erwanp** [sindresorhus/awesome#1759]
I've found many Natural Science related packages in the Miscellaneous theme. Ex:

- Neuroscience
- Bioinformatics
- Cheminformatics
- Neuroscience
- Biomedical Information Extraction

In #1213 adding a Natural Science theme was suggested, but eventually closed because of not activity. 
Should I proceed and add this new theme?

**Comment by sindresorhus** [comment]
👍

**Comment by arw36** [comment]
It doesn't appear this went update was made, but I would say Parasite would also fall under this header.

**Comment by muhammadhassangulamhussain** [comment]
It's which type of coading **is java or # # - [ ] paython**_or C++_[](any buddy - know)

**Comment by carollynn818** [comment]
Java is a widely used object-oriented programming language and software platform that runs on billions of devices, including notebook computers, mobile devices, gaming consoles, medical devices and many others. The rules and syntax of Java are based on the C and C++ languages.

**Comment by umeshkumarsahoo** [comment]
better u add  parasite under header
