### ISSUE TITLE
Mislead category about networking.

### ISSUE THREAD

**Issue by qin-nz** [sindresorhus/awesome#1764]
Hi, in category `Networking`, there are 3 awesome, but there NOT same things.

> Networking
> Software-Defined Networking
> Network Analysis
> PCAPTools

`Software-Defined Networking` and `PCAPTools` are about Internet or Ethernet or TCP/IP.
But  [Network Analysis](https://github.com/briatte/awesome-network-analysis) is about deeplearning or graph (a mathematical term).

So I think it might be placed in `Big Data` category.

**Comment by Achmadrumi** [comment]
Y

**Comment by sandra0029** [comment]
Good

**Comment by Bristools01** [comment]
Do you need assistance?

**Comment by Heniballer** [comment]
I love to be your assistance

**Comment by Dross937** [comment]
Hello

**Comment by Bristools01** [comment]
Hi

**Comment by DataZimbo** [comment]
- > > Hello~~~~, sorry couldn't find the thing at manhiy
