### ISSUE TITLE
Just launced the 'delightful' project, inspired by awesome

### ISSUE THREAD

**Issue by aschrijver** [sindresorhus/awesome#1765]
@sindresorhus hi Sindre,

I created this issue to let you know that - inspired by awesome project - I just launched an adaptation, called the **delightful** project: collecting gems of freedom :gem: 

It is hosted on Codeberg. The variation lies in the fact that only free, non-commercial and humanetech entries will be allowed to exist in the various curated lists. So - more or less - freedom is the theme, and the primary audience are those on the alternative web (fediverse et al).

In the project I give - I think - due credit to you, and this great project. But you judge for yourself.. the project is at this location:

https://codeberg.org/teaserbot-labs/delightful

**Comment by sindresorhus** [comment]
It's a commendable effort, but I think you will struggle with adoption because you're not on GitHub.

**Comment by aschrijver** [comment]
Thanks. Yes, I realize that 😄
