### ISSUE TITLE
Organizing the michellaneous category alphabetically

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome#177]
I think that it would be more appropriate to organize the lists in every category alphabetically. I think that it would be much easier to browse them if we do so.

**Comment by Rowno** [comment]
#112

**Comment by aleksandar-todorovic** [comment]
Oh, sorry then.

**Comment by aleksandar-todorovic** [comment]
I think I closed this too soon. Maybe apply this just to the Miscellaneous section? At least until somebody creates more categories.

**Comment by hbt** [comment]
+1 - misc section is getting messy.

**Comment by sindresorhus** [comment]
Sure, PR welcome for the misc section.
