### ISSUE TITLE
 Could you please rename master branch?

### ISSUE THREAD

**Issue by blacklivesmatterplease** [sindresorhus/awesome#1793]
Master and slave terminology has historical racist baggage. I think we should help try to remove them from our code to make it more inclusive. Google inclusive documentation already mentions this, would you please consider alternatives such as canary, edge and develop?

PS - why not main? 
https://www.nakasendoway.com/the-japanese-family-system/

**Comment by sindresorhus** [comment]
Done

**Comment by blacklivesmatterplease** [comment]
@sindresorhus Actually I am sorry if I wasn't clear enough. 

PS - why not main wasn't a suggestion but a link to the history behind asian culture where main family was used to refer to the nobles and branch families were similar to lower class servants.

Vercel and other big projects use canary, develop and edge. Maybe those are better terms?

**Comment by Richienb** [comment]
@blacklivesmatterplease https://twitter.com/Una/status/1271180494944829441

**Comment by blacklivesmatterplease** [comment]
I am aware but as I linked the article. You can search relevant history about it in the imperial japan and mao china. Develop, canary and edge avoid any references to historical baggage and are more widely used.

https://github.com/vercel/next.js

@Richienb

**Comment by Richienb** [comment]
I'm getting mixed messages here

![image](https://user-images.githubusercontent.com/29491356/84623408-4ee45080-af33-11ea-9ca8-996a41458e12.png)

**Comment by sindresorhus** [comment]
> PS - why not main wasn't a suggestion but a link to the history behind asian culture where main family was used to refer to the nobles and branch families were similar to lower class servants.

I personally think this is too far-fetched. "main" is an English word. I'm sure it's possible to dig up reasons why "canary" and "alpha" are bad in some culture's history too. However, this is not the place to discuss it. "main" is clearly what everyone is switching to. I'm going to hold off and wait and see what GitHub will use as a default and then align to that. So you need to convince GItHub, not me. In the meantime, "main" is still much better than "master".

I'm going to lock this thread as it's a controversial topic and the Awesome issue tracker is not the place to discuss it.
