### ISSUE TITLE
Create awesome list incubator

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/awesome#1806]
For lists which haven't existed for more than 30 days or ones that are still pretty empty, we could add them to a separate list that people can discover them. This can also be used to help raise initial awareness of the new list.

**Comment by sindresorhus** [comment]
I honestly don't want to manage that. It's more than enough work to review the current additions. And I don't really see any value in almost empty lists either. However, people can find all Awesome lists here: https://github.com/topics/awesome

https://github.com/sindresorhus/awesome/commit/3d6bc0215721268d2972fd851cfed730057829ab
