### ISSUE TITLE
Add awesome free during covid

### ISSUE THREAD

**Issue by empeje** [sindresorhus/awesome#1819]
Hi, I'm currently curating the free during Covid19 resources, e.g. online courses, software, and many others. Is it possible if I include it here? Here is the repository https://github.com/kulkultech/free-during-covid

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/main/create-list.md

**Comment by empeje** [comment]
Thanks @sindresorhus
