### ISSUE TITLE
Remove git-cheat-sheet and github-cheat-sheet?

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/awesome#184]
[Both](https://github.com/ArslanBilal/Git-Cheat-Sheet) [are](https://github.com/tiimgreen/github-cheat-sheet) definitely useful resources, but they don't seem to fit the pattern of the other entries (which are lists of *links* to awesome resources related to a topic). Instead, there could be an "awesome-cheatsheets" repo which would then link to those ([and](https://github.com/search?p=3&q=%22cheat+sheets%22+stars%3A%3E100&type=Repositories) [other](https://github.com/search?p=3&q=cheatsheets+stars%3A%3E100&type=Repositories)) repos.

Thoughts?

**Comment by sindresorhus** [comment]
Awesome list. Doesn't have to be a list of links.
