### ISSUE TITLE
how about add a  awesome-cn plan?

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [sindresorhus/awesome#1847]
Hello! I would like to add a Chinese translation version of this project to further promote this project, is that ok?

**Comment by sindresorhus** [comment]
Thanks for the offer. You're of course free to translate it, but I don't want to link to any translations, as from experience, they easily get out of date and I cannot quality check them.

**Comment by Wheeeeeeeeels** [comment]
ok,i know.if you want someone to make something,you can contact me.
