### ISSUE TITLE
Shouldn't Git and GitHub cheatsheets go to Development category?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome#187]
We already have them in the miscellaneous category. I think that they should be moved to the development category.

**Comment by sindresorhus** [comment]
There's no `Development` category. Do you mean `Developer Environment`?

**Comment by aleksandar-todorovic** [comment]
Yup. Sorry I was too lazy to go back and to see the full name of the category.

**Comment by sindresorhus** [comment]
`git` would fit, but not sure about the `GitHub` one.

**Comment by arthurvr** [comment]
I'd say Git should move but GitHub shouldn't.
