### ISSUE TITLE
Linux resources?

### ISSUE THREAD

**Issue by aleksandar-todorovic** [sindresorhus/awesome#188]
I found two repositories with Linux resources: [awesome-linux](https://github.com/dhamaniasad/awesome-linux) and [awesome-linux-resources](https://github.com/itech001/awesome-linux-resources). They have pretty different content, but I think that we should include at least one of them.

The second one already links back to this repository.

**Comment by sindresorhus** [comment]
None of those are good enough to be included. The former doesn't have much content and the latter is just a bunch of random links with no context.

Seems like a good opportunity for someone to do it better. Hint hint.

*(Keeping it open for the above reason)*

**Comment by aleksandar-todorovic** [comment]
Maybe something like this?

https://github.com/aleksandar-todorovic/awesome-linux

**Comment by sindresorhus** [comment]
@aleksandar-todorovic Sure, best one yet. Feel free to add it. Though could still use some more content, like [window managers](https://github.com/dhamaniasad/awesome-linux#x-window-managers) and books.

**Comment by aleksandar-todorovic** [comment]
I head about lots of great Linux books, but I don't want to recommend anything I haven't actually consumed, which is why that category is empty for now.

I'll create a pull request then.
