### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by irodionzaytsev** [sindresorhus/awesome#1881]
I'd like to make a list containing self-contained resources. I have made a [question](https://physics.stackexchange.com/questions/586757/self-contained-study-resources) about this on stackexchange, but then thought that an awesome-list would be a better place for such topic. Do you think an awesome-list would be appropriate format? Apologies if I shouldn't submit this question as issue, please tell me how to ask such questions properly.

**Comment by sindresorhus** [comment]
Yeah, this could potentially be a good awesome list if it's done well. Keep in mind though that for it to be added here, it needs to be very high quality. However, awesome lists don't have to be added here to be useful.
