### ISSUE TITLE
Awesome API Documentation Examples...

### ISSUE THREAD

**Issue by SimonGodefroid** [sindresorhus/awesome#1883]
Hey guys, I don't know how this sounds but I haven't find a good list of real life API documentation that are awesome.

For instance at work we use some RAML parser documentation and I wanted to look at an amazing documentation to inspire myself and although swagger's pet store is a good example, I haven't found online a list of just Awesome API Documentations (themselves) and only found lists of tools to make great API documentations.

Please close if judged irrelevant and thanks for these awesome lists.

**Comment by mandievs** [comment]
Alot of help thanx.

**Comment by Richienb** [comment]
Similar: https://github.com/matiassingers/awesome-readme

**Comment by Vmongst243** [comment]
id loke to take a deeper consensus on that approach

**Comment by Priyojone** [comment]
🍎

**Comment by AlanJosueherreraflores** [comment]
# _**![Screenshot_20220713-161530_Chrome.jpg](https://user-images.githubusercontent.com/109209556/178945722-1a14a56d-781f-475b-a46f-c68b4399b979.jpg)🤑**_

**Comment by Williamscom** [comment]
[](https://github.com/Williamscom)

**Comment by Williamscom** [comment]
😃

**Comment by silopolis** [comment]
An Awesome API Documentation list would surely get an important place in the proposed Technical Documentation category proposed in #2486, as well as the Awesome Readme list suggested by @Richienb

**Comment by Doinzman1233** [comment]
> Hey guys, I don't know how this sounds but I haven't find a good list of real life API documentation that are awesome.
> 
> 
> 
> For instance at work we use some RAML parser documentation and I wanted to look at an amazing documentation to inspire myself and although swagger's pet store is a good example, I haven't found online a list of just Awesome API Documentations (themselves) and only found lists of tools to make great API documentations.
> 
> 
> 
> Please close if judged irrelevant and thanks for these awesome lists.

**Comment by phuc-hoang-39** [comment]
> Hey guys, I don't know how this sounds but I haven't find a good list of real life API documentation that are awesome.
> 
> 
> 
> For instance at work we use some RAML parser documentation and I wanted to look at an amazing documentation to inspire myself and although swagger's pet store is a good example, I haven't found online a list of just Awesome API Documentations (themselves) and only found lists of tools to make great API documentations.
> 
> 
> 
> Please close if judged irrelevant and thanks for these awesome lists.

**Comment by phuc-hoang-39** [comment]
[]()

**Comment by phuc-hoang-39** [comment]
> Hey guys, I don't know how this sounds but I haven't find a good list of real life API documentation that are awesome.
> 
> 
> 
> For instance at work we use some RAML parser documentation and I wanted to look at an amazing documentation to inspire myself and although swagger's pet store is a good example, I haven't found online a list of just Awesome API Documentations (themselves) and only found lists of tools to make great API documentations.
> 
> 
> 
> Please close if judged irrelevant and thanks for these awesome lists.

**Comment by phuc-hoang-39** [comment]
> Alot of help thanx.

**Comment by phuc-hoang-39** [comment]
> Hey guys, I don't know how this sounds but I haven't find a good list of real life API documentation that are awesome.
> 
> 
> 
> For instance at work we use some RAML parser documentation and I wanted to look at an amazing documentation to inspire myself and although swagger's pet store is a good example, I haven't found online a list of just Awesome API Documentations (themselves) and only found lists of tools to make great API documentations.
> 
> 
> 
> Please close if judged irrelevant and thanks for these awesome lists.

**Comment by Alilimucci** [comment]
Ik

**Comment by Defen6D** [comment]
@SimonGodefroid have you started anything on this?  Sounds interesting

**Comment by JohnNewbold** [comment]
How do I receive payments in messenger
