### ISSUE TITLE
Awesome Statistics Project

### ISSUE THREAD

**Issue by PedroBarcha** [sindresorhus/awesome#1910]
Hi there, everyone!

I'm about to start a free software project in which I am going to get statistics (license, number of contributors, commits activity etc) of a bunch of github repos. In order to do that, I intend to use the repos mentioned here in Awesome. For that, I will need all the URLs of all the Awesome Lists. Is there an easy way to get all those URLS (maybe with some other open source project or some Awesome feature that I am missing)?

Thanks in advance.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/awesome/issues/427.

**Comment by PedroBarcha** [comment]
Nice! Thanks!
