### ISSUE TITLE
replace flask link

### ISSUE THREAD

**Issue by mjhea0** [sindresorhus/awesome#1918]
Hi. I couldn't find anything related to any policies on replacing a link (except for https://github.com/sindresorhus/awesome/issues/1063), but before I go through the process of getting my list ready for a PR, I'd like to know if it would be possible to add another Flask list or replace the current list altogether.

1. My awesome Flask list: https://github.com/mjhea0/awesome-flask
2. The current list thats listed (https://github.com/humiaozuzu/awesome-flask) has not been updated in over 15 months. I created my list back in Sep 2019 as I was tired of PRs not being addressed. For more, review https://github.com/mjhea0/awesome-flask/issues/3. I update my list regularly.
3. Also, if it helps with my request, I do maintain another awesome list (https://github.com/mjhea0/awesome-fastapi) that's currently listed, so I do understand the work required to maintain a list.

Thanks!

**Comment by sindresorhus** [comment]
Sure. Feel free to submit yours as a replacement.
