### ISSUE TITLE
Resources about awesome Java Spring backend 

### ISSUE THREAD

**Issue by GrandGarcon** [sindresorhus/awesome#1925]

**Comment by sindresorhus** [comment]
What exactly are you asking?

**Comment by GrandGarcon** [comment]
Sorry i submitted this by mistake without  putting the explanation . my  request was there was no mention about   listing awesome  Java enterprise  in  backend development  resources ( like Springboot , on oracle JRE  , etc ) . one of them for instance is : https://github.com/ThomasVitale/awesome-spring  . thanks

**Comment by nerd00f** [comment]
#2332 i opened a pull request solving this
