### ISSUE TITLE
Section for GitHub README Tools?

### ISSUE THREAD

**Issue by Dhyeythumar** [sindresorhus/awesome#1948]
Can we have a section for awesome GitHub README tools?

For example:
- [youtube stats card for GitHub Readmes](https://github.com/Dhyeythumar/youtube-stats-card) by @dhyeythumar
- [github readme stats](https://github.com/anuraghazra/github-readme-stats) by @anuraghazra

and many more...

**Comment by sindresorhus** [comment]
Those are not Awesome lists.
