### ISSUE TITLE
Awesomeappsec no longer maintained 

### ISSUE THREAD

**Issue by adds68** [sindresorhus/awesome#1971]
The https://github.com/paragonie/awesome-appsec list seems to be no longer maintained.

There are 19 pull requests open and 12 issues, the last commit was 2 years ago.

I also opened an issue asking if the list was being maintained and if i could help out: https://github.com/paragonie/awesome-appsec/issues/69

There has been no response yet, nearly coming up to 1 month.

I have forked the list and would now like to start merging PRs and cleaning up the list, is this something that is possible?

**Comment by sindresorhus** [comment]
Sure. Just make sure you show your commitment to keeping your fork maintained and ensure the list follows the guidelines: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md Then submit a pull request that replaces the URL with yours.

**Comment by Zyarasa** [comment]
Thank you
