### ISSUE TITLE
section anchors

### ISSUE THREAD

**Issue by VladimirAlexiev** [sindresorhus/awesome#1975]
@sindresorhus 
- When I'm looking at a list, eg https://awesomelists.top/#repos/onurakpolat/awesome-bigdata
- And I click on a heading (section), eg Data Ingestion
- I want a URL with anchor `data-ingestion` to be in the address bar
- So I can share that with a co-worker directly, eg https://awesomelists.top/#repos/onurakpolat/awesome-bigdata--data-ingestion

Notes:
- Inspect of the links on top shows there is something like that in the HTML eg
```
<a class="cate-anchor" data-anchor="#data-ingestion">Data Ingestion</a>
```
- Such anchors exist on github and are usable, eg https://github.com/onurakpolat/awesome-bigdata/blob/master/#data-ingestion
- They **almost** work on https://awesomelists.top:
  - Go to https://awesomelists.top/#repos/onurakpolat/awesome-bigdata
  - Now go to https://awesomelists.top/#data-ingestion, and you end up at the right place
  - But of course, if you go to https://awesomelists.top/#data-ingestion directly (in new tab or new incognito window), it doesn't go to the right place
- A URL with two hashes `https://awesomelists.top/#repos/onurakpolat/awesome-bigdata#data-ingestion` is not valid, and if I use this, your site gets confused
  - So I suggest using `--` instead of the second `#`, eg: `https://awesomelists.top/#repos/onurakpolat/awesome-bigdata--data-ingestion`

**Comment by sindresorhus** [comment]
Same as https://github.com/sindresorhus/awesome/issues/1976

---

// @lockys @John-Lin
