### ISSUE TITLE
improve search

### ISSUE THREAD

**Issue by VladimirAlexiev** [sindresorhus/awesome#1976]
Frankly I don't understand the search at https://awesomelists.top
- I search for "Kafka" and the first hit is https://awesomelists.top/#/repos/adafruit/awesome-adafruitio.
But it doesn't even contain that word!
- It should return https://awesomelists.top/#repos/onurakpolat/awesome-bigdata where Kafka appears 19 times, 
or https://awesomelists.top/#repos/manuzhang/awesome-streaming where Kafka appears 8 times.

Cheers!

**Comment by sindresorhus** [comment]
I don't run that site. You'll have to ask @lockys and @John-Lin.

**Comment by ichingking** [comment]
that site, it looks like not working.

**Comment by skyTech-max** [comment]
Which exactly

**Comment by VladimirAlexiev** [comment]
Hi @lockys and @John-Lin, should I repost #1975 and #1976 to some other repo that hosts the source of https://awesomelists.top ?

@sindresorhus, sorry about my confusion. 
So your excellent "list of lists" is at https://github.com/sindresorhus/awesome = https://awesome.re/, and there's no special UI for it?

**Comment by sindresorhus** [comment]
Correct
