### ISSUE TITLE
Urban Planning Resources

### ISSUE THREAD

**Issue by d-wasserman** [sindresorhus/awesome#1986]
Hi Awesome List Providers, 

I had a question - we have a repository that I think aligns with the awesome lists intent, but we don't want to rename our repo to much beyond markdown edits. What suggestions would you provide to integrate this into the the "awesome" framework?
[planning-technology-resources](https://github.com/APA-Technology-Division/planning-technology-resources)

**Comment by Jogai** [comment]
Well the thing is, list have to follow the standards to be included here. Unfortunately this means not including some awesome content like yours (in its current state).

**Comment by d-wasserman** [comment]
Is everything in the standards non-negotiable? We generally follow most (and recently took so more changes like branch name changes) of the guidelines [here](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md). 
We have already given a training on this repo, and a name change could be disruptive to people finding it. I also was curious if our hierarchal read me would need to be changed? 
I can raise an issue to see if users thing we should be compliant, but the work involved might not be worth it if compliance was not assured or less iron clad.

**Comment by Jogai** [comment]
Probably not _everything_, but its fairly rigid. I'm just someone who follows this repo and try to help now and then, so I can't say anything 'official'. I recommend doing that so you can see how strict everything is. One requirement is to review other pull requests, so you can start doing that too, because you have to do that anyway.

**Comment by d-wasserman** [comment]
Understood. I appreciate the response regardless. I have started an issue [here](https://github.com/APA-Technology-Division/planning-technology-resources/issues/14) to review items that need to be addressed before inclusion. If you see anything I am missing, I would appreciate feedback.

**Comment by dgrahn** [comment]
I took a quick gander at the list. I definitely think it would benefit from the awesome-list structure.

**Comment by d-wasserman** [comment]
Hi @dgrahn , I agree. We are going to discuss internally how quickly to transition to something more awesome like. We recently completed a training on GitHub for Planners [here](https://www.youtube.com/watch?v=gVa4d728T0k), and I fear a name change might spook people. I don't want to act unilaterally for our organization. 

There is a distinction between benefit from, and the minimum standards for inclusion. I am working on meeting the latter right now by reviewing the requirements for lists regarding contributing files, codes of conduct, main repo renaming, and other elements that I feel more comfortable changing as they don't really impact the form of the list today. Some guidance on what needs to change _at minimum_ for inclusion would be helpful.

**Comment by d-wasserman** [comment]
We are reviewing the changes we need to make [here](https://github.com/APA-Technology-Division/planning-technology-resources/issues/14). I am going to move this discussion into a PR. Thanks for everyone who provided input. We are basically very close to compliance on our side.
