### ISSUE TITLE
Awesome Vanilla Javascript

### ISSUE THREAD

**Issue by davidhund** [sindresorhus/awesome#200]
I just started compiling a little list of–specifically–‘Vanilla’ Javascript resources: https://github.com/davidhund/awesome-vanilla

Before making a PR I'd like to ask if this could be a handy addition to your list-of-lists?
I guess it would fall under the “Front-end Development” section.

**Comment by sindresorhus** [comment]
I like the idea, but the list need a lot more content.

The name is very obtuse, maybe `awesome-vanilla-js` instead.

Also needs a license and contributing guidelines. See this repo for inspiration.

And `npm`, not `NPM`.

Try submitting again in a month or so when it's gotten some time to mature.

**Comment by davidhund** [comment]
Sure, I understand. Thanks for your quick reply! :ok_hand:
