### ISSUE TITLE
This is a front for advertising revenue; please delist Awesome Chalice

### ISSUE THREAD

**Issue by brianmingus2** [sindresorhus/awesome#2004]
I did not charge any money for the large amount of work I put into Awesome Chalice, a community resource.

In order to have it listed here, I had to put a lot more work into it. It turns out that those guidelines are so that the list renders appropriately on project-awesome.org, where you strip out links, such as to our community Slack channel, provide no link back to the original list and display advertisements. The fatal blow is that because you have higher page rank, you prevent the original lists from ranking well in Google, having your own website show up instead. This is a very predatory practice, and it's being done fully intentionally and with the full knowledge of @sindresorhus, who has employed this strategy intentionally.

https://project-awesome.org/chalice-dev/awesome-chalice

**Comment by sindresorhus** [comment]
I am not running that website. Please try to do some research before accessing someone.

**Comment by brianmingus2** [comment]
Fair enough and I apologize.

Since we have no extradition treaty with Belarus, they cannot be compelled to comply with a C&D. However, the registrar in Russia might comply with one if you issue it. It is a total disaster in my opinion. That said, what other outcome would be expected from using FOSS licenses on these lists? Google is already confused about how to rank GitHub repos that only contain documentation, preferring ordinary websites. A license that only provided a right to fork in the case of lack of maintainership would make more sense.

**Comment by brodybits** [comment]
Hi I think there is nothing any of us can do in case of content that was already published under CC0 license, which is a form of public domain, this very list included!

I would personally not mind if this and other lists would switch to something like the CC BY 4.0 attribution license moving forward.

I did find something interesting in Belarus: https://www.sorainen.com/deals/moomin-characters-protects-its-copyright-in-belarus/

Right to fork *with proper attribution* is a basic tenant of open source, XEmacs is a famous example from over 30 years ago.

**Comment by minexew** [comment]
@brianmingus2 
In your original post you made this accusation:

> ...and it's being done fully intentionally and with the full knowledge of @sindresorhus, who has employed this strategy intentionally.

Was this based on some evidence of Sindre's involvement, or were you just trying to pass your assumptions as a fact?
