### ISSUE TITLE
Awesome Readme No Longer Maintained

### ISSUE THREAD

**Issue by RayhanADev** [sindresorhus/awesome#2008]
It seems that it's been over a year since anyone on the [awesome-readme](https://github.com/matiassingers/awesome-readme) team was actively monitoring the repository. There are quite a few stale pulls and issues that need to be addressed. I see quite a lot of potential for awesome-readme, but sadly none of it can be achieved since the team is no longer active :C.

In addition if you are willing, I would like to volunteer to manage a new awesome-readme fork/repo. Is this something that is doable?

Hope you get back to me,
~ Ray

**Comment by sindresorhus** [comment]
// @matiassingers

**Comment by brodybits** [comment]
Should someone fork it? (Should be easy under CC0 license)

**Comment by matiassingers** [comment]
(thanks for the tag @sindresorhus 🙌)

Thanks a bunch for posting this @RayhanADev and @brodybits, and apologies for the stale repo (notification screw-up on my side).

I'll review all the pending issues and PRs for the repo now, and feel free to ping me if you want to help maintain or collaborate!

**Comment by RayhanADev** [comment]
@matiassingers YAY! Glad to hear that you're still active :D. 🎉 There are quite a few PRs and issues, so if you're looking for a collaborator I'd be happy to help.

**Comment by RayhanADev** [comment]
Obtw I think we can close this since they're back :)
