### ISSUE TITLE
Add awesome-tmux

### ISSUE THREAD

**Issue by jjspace** [sindresorhus/awesome#2041]
I was recently using [awesome-tmux](https://github.com/rothgar/awesome-tmux) to help me set up tmux and I realized it wasn't on this list. I think it could fit under Platforms or Dev Environment. I don't know all the requirements to figure out if it truly is an "awesome" list so I didn't want to open the PR myself.

**Comment by sindresorhus** [comment]
The process for adding a list is well documented: https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
