### ISSUE TITLE
setup redirects for awesome lists using awesome.re

### ISSUE THREAD

**Issue by binyamin** [sindresorhus/awesome#2046]
It would be super handy if, for example, https://awesome.re/go would redirect to https://github.com/avelino/awesome-go. Since GitHub Pages doesn't appear to support setting redirects, the awesome.re site would likely move somewhere like vercel or netlify.

**Comment by sindresorhus** [comment]
This is a cool idea, but how would it practically work? I have enough things to maintain, so it would have to be something fully automatic.

There's also the problem of name conflicts. For example, there are two lists named `Stacks`.

**Comment by RobertCharles1988** [comment]
I believe it would automatically redirect you as you click on the address in general I've experimented with this pastly

**Comment by Sadaasxa** [comment]
- [ ] Есть кто тоже хочет ????

**Comment by ROKONUJJAMA** [comment]
https://www.fiverr.com/share/3vkpLa

**Comment by Git-How** [comment]
[Sublime Text](https://appstorex.net/sublime-text) and Awesome

**Comment by HemetCa** [comment]
How do I sign out

**Comment by sindresorhus** [comment]
Going to pass on this as it's not very important and also not easy to achieve.
