### ISSUE TITLE
Add a social banner for project

### ISSUE THREAD

**Issue by ksenginew** [sindresorhus/awesome#2068]
I had created a article of "Top 10 trending github repos of the week💜."

Here https://dev.to/ksengine/top-10-trending-github-repos-of-the-week-k7

I can't see your social banner there.
Please add a social banner to this project

According to github docs
> Customizing your repository's social media preview
You can customize the image displayed on social media platforms when someone links to your repository.
>
> Until you add an image, repository links expand to show basic information about the repository and the owner's avatar. Adding an image to your repository can help identify your project across various social platforms.

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview

Thanks 😊

**Comment by sindresorhus** [comment]
This repo already has a social banner set:

<img width="758" alt="Screen Shot 2021-10-09 at 15 37 15" src="https://user-images.githubusercontent.com/170270/136650951-5ff5cc3e-7ddc-4ff7-a588-d0cab61d95b2.png">
