### ISSUE TITLE
Improve the awesome list ecoystem

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#207]
A lot of lists are missing important things or just too low of quality. We could be nice internet citizens and help out those lists.

Common things I open issues about in lists:

- Missing license. Here we can suggest the same as this repo or CC0 or some other CC license.
- Missing contributing.md. Can just suggest copying the one in this repo and modify it to own needs.
- Succinct description to each item.
- Commentary on each item. Added by the submitter of why the item is worth reading/consuming. See https://github.com/sindresorhus/awesome-scifi#cities-in-flight-1970-by-james-blish-40 for example.
- Grammar. I find an amazing amount of typos in the lists people make.
- It's readme should have a clear description of what the list contains.
- Quality check added content. Not everything is worth adding. It should be a curation of the best, not a list of everything.

Having all lists follow this would improve the quality considerably.

Maybe we could come up with some guidelines on what's a `awesome` "certified" list?

Anything I missed?

**Anyone care to help out opening issues on lists? Both lists included here and not.**

**Comment by sindresorhus** [comment]
@n1trux

**Comment by arthurvr** [comment]
Neat idea. Just going through some of the lists. If a list looks unmaintained, should I open an issue to discuss removal and/or finding an alternative?

**Comment by sindresorhus** [comment]
Yes, though unmaintained should be a bit loose, meaning not updated in many months.

**Comment by arthurvr** [comment]
@sindresorhus Well, WDYT? https://github.com/dypsilon/frontend-dev-bookmarks. The 54 open PRs...

**Comment by sindresorhus** [comment]
@arthurvr Would be happy to change the link to an alternative high quality fork, but don't want to remove it as it's a good resource as is.

**Comment by aleksandar-todorovic** [comment]
@sindresorhus Maybe creating a new file called something like `guidelines.md` that will explain this process?

**Comment by sindresorhus** [comment]
@aleksandar-todorovic Yes, that's the idea. Just need to decide on what it should contain first.

**Comment by aleksandar-todorovic** [comment]
Here's my idea. Of course, you could improve the order a bit.

#### Only link to awesome content. 

Don't link to everything people suggest you to link. Research it, find out if it's really awesome and include it if it is.

#### Request a personal comment on why something is awesome

It's not enough to just suggest something. You also have to say _why_ do you suggest it and how will the potential users benefit from consuming it.

#### Make it clear on what the list is about

Make sure your list covers a certain scope and nothing else.

#### Pay attention to the grammar

Please be sure that you do your best to keep the list grammatically correct.

#### Choose an appropriate license

See [Choose a License](http://choosealicense.com/no-license/) for more details. Keep in mind that if you haven't selected a license, it basically means the people are not allowed to reproduce, distribute or create derivative works.

**NOTE**: I did an interview with a GitHub representative about licenses that could be a perfect addition to this section. It'll be online in a couple of days.

#### Stylize your list properly

Create table of content, put a picture or two, organize the content into different categories.

#### Accept other people's opinion

If you're an owner of the list, respect other people's opinion. If there are plenty of users not agreeing to your decision, give it a second thought!

**Comment by n1trux** [comment]
Nice idea, I think we should continue our efforts in making the lists better.

I'll start with my own one and then open issues on other lists. Should we mark "certified awesome" lists which adhere to the awesome guidelines with ☑ or ❤ or another symbol to distinguish them from the ones needing work?

Should we create an "awesome.md" with a "check list" or merge the guidelines into contributing.md?
Kind of like an "awesome manifesto"?

**Comment by arthurvr** [comment]
I opened quite a bit of issues on lists last week too.

**Comment by sindresorhus** [comment]
> Should we mark "certified awesome" lists which adhere to the awesome guidelines with ☑ or ❤ or another symbol to distinguish them from the ones needing work?

I'd rather we just help everyone get there when the guidelines are decided on. We can remove entries that are non-responsive.

> Should we create an "awesome.md" with a "check list" or merge the guidelines into contributing.md?
Kind of like an "awesome manifesto"?

awesome.md file in this repo that is referred to from the readme and contributing.md

**Comment by h4cc** [comment]
I think such a community should be based on standards and choosen membership. A role model or overall inspiration could be these guys: https://thephpleague.com/

**Comment by sindresorhus** [comment]
> I think such a community should be based on standards and choosen membership.

What does that even mean? Elaborate?

**Comment by n1trux** [comment]
>I'd rather we just help everyone get there when the guidelines are decided on. We can remove entries that are non-responsive.

Fair enough.

>awesome.md file in this repo that is referred to from the readme and contributing.md

Okay, I'm doing just that. Should I create a PR or push directly and we discuss later?

**Comment by sindresorhus** [comment]
> Okay, I'm doing just that. Should I create a PR or push directly and we discuss later?

You can usually just push directly, but I think it would be helpful to do a PR so we can discuss directly there.

**Comment by h4cc** [comment]
> What does that even mean? Elaborate?

@sindresorhus Its a term i used for the "we" in your previous sentence:

> Maybe we could come up with some guidelines on what's a awesome "certified" list?

Defining what is "certified" needs to be a rfc-style decission needed a group of people.
Also calling it "certified" might be counterproductive by scaring maintainers and producing competition. A open and friendly group that could be joined on free will seems way more friendly to me.

**Comment by n1trux** [comment]
>I'd rather we just help everyone get there when the guidelines are decided on. We can remove entries that are non-responsive.

Fair enough.

>awesome.md file in this repo that is referred to from the readme and contributing.md

Okay, I'm doing just that. Should I create a PR or push directly and we discuss later?

**Comment by arthurvr** [comment]
> Okay, I'm doing just that. Should I create a PR or push directly and we discuss later?

Create a PR so we can discuss it first.

**Comment by arthurvr** [comment]
Also worth checking some lists for broken links. Found quite a bunch of them.

**Comment by h4cc** [comment]
> Also worth checking some lists for broken links. Found quite a bunch of them.

That could be offered as a service. Or every list would have to integrate that into its own CI with travis or such (what i already did).

**Comment by n1trux** [comment]
oh fuck. Accidentally uploaded it :/

https://github.com/sindresorhus/awesome/blob/master/awesome.md

er, should I remove it again or should we just discuss it now? *facepalm*

**Comment by sindresorhus** [comment]
@n1trux Fixed it for you. Just click the green pull request button in the repo ;)

**Comment by dypsilon** [comment]
@sindresorhus I will go through your list and improve the quality of frontend-dev-bookmarks asap. Thank you for your contributions to the community.

**Comment by xPetrus** [comment]
You know what would be awesome but a long process? adding the logos to each link or just the big ones.

**Comment by sindresorhus** [comment]
@xPetrus It's a nice idea, but I honestly don't think it's worth the effort. And it will look weird when only some have graphics.

**Comment by strugee** [comment]
> And it will look weird when only some have graphics.

I _think_ this could be solved by putting a placeholder (e.g. blank circle or something) next to any list that doesn't have a graphic... *shrugs*

**Comment by sindresorhus** [comment]
Yeah, I just prefer the simplicity of text. Logos are all different. In my mind, it would look kinda noisy.

**Comment by sindresorhus** [comment]
The awesome manifesto is now live: https://github.com/sindresorhus/awesome/blob/master/awesome.md

We're still very much open to improvements and additions. I'm sure there's things we've missed.
