### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#213]
Maybe we can have a badge for people to use in their awesome list if they follow the `awesome.md` guidelines?

I can make something based on the new logo, but we need to find a canonical place to host it where the URL will never change, long cache, but still possible to update it. Any ideas?

**Comment by n1trux** [comment]
Why not host it at github?

**Comment by sindresorhus** [comment]
@n1trux I guess we could. Just that GitHub blocks rendering SVGs hosted in GitHub repos, so we would have to use https://rawgit.com like we do in the readme, and they have some kind of rate limiting, though unsure how high it is.

**Comment by jeshuamaxey** [comment]
http://imgur.com ?

**Comment by sindresorhus** [comment]
@jeshuamaxey Can you update the image without changing the URL there?

**Comment by jeshuamaxey** [comment]
Ahh didn't see that requirement. Imgur won't work

**Comment by n1trux** [comment]
Couldn't we just use our own servers?

Base64?

**Comment by darthmaim** [comment]
Host it in the gh-pages branch?

**Comment by lukasz-madon** [comment]
:+1: gh-page

**Comment by sindresorhus** [comment]
Badge suggestion:

<img width="110" src="https://cloud.githubusercontent.com/assets/170270/8941717/7c5d3d56-3571-11e5-9574-7fdf1bb2cb00.png">

I went with something non-pink, the logo text color, as pink would probably have been too bright and distracting for people.

Thoughts?

**Comment by arthurvr** [comment]
*Me likey!*

**Comment by aleksandar-todorovic** [comment]
Looks excellent! I like it a lot, especially the colors!

Did you draw the letters or used some font? Those are some sexy letters right there!

**Comment by sindresorhus** [comment]
@aleksandar-todorovic Same font as in the logo, Orbitron. It's just paths in the badge though.

**Comment by jyguyomarch** [comment]
:+1:

**Comment by dthree** [comment]
:+1:

**Comment by sindresorhus** [comment]
See here on how to use the badge: https://github.com/sindresorhus/awesome/blob/master/awesome.md#awesome-badge

**Comment by arthurvr** [comment]
@sindresorhus Should we notify the list authors about the existence of this badge? Most of the authors already on the list are never going to notice it.

**Comment by arthurvr** [comment]
Nevermind, just saw the other issue.

**Comment by stoeffel** [comment]
This looks awesome! nice work.
