### ISSUE TITLE
New list: Awesome Conversational AI

### ISSUE THREAD

**Issue by jyguyomarch** [sindresorhus/awesome#2130]
I have started a new awesome list: https://github.com/jyguyomarch/awesome-conversational-ai

Found some very good lists on ML and NLP, but none on Conversational AI or related. Thought I would post here to get early feedback, or just in case someone knows of an existing list. If you want to contribute as usual feel free to PR.

I'll close this issue in a bit less than 30 days once the list is mature enough for a PR. And if it is not the right way to use issues in this repo, feel free to close it of course.

**Comment by TheDire** [comment]
I'm trying to learn GitHub since I dared do mistakes learn cool diagrams, not sure Traumatic Brain Injury can deal with much but seeing your posts are interesting. And it heals and lessen pain. Thank you.

**Comment by bolshoytoster** [comment]
@jyguyomarch
Would [this](https://medium.com/x8-the-ai-community/a-reading-list-and-mini-survey-of-conversational-ai-32fceea97180) be useful?

**Comment by jyguyomarch** [comment]
@bolshoytoster definitely. Thx for that!

**Comment by Beckyscrypto** [comment]
Good for you

**Comment by RockSolid11212** [comment]
I am looking for others who would like to build out a website domain called NicelyUnited.com This would be complex however I know we have the global reach to make this happen.  Anyone who wants to collaborate and create something that will be uniquely ours please refer to this post.  My email is rocksolid11212@gmail.com

**Comment by jyguyomarch** [comment]
Closing this issue as I have created a PR #2160

**Comment by RockSolid11212** [comment]
Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
