### ISSUE TITLE
What is this.

### ISSUE THREAD

**Issue by sastofficial** [sindresorhus/awesome#2140]
I dont understand the concept. All it says is lists

**Comment by huabin** [comment]
Its about **😎 Awesome lists about all kinds of interesting topics**, in my opinion, it is so clear. If you read the README.md file, you should not be confused.

**Comment by sastofficial** [comment]
What do you mean by lists. What is in the lists. The read me is just ads and links to lists

**Comment by Jogai** [comment]
https://github.com/sindresorhus/awesome/blob/main/awesome.md

**Comment by sastofficial** [comment]
> https://github.com/sindresorhus/awesome/blob/main/awesome.md

ok so its links to lists that have links to websites/programs/etc

**Comment by Pshell21** [comment]
Ooops, I hope I didn't screw something up, Hey guys I do apologize if I did! 



 Hi💁‍♀️ I'm brand new & learning pretty much what I read as I go. It doesn't help that I'm way old👵🤫😁. 
I've had some real issues with my computer & tech in at my place. I'm also not able to work at it every day. But let me tell ya, super excited to have my emails & things finally going.😁😁😁 I think I maybe have opened up something a moment ago that was wrong 🤪😬. Please if at all you can tell me which way to go, I will kindly exit. I'm really just learning & I don't want to be in the way if I'm to slow.
I guess what I'm looking for is A Place for Mom 👵👩‍🦳

**Comment by Pshell21** [comment]
I'm pretty sure I thought I was opening something that would be useful outside of here😬 kinda like a coupon 😂
