### ISSUE TITLE
Read the PR guidelines but need further clarity before submitting.

### ISSUE THREAD

**Issue by zriyansh** [sindresorhus/awesome#2149]
Hey @sindresorhus, I read the guidelines that you made with much effort but looks like my awesome list is not compatible here,  I made it because I liked it without knowing about your 'awesome' thing. 

here's the link - https://github.com/zriyansh/awesome-os/

Everything can be followed according to the guidelines but I cannot format it in --
`[Name](link) - description`

as the list requires adding more details, so I used tables instead, have a look.

I have not yet run awesome-lint on the list.

If you think this list can find a place here, let me know so I can reformat it according to the need. 

Thanks for your time.

**Comment by zriyansh** [comment]
unicorn

**Comment by zriyansh** [comment]
The list is a collection of all big and small open-source projects and clones of Linux, Windows, and macOS operating system and their software.

**Comment by sindresorhus** [comment]
I see no reason why you have to use tables for this. Tables in this case actually makes it worse. It's a [bad experience on mobile](https://user-images.githubusercontent.com/170270/149056033-72f77a45-b764-4661-ae13-4e450a24cda4.PNG) and it's super annoying to edit, so it will be harder for users to contribute.
