### ISSUE TITLE
Shouldn't the master list be ordered alphabetically?

### ISSUE THREAD

**Issue by jyguyomarch** [sindresorhus/awesome#216]
I find it easier to scan a list if it is ordered alphabetically.

I understand that you ask new list links to be added to the end of the corresponding category. I guess it is to keep track of what's new.

Maybe instead you could ask new links to be inserted alphabetically and a :new: emoji to be added in front. If the category already has a link with :new: then remove the old :new: emoji.

**Comment by n1trux** [comment]
Well, I brought that up lately: #201

**Comment by arthurvr** [comment]
I still don't think it's worth the overhead. This list is for discovering new lists, not look up something.

> I guess it is to keep track of what's new.

Therefore people have the commit log. We just don't order things alphabetically to keep maintenance and contributing easier.

> But I find the idea with the new emoji pretty nice.

Personally, I'm :-1: but let's hear @sindresorhus.

**Comment by aleksandar-todorovic** [comment]
I like the idea of inserting :new: emoji. I also posted a similar issue (#117), which got miscellaneous category sorted alphabetically.

**Comment by diestrin** [comment]
The idea of inserting a NEW emoji has some drawbacks:

Imagine that you saw the list once, and you read all the links for a certain category. Then some new items are added to the list with the NEW emoji. Again, another pull request add some new items so this deletes the old NEW previously added.
Finally you come to this list to see what's new, and you will only find the new items from the last pull request, and not the previous new items.

This can be avoided in the way they are listed now, if an old visitor come to the list, they just look for the last item they remember remember they saw, and then continue reading the new items, which are the links below the last one they remember.

**Comment by aleksandar-todorovic** [comment]
...or we could keep the emoji for like one moth before removing it.

**Comment by arthurvr** [comment]
:-1: on pretty much all of this.

> ...or we could keep the emoji for like one moth before removing it.

Sounds like a pain to maintain.

**Comment by n1trux** [comment]
well, a new emoji would also clutter the commits to oblivion. You couldn't see in the commit log what was changed. I changed my mind about the emoji, let us not do it.

I honestly think we have more pressing issues to solve, e.g. that a lot of the awesome-repositories don't have a license or contributing file or are badly formatted or have non-awesome apps in them.

**Comment by jyguyomarch** [comment]
After reading the comments on #201 I think I better understand your point of view @arthurvr . And in fact I agree. The top priority is to make it easy to contribute lists and links.

Ordering, flagging new lists and beautifying should be done automatically with a web site generated with the README. Like it was already suggested in #210 by @n1trux :)

So feel free to close this issue (or should I close it myself?)

**Comment by arthurvr** [comment]
Feel free to reopen if anyone disagrees.
