### ISSUE TITLE
about web-padawan's awesome-lit (previously awesome-lit-html)

### ISSUE THREAD

**Issue by z00rat** [sindresorhus/awesome#2179]
hello everyone,
@web-padawan changed the repo name from **awesome-lit-html** to **awesome-lit**.

When this repo was first added it was named as **lit-html** with description **"HTML templating library for JavaScript."**
on https://github.com/sindresorhus/awesome/pull/1357 / https://github.com/sindresorhus/awesome/commit/137dee5ea2b1c1e0a439af2b5f392ea00fbbcc06

but, now this link redirects to https://github.com/web-padawan/awesome-lit 
```shell
❯ curl -I https://github.com/web-padawan/awesome-lit-html
HTTP/2 301 
server: GitHub.com
...
location: https://github.com/web-padawan/awesome-lit
...
```
and its about reads **"A curated list of awesome Lit resources."**

so, now what should be done ??
can i just change the _like_ and the _description_ and make a pull request ??
or should it be moved to some other category other than **Front-End Development** ??

**Comment by web-padawan** [comment]
> or should it be moved to some other category other than Front-End Development 

Lit is just a newer version of `lit-html` that ships with a new npm package `lit`. Check out the [release blog post](https://lit.dev/blog/2021-09-21-announcing-lit-2/).

I would appreciate a PR to update the link and description 👍

**Comment by z00rat** [comment]
> Lit is just a newer version of `lit-html` that ships with a new npm package `lit`. Check out the [release blog post](https://lit.dev/blog/2021-09-21-announcing-lit-2/).

awesome post. 👍

> I would appreciate a PR to update the link and description 👍

what the description should be ??
i'm thinking about **"Templating library"** only.

**Comment by web-padawan** [comment]
I would suggest to use something along these lines to mention web components:

> Library for building web components with a declarative template system.

This covers both key parts of Lit, namely `lit-html` and `lit-element`.

**Comment by z00rat** [comment]
> I would suggest to use something along these lines to mention web components:
> 
> > Library for building web components with a declarative template system.
> 
> This covers both key parts of Lit, namely `lit-html` and `lit-element`.

i'm going with yours one for now.
