### ISSUE TITLE
dead list awesome-rubymotion

### ISSUE THREAD

**Issue by z00rat** [sindresorhus/awesome#2187]
the list **awesome-rubymotion** by @motion-open-source is dead.
https://github.com/sindresorhus/awesome/blob/9170c40dc9ae84fb4a6bd9708085de6dabea3a32/readme.md?plain=1#L217
```
❯ curl -I https://github.com/motion-open-source/awesome-rubymotion
HTTP/2 404 
server: GitHub.com
date: Thu, 17 Feb 2022 03:34:35 GMT
content-type: text/html; charset=utf-8
```

looks like the user https://github.com/motion-open-source is dead in the first place.
but found some mirror (ig):
- https://project-awesome.org/motion-open-source/awesome-rubymotion
- https://github.com/rvollebregt/awesome-rubymotion (0 star | last commit on "1 Dec 2015") 
- https://awesomerepos.io/awesome/motion-open-source/awesome-rubymotion (dead server)

can i make a pull request removing the list ??
or something else should be done ??

**Comment by sindresorhus** [comment]
> can i make a pull request removing the list ??

👍
