### ISSUE TITLE
Regular Expression 

### ISSUE THREAD

**Issue by huei90** [sindresorhus/awesome#219]
Can I add [awesome-regexp](https://github.com/huei90/awesome-regexp) in this list?

**Comment by arthurvr** [comment]
> Collection of anything about Regular Expression (RegExp)

That's not what an awesome list should be. It should be a curated list of the best things. Not a "collection of everything".

**Comment by huei90** [comment]
@arthurvr Thanks for your suggestion.
I will add those later.

How about
> A curated list of awesome Regular Expression resources, tools,  and shiny things

**Comment by sindresorhus** [comment]
Maybe, but you need to be a lot more strict on what you're including.

Including `w3schools` doesn't really give a high confidence in its quality.

http://www.w3fools.com/

-

You just created the list. Give it some time to mature and improve. Try submitting again in a month or so.

**Comment by huei90** [comment]
Ok @sindresorhus Thanks.

**Comment by huei90** [comment]
One question, why `w3schools` still always show on the top on the search page

**Comment by sindresorhus** [comment]
@huei90 Because they use sleazy and spammy SEO optimizations to get there.

**Comment by huei90** [comment]
I have moved the project to awesome-regex, see
https://github.com/aloisdg/awesome-regex/issues/5
