### ISSUE TITLE
Love this

Great list

### ISSUE THREAD

**Issue by LadyAce777** [sindresorhus/awesome#2195]

**Comment by xricluc** [comment]
;+(

**Comment by sindresorhus** [comment]
👍

**Comment by Pinocchio9** [comment]
Flash BTC Transaction (Core Network) 6.3.0

New features : 

-Supports up to 5000 BTC per transaction
-Can stay on the wallet for more than 6 months (180 days)
-Quick confirmation if you have over 30,000TH / S
-Support an unlimited number of transfers by wallet
-Support new bitcoin addresses (Segwit, legacy, Bech32)
-Supports future trading on binance, ftx and coinbase Mail : pinocchiojean@gmail.com
Telegram : @pinocchioMiner
Demo transaction blockchain explorer link: 
https://bitref.com/3L2CGSKH26yJPNuKjfN8NakvpnCv4GFHan
