### ISSUE TITLE
Draft process and list placement

### ISSUE THREAD

**Issue by cnpryer** [sindresorhus/awesome#2239]
Hi! Love this. A couple questions:

1. Is there a draft process for baking lists? (Prevent duplicates or redundant effort)
2. For lists that focus on something like a library that spans multiple languages and domains, where would a list like this fit?

### Drafting

>Don't open a Draft / WIP pull request while you work on the guidelines. A pull request should be 100% ready and should adhere to all the guidelines when you open it.

The goal is to add an `awesome` list to the `awesome` tree. If you want to centralize the community's effort, wouldn't it help to submit a draft PR here to provide that visibility (almost like self-assign)?

### List placement (category)
I'm baking [awesome-polars](https://github.com/cnpryer/awesome-polars) that is very early stage. Since I have a lot of time to get this all figured out (and do [a couple reviews](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md#requirements-for-your-pull-request)), I want to make sure I know where to aim for and how placement works.

If it were solely a Python ecosystem topic awesome-python would probably make sense (correct me if I'm wrong), but it's a Rust library with supported bindings for a couple languages. Visibility within the Python ecosystem is just as important as it is in the Rust ecosystem. Since it's a DataFrame library it could also be considered part of several domains/non-language categories.

Any advice here would be appreciated! 😄

**Comment by sindresorhus** [comment]
1. I don't want to get notifications for incomplete lists. It would create a lot of maintenance overhead. I'm going with an issue instead: https://github.com/sindresorhus/awesome/issues/2242

2. Anything without a clear category ends up in "Miscellaneous". If there turns out to be multiple lists that could share a new category, it can be moved later on. I'm not really sure what category this one belongs too.

**Comment by cnpryer** [comment]
> 1. I don't want to get notifications for incomplete lists. It would create a lot of maintenance overhead. I'm going with an issue instead: https://github.com/sindresorhus/awesome/issues/2242

Sounds good. Thanks! I could be wrong, but I don't think drafts will ping you. I wonder if you'll end up getting more notifications with the issue format.

> 2. Anything without a clear category ends up in "Miscellaneous". If there turns out to be multiple lists that could share a new category, it can be moved later on. I'm not really sure what category this one belongs too.

Makes sense! 👍

**Comment by sindresorhus** [comment]
> but I don't think drafts will ping you. I wonder if you'll end up getting more notifications with the issue format.


Draft PRs do create notifications. I can unsubscribe from an issue.
