### ISSUE TITLE
Badge style "for-the-badge" allowed?

### ISSUE THREAD

**Issue by elliotwutingfeng** [sindresorhus/awesome#2250]
I want to place a "mentioned in awesome" badge on my awesome project's readme, in the style of "for-the-badge", but there is currently no such option available (the existing flat version is smaller than "for-the-badge" badges and would look out of place in this repo https://github.com/elliotwutingfeng/go-fasttld).

Is it against the rules to use my own "for-the-badge" badge like this?

![Mentioned In Awesome](https://img.shields.io/static/v1?logo=awesomelists&label=&labelColor=CCA6C4&logoColor=261120&message=Mentioned%20in%20awesome&color=494368&style=for-the-badge)

(generated from shields.io)

**Comment by sindresorhus** [comment]
Feel free to use that. And also feel free to add it to https://github.com/sindresorhus/awesome/blob/main/awesome.md#awesome-mentioned-badge
