### ISSUE TITLE
Is there section for CMS's?

### ISSUE THREAD

**Issue by xPetrus** [sindresorhus/awesome#227]
I couldn't find any, but I can provide links, SVG's, and .ai files if you need them.

**Comment by sindresorhus** [comment]
We only create sections when there's an actual need. Do you have any awesome CMS list to suggest?

**Comment by xPetrus** [comment]
There will be after I make one.

**Comment by sindresorhus** [comment]
Ok, but for a section to be created there needs to be at least two entries. No worries though. We can just add it to Misc first and later to a new section if there is a need.

**Comment by xPetrus** [comment]
No worries I'm already making an awesome list https://github.com/xPetrus/awesome-cms
