### ISSUE TITLE
awesome-productivity

### ISSUE THREAD

**Issue by jyguyomarch** [sindresorhus/awesome#228]
Hi,

I started a list on productivity (methods, tools, books...). But before going further, is that something that already exists and that I might have missed? If not, do you think it is a good idea and would fit the awesome framework?

**Comment by cmmata** [comment]
I don't know any awesome productivity list, but would be great to have one and take a look. And I think it would fit

**Comment by aleksandar-todorovic** [comment]
I don't know of any such list, but I would love to find one!

Thanks for creating it. I hope you'll manage to attract more contributors to it.

**Comment by jyguyomarch** [comment]
I have started https://github.com/jyguyomarch/awesome-productivity

I'll add it to the awesome repo once we have enough resources in there.
