### ISSUE TITLE
Guidance on what the name of a list that contains these entries should be?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/awesome#229]
These are kind of the things that I want to add to this list :- 

1. [Dunning-Kruger effect](https://en.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect)
2. [Hanlon's Razor](https://en.wikipedia.org/wiki/Hanlon%27s_razor)
3. [Murphy's Law](https://en.wikipedia.org/wiki/Murphy%27s_law)
4. [Stockholm Syndrome](https://en.wikipedia.org/wiki/Stockholm_syndrome)
5. [Flow - psychology](https://en.wikipedia.org/wiki/Flow_(psychology))

Some of the things that are common about these entries are :-

1. Some of them are related to Programming, Open Source. (1, 2, 3)
2. All of them are one of `Adages`, `Aphorisms`, `Psychological syndromes`,
`Psychological principles`.
3. They are easy to understand, and behavior starts to make sense after
understanding their gists. (Especially with 1, 2, 4, 5)

I thought about naming the list :-

1. `awesome-behaviour` : Almost everything on the lit is related with behaviour,
except for entries like 3.
2. `awesome-psychology` : Entries list 2 and 3 do not fit.

So, I would like your opinion on :-

1. **Does an awesome list feel justified?**

  I do believe that a list must exist that has a list of all these things. Although, I think that the content is very fragmented. As there are a lot of things that could be part of this list, and the list could probably end up being called `awesome-miscellaneous`.
  
2. **Do you think that Wikipedia is the right source to link to, for entries like above?**
 
  I am slightly uncomfortable about using WikiPedia as the only source, because content keeps changing, and there's no concrete verification of the information being entered. Would you rather that the list have a link to the Wikipedia page, alongwith the link to a paper/article in a respected journal / blog post by a respected person in the field, along with the entry? This would make the list harder to build, and accept contributions to, but I guess it would be worth it, as everything there would actually be _curated_.
  
  Of course, this list would be something that you can consume in your free time and get to know
  more, so, in that perspective, Wikipedia seems good enough.

P.S. I have read the [Awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md), and the contributing guidelines for some awesome lists. Yet, I remain indecisive.

**Comment by sindresorhus** [comment]
1. I think it's a good idea. Though I can see how easy it would be to lose focus and end up being a misc list. It will need a clear tagline and contributing.md of what's acceptable, but also a good judgement on PRs. It's important that the list not only contain a list of links but a good succinct description of each item and why you should care.

2. Wikipedia is generally an ok source. I think it should also come with other good vetted sources about an item, preferably something less dry and more easily readable than Wikipedia.

**Comment by icyflame** [comment]
Thanks for your suggestions! I will get the list up and running as soon as I get some free time!
