### ISSUE TITLE
Add awesome-linuxaudio

### ISSUE THREAD

**Issue by nodiscc** [sindresorhus/awesome#232]
Shameless self-promotion :) https://github.com/nodiscc/awesome-linuxaudio/ is a list of software and resources for professional audio/video/live events production on Linux.

Patches welcome.

**Comment by sindresorhus** [comment]
Make sure your list follows: https://github.com/sindresorhus/awesome/blob/master/awesome.md

Especially the point about quality checking what you include. You seem to have included a lot of random things. Comments about why something is included would be useful.

Then submit a PR to get it added here.
