### ISSUE TITLE
Add "Awesome How to do Open Source" list

### ISSUE THREAD

**Issue by dirkmueller** [sindresorhus/awesome#2333]
@cornellius is maintaining https://github.com/cornelius/awesome-open-source which is an awesome listing on how to *do* open source. it is missing in the current list and as far as I can see fits the contribution requirements.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md

Someone would need to ensure it follows the requirements and then submit it.
