### ISSUE TITLE
List slack apps for developers

### ISSUE THREAD

**Issue by cosydney** [sindresorhus/awesome#2344]
I created a list of 50 slack apps for developers, happy to rewrite them in the same awesome format as you guys have if you think this would make sense? 

https://github.com/axolo-co/slack-apps-for-developers

Let me know and I can easily create a PR, 

Cheers

**Comment by sindresorhus** [comment]
Looks like a useful list. It would be welcome here.

https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md
