### ISSUE TITLE
Explain One Thing

### ISSUE THREAD

**Issue by fulldecent** [sindresorhus/awesome#2379]
Please explain in the README why One Thing is featured so prominently.

Is this something cool you like? (if so, please say so)

Are they paying you money? (if so, please say so, and that would be weird because that app does not make money... is it a virus or something where they make money another way?)

**Comment by sindresorhus** [comment]
It's my own app. I'm just doing some self promotion.

**Comment by fulldecent** [comment]
By failing to explain this in the README, this had the negative effect on me--it made me know I DON"T want this app. Maybe other people got the same impression.

This PR might help your cause to ensure the message is received in the appropriate light.
