### ISSUE TITLE
Awesome Cheminformatics Teaching Material

### ISSUE THREAD

**Issue by Sulstice** [sindresorhus/awesome#2483]
Hello,

I would like to submit this list of material I use to teach cheminformatics as an awesome list and whether this is appropriate? 

https://github.com/Sulstice/Cheminformatics-Teaching-Material

Thank you!
-Sulstice

**Comment by hallvaaw** [comment]
Hi @Sulstice,

Your list seems to be suitable for [Awesome Cheminformatics](https://github.com/hsiaoyi0504/awesome-cheminformatics#readme). You should try to submit it there.

**Comment by Deckojoof** [comment]
Can I blessed you some money hear 🤑💰💵

**Comment by Thefenix14** [comment]
Dinero

**Comment by Sulstice** [comment]
@Deckojoof @Thefenix14 oh sure haha.

**Comment by Thefenix14** [comment]
> Can I blessed you some money hear 🤑💰💵

Hola

**Comment by Rickeykarna** [comment]
yes please .
