### ISSUE TITLE
Add Technical Communication category

### ISSUE THREAD

**Issue by silopolis** [sindresorhus/awesome#2486]
This category would group lists about technical documentation, developer experience etc.

For starters, it could host #1883 , #2424 and #2288

The following would be candidate entries:

* https://github.com/testthedocs/awesome-docs 
* https://github.com/writing-resources/awesome-scientific-writing
* https://github.com/yoloseem/awesome-sphinxdoc

**Comment by benjaoming** [comment]
This would be really great - the LaTeX list might also fit well here: https://github.com/egeerardyn/awesome-LaTeX#readme

**Comment by benjaoming** [comment]
These two are also great candidates:

* Translation: https://github.com/mbiesiad/awesome-translations#readme
* Scientific Writing: https://github.com/writing-resources/awesome-scientific-writing#readme

**Comment by silopolis** [comment]
> These two are also great candidates:
> 
>     * Translation: [mbiesiad/awesome-translations#readme](https://github.com/mbiesiad/awesome-translations#readme)

This one made my day! Thanks for sharing.
Actually, I didn't mention translation as it wasn't clear to me  if that new category would really be the best place for it.
After searching for "awesome translation" here on GH, it appears that it could constitute an interesting small category, or maybe a bigger one if extended to all language related maters.

> Edit: Naming the category "Technical and Scientific Writing" might be better at tackling the intersection of these two fields.

Could be, but I'd keep "communication" over "writing" for a wider scope including other content types creation, information architecture, etc.

**Comment by benjaoming** [comment]
@silopolis I was curious to your choice of "communication" instead of "writing", I think your explanation makes sense.

**Comment by mcanouil** [comment]
I believe Quarto would also fit in that category instead of "Miscellaneous" https://github.com/sindresorhus/awesome/pull/2550

**Comment by phuc-hoang-39** [comment]
> This category would group lists about technical documentation, developer experience etc.
> 
> 
> 
> For starters, it could host #1883 , #2424 and #2288
> 
> 
> 
> The following would be candidate entries:
> 
> 
> 
> * https://github.com/testthedocs/awesome-docs 
> 
> * https://github.com/writing-resources/awesome-scientific-writing
> 
> * https://github.com/yoloseem/awesome-sphinxdoc
> 
>

**Comment by benjaoming** [comment]
@sindresorhus 

1) Would you accept a new topic "Technical and Scientific Communication" given the short motivation from above comments?

Documentation, technical writing, scientific writing and translation seems to be subtopics that can be covered.

2) How many entries constitute "critical mass"? I count ~5 _existing_ entries suggested to be moved there.

3) There are some suggestions that aren't current entries. We cannot include these, they have to be adopted separately.

If that's okay for a PR, it seems like the issue is actionable :+1:

**Comment by sindresorhus** [comment]
👍

**Comment by JoelStarzy** [comment]
Good idea

**Comment by JohnNewbold** [comment]
No need

**Comment by Jacqeneres** [comment]
Nice
