### ISSUE TITLE
[Suggestion] AWS  Cheatsheet

### ISSUE THREAD

**Issue by seifrajhi** [sindresorhus/awesome#2522]
Hello,
As I am working on a daily basis with AWS I was triggered that this cloud provider is not yet having a cheat sheet. Is it in the program?
Can I contribute? (for example with a sample of the cheatsheet?).

Thank you very much, I love this project!

**Comment by Charliebrickman75** [comment]
I am new to coding. What language do you suggest to learn first? Python or JavaScript

**Comment by Charliebrickman75** [comment]
> @Charliebrickman75 If you want to work only web related, better to start with javascript, or else go with python, in my opinion

Thank you so much. I have an idea for a fall, I would like to create an app that would connect people needing lawyer services to lawyers to bid on cases or projects in exchange for crypto/ goods or services.. should I try to start on github

**Comment by Charliebrickman75** [comment]
Ty
I have a great idea for a Dapp, attorneys and retired attorneys can bud on work, coins and services.

🙏🏼C.P BRICKMAN
Tobros International Business Brokerage

**Comment by magic-i-an** [comment]
–· ·· ––· ···· – ··· ·––· · ·–·· ·–·· ·–·–·– –·–· ·– ·–· ·–· –·· ·–·–·– –·–· –––

**Comment by crazytrain1970** [comment]
Can’t get my funds out ummmSent from my iPhoneOn Feb 12, 2023, at 2:23 AM, saifeddine Rajhi ***@***.***> wrote:﻿
Hello,
As I am working on a daily basis with AWS I was triggered that this cloud provider is not yet having a cheat sheet. Is it in the program?
Can I contribute? (for example with a sample of the cheatsheet?).
Thank you very much, I love this project!

**Comment by Charliebrickman75** [comment]
> @Charliebrickman75 yes that will be a good start to work with js-ES6 and blockchain, and try to learn git essentials so that you will be habitual with working with branches and versioning. Checkout git docs and freecodecamp for js tutorials.

How can I join a team to build my resume

**Comment by Jogai** [comment]
@seifrajhi that should go on this list: https://github.com/donnemartin/awesome-aws#readme
And please close this issue, because the rest of the discussion is just noise.

**Comment by seifrajhi** [comment]
@Jogai ok I will close right now
