### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Pratyushslimsady** [sindresorhus/awesome#2596]
on:
  pull_request:
    branches: [main]
    paths:
      - 'readme.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run lint check
        run: |
          chmod +x ./.github/workflows/repo_linter.sh
          ./.github/workflows/repo_linter.sh

**Comment by sindresorhus** [comment]
?

**Comment by hayyyyjax** [comment]
Why was the fetch ser to zero?

**Comment by Alaaryad** [comment]
Contact me
