### ISSUE TITLE
[Feature]  Trigger warning Rating

### ISSUE THREAD

**Issue by CBID2** [sindresorhus/awesome#2681]
## Introducing Myself 
Hi @sindresorhus! I'm CBID2, and I found this project via the Topics Tab on GitHub, so I'm excited to be here! :) 
##  Related Issue

Connects to #732 

## Concern
Adding more non-tech lists is a great idea. However, a possible problem that could occur is a person goes to a list (For context, let's say there's a list of Awesome Animated shows) and ends up finding content that might negatively affect their mental health(e.g., the murder scene in Invincible). 

## Solution
Add GitHub Action that automatically closes a pull request if a contributor does not add a trigger warning in their PR.

**Comment by ghasem1987** [comment]
ا****

**Comment by CBID2** [comment]
> ا****

I'm sorry. I don't understand

**Comment by sindresorhus** [comment]
Thanks for the suggestion. I don't see the need to have auto-closing of a pull request. I think most people have good sense for what is acceptable. We can add new rules to the guidelines when needed. Awesome has existed for many years without any kind of problem related to this.

**Comment by nthhanh526** [comment]
Text or RK

**Comment by nthhanh526** [comment]
Oophekep oaphinant

**Comment by nthhanh526** [comment]
Moment

**Comment by nthhanh526** [comment]
Magitek
