### ISSUE TITLE
How can we get non-git users to contribute PRs to awesome lists?

### ISSUE THREAD

**Issue by simonv3** [sindresorhus/awesome#269]
Could a bot be set up that does PRs running from a server somewhere that people who don't have github-foo can submit additions to a list for?

cc @RichardLitt

**Comment by sindresorhus** [comment]
You can easily edit from the GitHub UI. Most contributors does that.

Example: https://github.com/sindresorhus/awesome/edit/master/readme.md

**Comment by RichardLitt** [comment]
@simonv3 Why don't we make a nice 'How to Contribute' guide for all of the awesome lists? Maybe we could make a website for this?

**Comment by simonv3** [comment]
@sindresorhus Is the target demographic just people who have a github account? For example - I started awesome-zines, but the people who most likely know the most about zines might not be very big github users. 

Of course, maybe asking that people create a github account to contribute to these is a fine minimal step - especially if it gets them exploring the projects that are hosted here - and like @RichardLitt says - maybe creating a good contributing guide is good enough. 

Is there an objection to a bot if one gets built by someone (say if I have some spare time?)

**Comment by aleksandar-todorovic** [comment]
Do we really need a website for this?

In my opinion, this should be an addition to an issue #266 (but that issue will need to be resolved first). I honestly think that creating a couple of pictures into `contributing.md` is all that is needed.

@simonv3 Of course there is. The point of the awesome lists is to _only_ include awesome content and tell others why that content is awesome. If your bot is not an AGI, that won't work. :wink:

**Comment by RichardLitt** [comment]
Eh, I was thinking a website would be good because each Contribute.md for each thing can link to it, whereas having images in each one might get annoying. 

The bot wouldn't generate the content - rather, it would be a bot to help non-GitHub users add content. I don't have an objection to that at all.

**Comment by simonv3** [comment]
@aleksandar-todorovic You could have people include why they think something is awesome via the bots PR? The bot wouldn't automatically just include links.

Pictures would probably go a long way. You could also just link to one contribute.md file from the list (rather than setting up a website). But anyway - doesn't the gh-pages branch automatically create a website for any root level .md files? `website.github.com/readme`?

**Comment by RichardLitt** [comment]
I think pictures would be best. And yes, it does - I mentioned a website just because I thought it might be a wider thing. One contribute would work.
