### ISSUE TITLE
awesome-mastodon orphaned 

### ISSUE THREAD

**Issue by IamFlowZ** [sindresorhus/awesome#2724]
Hello!

I've tried reaching out a number of ways to the owner of the awesome-mastodon repo, and haven't gotten a response. It has almost 900 stars and people still trying to actively contribute. Was wondering if there's any way we could redirect the link to one of the forks? Or through some other means make it available seeing as how mastodon has gained a lot of popularity in recent history.

**Comment by sindresorhus** [comment]
I'm happy to change the link if someone else can commit to maintain a fork.

**Comment by IamFlowZ** [comment]
Hey there, just checking in on this.

**Comment by atumcurrency** [comment]
](https://www.dropbox.com/scl/fi/bj0vk4rd5ysz0rt8m3kvt/2023-09-11-07.51.06.pdf?rlkey=7r20m2ca4sq4ypka7nw0cdsrj&dl=0)

**Comment by NewAlexandria** [comment]
@IamFlowZ why don't you start by just cloning the repo, updating it for @sindresorhus current norms of awesome lists, then submit a PR for it here. 

Then once your repo is being pointed to, it should be easy to ask people to open PRs against yours, or patch-apply their PRs if any of them are unresponsive.

**Comment by asim339** [comment]
Hi
