### ISSUE TITLE
Add Large language models frontends ?

### ISSUE THREAD

**Issue by iChristGit** [sindresorhus/awesome#2877]
There are plenty of amazing LLM "chatgpt" like webuis and interfaces., they are all open source and I think they deserve a small section.

Some examples:

https://github.com/huggingface/chat-ui
https://github.com/oobabooga/text-generation-webui
https://github.com/ParisNeo/lollms-webui/
https://github.com/h2oai/h2ogpt
https://github.com/SillyTavern/SillyTavern
https://github.com/NimbleBoxAI/ChainFury
https://github.com/nomic-ai/gpt4all
https://github.com/imartinez/privateGPT

What do you think?

**Comment by sindresorhus** [comment]
Looks like this was opened on the wrong repo.

**Comment by iChristGit** [comment]
> Looks like this was opened on the wrong repo.

Where should this be posted at? I thought this is the main repo .
