### ISSUE TITLE
Implementation of awesome-sample-apps

### ISSUE THREAD

**Issue by alferov** [sindresorhus/awesome#289]
I apologize in advance if someone had this idea before, but what if it would be created a list that would contain links to open-sourced applications.

For example:
- Ruby
  - Rails
    - [railstutorial/sample_app](https://github.com/railstutorial/sample_app) - Ruby on Rails Tutorial sample application.
- JavaScript
  - Angular
    - [ProtonMail/WebClient](https://github.com/ProtonMail/WebClient) - Official AngularJS Web Client for ProtonMail.
  - React
    - [ipselon/react-ui-builder](https://github.com/ipselon/react-ui-builder) - React UI Builder.

It would be beneficial for everyone, who starts playing around with a new framework and prefers to learn by reading code.
I can start working on it (if it hasn't been implemented yet :smile:).
Thanks!

**Comment by sindresorhus** [comment]
Sounds like a cool idea. Go ahead. Make sure you quality check everything you include.

-

Please read the [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.
