### ISSUE TITLE
Static Site Generator

### ISSUE THREAD

**Issue by akhyarrh** [sindresorhus/awesome#291]
Currently, there's no awesome list contain a resource for static site (hosting, comment system, etc). I sometime need to do a little digging to find something I need. So awesome list contain a resource related to static site would be awesome.

We don't need list for static site generator, but a resource for it. Netlify already have awesome list [here](http://www.staticgen.com/) ([source](https://github.com/netlify/staticgen)).

Some list are exist:

- [myles/awesome-static-generators](https://github.com/myles/awesome-static-generators) - last commit 27 Apr
- [planetruby/awesome-staticgen](https://github.com/planetruby/awesome-staticgen) - last commit 2 Jul
- [rogeriopradoj/awesome-static-site-generator](https://github.com/rogeriopradoj/awesome-static-site-generator) - last commit 17 days ago

I open issue here to ask how about make awesome list related to static site (hosting, comment system, embedding service, payment, etc) ?

**Comment by sindresorhus** [comment]
I'm not totally sure what you're asking? Do you want to create such list or are you asking if someone can do it? Also not sure exactly what you want the list to contain?

**Comment by staxmanade** [comment]
Take a look here https://staticsitegenerators.net/

**Comment by akhyarrh** [comment]
Sorry for late reply. I ask someone to create a list that contain things like hosting, embedded service, etc but only for static site

**Comment by myles** [comment]
I can add some more resources for running a static web site to my awesome list.

**Comment by aharris88** [comment]
I've started a list like this: https://github.com/aharris88/awesome-services-for-static-websites

**Comment by gutierri** [comment]
It could be equal to VIM category, a URL to https://staticsitegenerators.net/ or https://www.staticgen.com/

?

**Comment by akhyarrh** [comment]
aharris88 already started what I'm looking for. This issue can be closed when aharris88's repo merged.

**Comment by aharris88** [comment]
@akhyarrh I'm just working on writing descriptions for each thing on my list and then I'll open a pull request to add it to this list.
