### ISSUE TITLE
Guidelines on subpages

### ISSUE THREAD

**Issue by lskatz** [sindresorhus/awesome#2967]
Are there guidelines if we want to make a sub page? I have a category that might get extremely large and so I want it to be on its own page.

**Comment by sindresorhus** [comment]
It's hard to define an absolute guideline as it depends on the content. In general, you should try to keep everything in the readme file as it makes it easier to navigate and search. In addition, if you have so much content that it requires sub-pages, maybe consider whether you have too much content. Awesome lists are supposed to be a curation of the best, not everything.

**Comment by lskatz** [comment]
Thanks! That is a good perspective.

**Comment by EmailScraper** [comment]
?

**Comment by Jogai** [comment]
Also, pay attention to: [the-awesome-manifesto](https://github.com/sindresorhus/awesome/blob/main/awesome.md#the-awesome-manifesto)
