### ISSUE TITLE
Awesome badge height

### ISSUE THREAD

**Issue by vasili111** [sindresorhus/awesome#298]
Can you please change Awesome badge height so that it will have same height as other badges. For example, in [awesome-AutoHotkey list](https://github.com/ahkscript/awesome-AutoHotkey) awesome badge has different height in comparison to other badges. I think it will look more nice if all badges will have same height.

**Comment by sindresorhus** [comment]
I'm using the same height as TravisCI, Coveralls, and most other badges, so it's your other ones that have the "wrong" height.

<img width="710" alt="screen shot 2015-08-28 at 22 11 17" src="https://cloud.githubusercontent.com/assets/170270/9549741/d1a7c72c-4dd1-11e5-989a-d0116de55182.png">
