### ISSUE TITLE
Add New List: Awesome Machine Learning

### ISSUE THREAD

**Issue by MasterOfBrokenLogic** [sindresorhus/awesome#3116]
I would like to suggest adding a new list for Machine Learning resources. This list includes curated resources such as tutorials, frameworks, datasets, and more. Here is the link to the list: [awesome-machine-learning](https://github.com/josephmisiti/awesome-machine-learning).

Thank you for considering this addition! ❤️

**Comment by sindresorhus** [comment]
This is already added. Please spend some more effort before opening an issue.
