### ISSUE TITLE
Soundcloud

### ISSUE THREAD

**Issue by MandeepSinghPB08** [sindresorhus/awesome#3179]

**Comment by j2346391** [comment]
closed forever please
i'm helping you to clean this mess. the only thing is closed? that's super
coward of you!
That's why you are keeping producing a lot of boys and girls and you are
killing them.
Mahalo,

*Abao *



MandeepSinghPB08 ***@***.***> 於 2024年9月7日 週六 下午3:25寫道：

**Comment by j2346391** [comment]
If I'm the god, i'll close your computer first.
Mahalo,

*Abao *



陳阿寶 ***@***.***> 於 2024年9月7日 週六 下午6:58寫道：

**Comment by j2346391** [comment]
you are the under a murder of 8 billion of people so sooooooon.
you made it but someone tried to assist you.
Come on, you never try.
Accept the exception of the inception
Mahalo,

*Abao *



陳阿寶 ***@***.***> 於 2024年9月7日 週六 下午6:59寫道：

**Comment by MandeepSinghPB08** [comment]
Thanx for help
