### ISSUE TITLE
create-list.md not clear about license and contributing in footernote

### ISSUE THREAD

**Issue by mikbry** [sindresorhus/awesome#3216]
I read carefully the doc to check [Awesome-WebGPU](https://github.com/mikbry/awesome-webgpu), I started it several years ago. So we need to clean it up. But one part is not clear regarding the footernote:
`Do not add the license name, text, or a Licence section to the readme.` Ok but if I want to add:
```
To the extent possible under law, [Mik Bry](https://github.com/mikbry) has waived all copyright and related or neighboring rights to this work.
```
You give an [Example](https://github.com/woop/awesome-quantified-self) that is made like that, but it doesn't pass awesome-lint...

Same for contributing, should I put it in the footernote ?

Thanks for your great work !

**Comment by CiCi2019-cu** [comment]
Delete
