### ISSUE TITLE
CoffeeScript

### ISSUE THREAD

**Issue by faustinoaq** [sindresorhus/awesome#323]
I'm sorry, i don't readed the guidelines. [My mistake](https://github.com/sindresorhus/awesome/pull/322)
I will work in an awesome-coffeescript after read the guidelines
I like CoffeeScript and its Python syntax, but What do you think about CoffeeScript today?
Is TypeScript better than CoffeeScript?
Did we need CoffeeScript?,
It's just Javascript

**Comment by sindresorhus** [comment]
I personally think CoffeeScript is dead now that ES2015 (through [Babel](https://babeljs.io)) and TypeScript is mainstream.
