### ISSUE TITLE
What Are the Criteria for “No Blockchain-Related Lists” in Pull Request Guidelines?

### ISSUE THREAD

**Issue by yijun-lee** [sindresorhus/awesome#3302]
Looking at the pull request requirements, there’s a condition stating **“No blockchain-related lists.”** 
What exactly is the criterion for this? 
There are already some “blockchain-related” items on the existing awesome list, and it seems like the current PR also includes such items.

**Comment by sindresorhus** [comment]
There are too many blockchain projects that are pure scam and I don't want to spend a lot of time investigation whether the submissions are such projects.

---

> There are already some “blockchain-related” items on the existing awesome list

The work was already done with those.

**Comment by CiCi2019-cu** [comment]
Clear all
