### ISSUE TITLE
NoSQL

### ISSUE THREAD

**Issue by ffffranklin** [sindresorhus/awesome#349]
Maybe it's too-early-in-the-game for this but it would be ~~nice~~ **awesome** to see a list on NoSQL.  Data structuring best practices, tutorials, talks and articles.  Some links I've come across in the past:
- https://www.firebase.com/docs/web/guide/structuring-data.html
- http://blog.nahurst.com/visual-guide-to-nosql-systems
- http://docs.mongodb.org/manual/core/data-modeling-introduction/
- https://highlyscalable.wordpress.com/2012/03/01/nosql-data-modeling-techniques/

**Comment by erictleung** [comment]
Here's some awesome links I found on NoSQL:

- Introduction to NoSQL - Martin Fowler (https://www.youtube.com/watch?v=qI_g07C_Q5I)
- Seven Databases in Song (https://www.youtube.com/watch?v=jyx8iP5tfCI)
- NoSQL Databases: An Overview (https://www.thoughtworks.com/insights/blog/nosql-databases-overview)
- List of >200 NoSQL databases to choose from (http://nosql-database.org/)
- NoSQL Tutorial for Beginners (https://www.youtube.com/playlist?list=PLb5HO8RZjX-nZgYoTRhMB32Lq-Sz-b3o5)

**Comment by sindresorhus** [comment]
@erictleung Did you read and watch all of those and can vouch for their quality?

**Comment by erictleung** [comment]
The only one I haven't watched/read all the way was the NoSQL tutorial for beginners (it's a series). It looks like to be a rip from some Lynda.com videos. So you don't need to include that one but the rest should be good. The "Seven Databases in Song" is for fun :smile:. Also, I'm not an expert on NoSQL systems but I found most of these links to help me understand them.

**Comment by davisonio** [comment]
@jasonkying has made a draft over here: https://github.com/jasonkying/awesome-NoSQL Unfortuntely there's no links yet :)

**Comment by erictleung** [comment]
awesome-sysadmin has a couple links on some of the more popular NoSQL databases (https://github.com/kahun/awesome-sysadmin#nosql) but http://nosql-database.org/ is more extensive.

**Comment by erictleung** [comment]
I've started my own `awesome-nosql` repo [here](https://github.com/erictleung/awesome-nosql). It's a work in progress. I'll make a PR here once I feel it is mature enough to add.
