### ISSUE TITLE
Include Awesome AWS in the list

### ISSUE THREAD

**Issue by swaroopch** [sindresorhus/awesome#360]
https://github.com/donnemartin/awesome-aws

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

**Comment by sindresorhus** [comment]
Looks very comprehensive and high quality, so happy to include it at that point. Just submit a PR then.

// @donnemartin

**Comment by donnemartin** [comment]
@sindresorhus thanks for the feedback, I was going to wait until 2 week mark before submitting the PR :)

**Comment by sindresorhus** [comment]
I know the delay might seem annoying, but it has successfully filtered out a lot of hit'n'run lists.

**Comment by donnemartin** [comment]
No problem Sindre.

And thanks for the mention @swaroopch.
