### ISSUE TITLE
Starting my awesome list, DevOps

### ISSUE THREAD

**Issue by joubertredrat** [sindresorhus/awesome#409]
On this week I will finish this

https://github.com/joubertredrat/awesome-devops

Is possible to add in your list when I finish?

**Comment by aleksandar-todorovic** [comment]
It is absolutely possible _if_ you take your time to read [the awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md), [contributing.md](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and [create-list.md](https://github.com/sindresorhus/awesome/blob/master/create-list.md) and make sure that your list complies with the requirements stated in these files.

**Comment by arthurvr** [comment]
Going to close this issue, just open a PR when the list is finished and matured a little :) 

Thanks!
