### ISSUE TITLE
Maintainer wanted for COBOL list

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#414]
The current maintainer @dshimy doesn't seem active. Would be happy to switch the link to an actively maintained fork if anyone is interested.

https://github.com/dshimy/awesome-cobol

**Comment by kdabir** [comment]
Why maintain a prank? Anyways those links are not real. Someone copied the links from awesome go.

**Comment by sindresorhus** [comment]
Lol, I didn't realize.
