### ISSUE TITLE
For Girls.

### ISSUE THREAD

**Issue by cristianoliveira** [sindresorhus/awesome#424]
A list of awesome inclusive events/projects/initiatives for women in the tech area. :rose: :computer: :gift_heart:
https://github.com/cristianoliveira/awesome4girls

**Comment by sindresorhus** [comment]
Good idea :)

**Comment by sindresorhus** [comment]
Please read the [instructions](https://github.com/sindresorhus/awesome/blob/master/create-list.md) for creating a new list, [contributing guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and the [awesome manifest](https://github.com/sindresorhus/awesome/blob/master/awesome.md).

Especially this part:

> Wait at least a couple of weeks after creating a list before submitting to give it a chance to mature.

After that do a pull request.

**Comment by cristianoliveira** [comment]
Hey @sindresorhus, thanks.
No problem, I will wait. :)
