### ISSUE TITLE
Meteor + TheIntern.io - Automate Testing Link

### ISSUE THREAD

**Issue by harpreetkhalsagtbit** [sindresorhus/awesome#444]
Hi

I have developed a tutorial for Automate Functional Testing of **Meteor** with **TheIntern.io**. 

**Environment Setup**
https://gist.github.com/harpreetkhalsagtbit/ffb4cea37fcc02efa250

**Example Tutorial - Meteor + TheIntern**
https://gist.github.com/harpreetkhalsagtbit/55022792c1b6ab4367c4

Please have a look at these link and let me know if you think these links are usefull. How can I contribute this to your repo?

**Comment by aleksandar-todorovic** [comment]
> How can I contribute this to your repo?

You can't. This is a list of other awesome lists. Your tutorial is not a list. You can add this to one of the lists listed in this list (not really familiar with functional testing, so I'm not sure which one is appropriate).
