### ISSUE TITLE
found a bunch of repos that are maybe not in here

### ISSUE THREAD

**Issue by pokeball99** [sindresorhus/awesome#470]
https://github.com/search?q=d7305f38d29fed78fa85652e3a63e154dd8e8829&ref=searchresults&type=Code&utf8=%E2%9C%93
this all github ¨awesome¨ repos that can be found with the awesome badge(~500), just putting this here so someone can go though them

**Comment by imcaffrey** [comment]
@pokeball99 The main reason most repos not here might be that they are still building, or they are maintained for personal use.D

**Comment by pokeball99** [comment]
@imcaffrey true, but it still is nice to see if there are any hidden gems out there

**Comment by imcaffrey** [comment]
@pokeball99 I agree with you.

**Comment by sindresorhus** [comment]
Feel free to go through it, but I highly doubt you'll find much worth adding.
