### ISSUE TITLE
Mongo?

### ISSUE THREAD

**Issue by RickyGeek** [sindresorhus/awesome#477]
I just came for the first time on this repo, I searched for Mongo and ... surprise, not even a single link about Mongodb? why?

**Comment by aleksandar-todorovic** [comment]
Because nobody created an awesome list about MongoDB?

**Comment by aleksandar-todorovic** [comment]
Yup, I was right. GitHub search returned nothing, so I'm going to close this. Feel free to create a list (take a look at the [awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md) and submit it here.

**Comment by sindresorhus** [comment]
Hah, no wonder. Very few people still consider MongoDB awesome :p

**Comment by feimosi** [comment]
@RickyGeek How about this one: [ximaoxo/awesome-mongodb](https://github.com/ximaoxo/awesome-mongodb) ?
@sindresorhus would you add it? Does it qualify for your list? Awesome or not, that's a personal opinion ;)

**Comment by sindresorhus** [comment]
@feimosi Doubtful. It haven't been updated in almost a year and is far from good enough to be added. If people want a MongoDB, someone make a better one that is maintained.

**Comment by ramnes** [comment]
I have initiated a MongoDB list here: https://github.com/ramnes/awesome-mongodb

Just tell me if you want me to make a PR. I didn't do it already because of the "few weeks maturation" rule. :)

**Comment by davisonio** [comment]
> @ramnes Just tell me if you want me to make a PR. I didn't do it already because of the "few weeks maturation" rule. :)

Great list! :+1:  It looks good to submit here now considering [first commit](https://github.com/ramnes/awesome-mongodb/commit/0ec1f8f977dc2a581ef2fe91cda1c847add41ef9) was a few months ago.

**Comment by ramnes** [comment]
@davisonio, done. :+1:
