### ISSUE TITLE
API to search / fetch awesome data

### ISSUE THREAD

**Issue by millaisnick** [sindresorhus/awesome#501]
I was wondering if someone is already working on an API to be able to fetch the different awesome lists. Basically I am thinking of a simple script that will wget or curl the markdown and parse, pick your best heuristic, the lists to retrieve something like:

```
$  awesome awesome
```

```
{
  name: awesome-nodejs,
  url: https://github.com/sindresorhus/awesome-nodejs
  ...
}
```

You should be able to get the items from any awesome list if you indicate either a name or url.

**Comment by sindresorhus** [comment]
Yes, see: https://github.com/sindresorhus/awesome/issues/427

// @lockys
