### ISSUE TITLE
Do you think conventional-changelog belongs here?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/awesome#516]
https://github.com/ajoslin/conventional-changelog and the cli https://github.com/stevemao/conventional-changelog-cli

Its a tool to generate a changelog from git metadata. Used by angular and jshint. It can be used for both front-end and back-end development.

If not, does it belong to your other list? Thanks.

**Comment by sindresorhus** [comment]
No, this is a list of lists.

#509 #461 https://github.com/sindresorhus/awesome/pull/373 https://github.com/sindresorhus/awesome/pull/319 https://github.com/sindresorhus/awesome/pull/183
