### ISSUE TITLE
A possible duplicate but a different layout

### ISSUE THREAD

**Issue by lnishan** [sindresorhus/awesome#517]
Recently I made my list for competitive programming: [lnishan/awesome-competitive-programming](https://github.com/lnishan/awesome-competitive-programming)

I wasn't aware that there was a repo under a similar name: [hkirat/awesome-competitive-coding](https://github.com/hkirat/awesome-competitive-coding)

First of all, I believe the better term is "Competitive Programming". (See [Competitive programming - Wikipedia](https://en.wikipedia.org/wiki/Competitive_programming))  
Secondly, the layout is vastly different. I listed many more websites and covered different aspects of competitive programming. I cannot really think of a way to cooperate besides adding a link to his list.

More importantly, part of the reasons why I made this list is that there are already several similar lists out there and none of them is complete. (See my [List of lists](https://github.com/lnishan/awesome-competitive-programming#list-of-lists) and [Open courses](https://github.com/lnishan/awesome-competitive-programming#open-courses) section)

What would be a good way to resolve this issue?

**Comment by sindresorhus** [comment]
Hard for me to judge as I have little knowledge in the field of competitive programming. This project lists the best lists, not just the first. We have multiple times switched out existing lists with something better. If you really can't collaborate (which I would recommend), try making the best list for this. That mean being strict about what's being added, actively maintain it, and make sure it's well organized. The existing list here isn't very actively maintained, so let's give it a month and if you're still maintaining your list, ping me and I'll consider replacing the existing one with yours. Sounds good?
