### ISSUE TITLE
Can I order pizza here?

### ISSUE THREAD

**Issue by dikiaap** [sindresorhus/awesome#544]
Need help with it.

**Comment by sindresorhus** [comment]
![image](https://cloud.githubusercontent.com/assets/170270/13265249/7bcf8276-daa4-11e5-997f-7d4e19e8ee4f.png)

**Comment by aleksandar-todorovic** [comment]
Sure thing!

What's your address?

**Comment by dikiaap** [comment]
@aleksandar-todorovic You can ship to Coordinate 3° 12' 43.2" South & 5° 12' 39.6" West

Actualy, I'm at moon.

**Comment by gld1982ltd** [comment]
nonsensical nonsense

**Comment by dikiaap** [comment]
@gld1982ltd thanks, u is bro.
