### ISSUE TITLE
Revisit applying alpha sorting of lists

### ISSUE THREAD

**Issue by AllThingsSmitty** [sindresorhus/awesome#548]
This project has grown considerably in the last year. Perhaps it's worth revisiting the past suggestion that lists and categories be sorted alphabetically.

Reference: https://github.com/sindresorhus/awesome/issues/112

**Comment by sindresorhus** [comment]
I don't really see how that changes anything. My opinion still stands that it's not worth the overhead and if you're one of the few that actually looks for an existing list (most use this to discover things), you can more easily find it with <kbd>Cmd+F</kbd>.

However, I could use some help trying to make the Misc section smaller by inventing some new categories. Although, a category should have at least 2, preferably 3 items.

**Comment by AllThingsSmitty** [comment]
I can take a look at the Misc. section. It's probably best to close this and open an new Issue for tracking.

**Comment by pravic** [comment]
What about to sort a Programming languages section?
