### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [sindresorhus/awesome#556]
Hi there!
This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because I want to give some of money to awesome list, but there is no donate button o something like that.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like awesome list. 

Thanks for this great work!

**Comment by sindresorhus** [comment]
I appreciate the gesture, but I don't accept donations. Donate to a [good cause](https://girlswhocode.com) instead ;)

-

https://github.com/sindresorhus/ama/issues/68 https://github.com/sindresorhus/ama/issues/160

**Comment by Francolpm** [comment]
Okay @sindresorhus ! I take your advise. 
Please close this false issue! 
Cheers!
