### ISSUE TITLE
Awesome Birmingham?

### ISSUE THREAD

**Issue by LimeBlast** [sindresorhus/awesome#592]
Hi, I wanted to check with you if it would be acceptable to create an Awesome [Birmingham](https://www.wikiwand.com/en/Birmingham) list?

I run a local tech community forum in Birmingham, and feel that this would be a cool little project for the community to get behind - contributing to a list of all the awesome things in Birmingham (attractions, restaurants, companies, areas of natural beauty, etc..).

This is a little outside the other lists you've got here, so before we got started, I wanted to check if such a list would be accepted among your lists.

Thank you.

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/awesome/issues/153.

**Comment by aleksandar-todorovic** [comment]
This should probably be closed since #153 is the right place to discuss this.
