### ISSUE TITLE
Add a new category - Lists various websites where one can practice coding

### ISSUE THREAD

**Issue by hkasera** [sindresorhus/awesome#633]
Hello,

I would like to request for adding a new list to the awesome list. This new list enumerates various websites where one can practice coding.

I created a [repository](https://github.com/hkasera/practice-coding) for the same and then got to know about awesome list. I think it would be great if this list can be a part of it.

Let me know if this is a welcome contribution!

Cheers,
Harshita Kasera

**Comment by sindresorhus** [comment]
I think already exists. See: https://github.com/karlhorky/learn-to-program Maybe contribute to that on instead?

**Comment by hkasera** [comment]
Thank you! I was not aware of this 👍
