### ISSUE TITLE
PR template to "enforce" contribution guidelines?

### ISSUE THREAD

**Issue by egeerardyn** [sindresorhus/awesome#650]
How about adding a [PR template](https://github.com/blog/2111-issue-and-pull-request-templates) to make the contribution guidelines stand out more and maybe even make it easier to spot lazy PRs?

I was thinking something along the lines of a checklist:

> Added **your URL here**
>
> - [ ] I have read and understood the [contribution guidelines](https://github.com/sindresorhus/awesome/blob/master/contributing.md).
> - [ ] This PR (and commit) have a descriptive title.
> - The list I added
>   - [ ] is not a duplicate,
>   - [ ] has been around for a few weeks,
>   - [ ] only has awesome items with descriptions,
>   - [ ] contains the awesome badge,
>   - [ ] has been checked for inconsistent formatting, spelling and grammar,
>   - [ ] has been added at the bottom of the appropriate category.
> - [x] I will click on anything, so feel free to close this PR.

I know, this won't stop every halfwit, but, I hope it will reduce the number of dumb PRs by a significant amount.

**Comment by aleksandar-todorovic** [comment]
I like this idea a lot!
