### ISSUE TITLE
Request awesome list "admins" to move repos to awesome-lists organization

### ISSUE THREAD

**Issue by pokeball99** [sindresorhus/awesome#661]
https://github.com/awesome-lists
this would be great in case some of the repo owners go MIA or else,someone else could pick it up, it would also just be great to put these in a single account
@sindresorhus what do you think about this, agree? or maybe the idea needs improvement?

**Comment by sindresorhus** [comment]
I set that org up in case an owner doesn't want to maintain/own a list anymore. I'm not going to actively encourage people to move lists there. In general lists are better off with a [BDFL](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life).
