### ISSUE TITLE
Encryption list

### ISSUE THREAD

**Issue by sobolevn** [sindresorhus/awesome#663]
Maybe someone is interested in creating and maintaining the `awesome-ecryption` list?
It might be useful. 

Quick googling and searching github said that's nothing like it: https://github.com/search?utf8=%E2%9C%93&q=awesome+encryption&type=Repositories&ref=searchresults

**Comment by davisonio** [comment]
There's an awesome Cryptography list: https://github.com/MaciejCzyzewski/retter ([website](http://maciejczyzewski.me/retter/)).

**Comment by sobolevn** [comment]
Well, a lot of resources from there might be useful.
I have created a project for `cryptography`: https://github.com/sobolevn/awesome-cryptography
It will be a hard work to fill it. Contributions, as always, are welcome.

@sindresorhus thanks, for https://github.com/sindresorhus/awesome/blob/master/create-list.md

**Comment by guoxiangwen** [comment]
> a lot of resources from there might be useful.

test

**Comment by sindresorhus** [comment]
Closing as this didn't get any traction.
