### ISSUE TITLE
proposal for adding awesome-nlp to the list

### ISSUE THREAD

**Issue by keonkim** [sindresorhus/awesome#677]
I've searched through the awesome list (which was awesome) and found [Speech and Natural Language Processing](https://github.com/edobashira/speech-language-processing) but its content is more of Language Modelling rather than Natural Language Processing.

So I've been building this new awesome list  called [awesome-nlp](https://github.com/keonkim/awesome-nlp) and this only contains lists of Natural Language Processing, not language modelling.
I wanted to add this list to the sindresorhus/awesome to gain more accessibility.

So I wanted to hear admin's thoughts before I make a pull request.
Of course, I am going to adjust and refine to adhere the rules before I make the request.

**Comment by sindresorhus** [comment]
Sure.

-

Unrelated to your request, but do you think that list is a good resource? I've been considering removing it as it's been unmaintained for a year.

**Comment by keonkim** [comment]
@sindresorhus I am not sure. But this is a really quickly moving field and the owner seems to be not maintaining the list (there are 10 pull requests unanswered, the earliest from may 2015)

Some links are pointing to blank or wrong pages, too.

**Comment by sindresorhus** [comment]
How is the list coming along?

**Comment by the-ethan-hunt** [comment]
@sindresorhus , sorry for the delay! 
The list has been growing for the last two years. We now have two more active maintainers to help @keon - @NirantK,  and me. There has been a significant development in the awesome-nlp list- 

- We now have separated NLP sections for other languages.
- The list complies with the `awesome` guidelines only with the exception of a cover image. We are working on that too. :smile: 
- Research papers on new topics in the field have been added and courses have been updated regularly.

I wanted to hear the admin's thoughts before pulling the request. We would adhere to all the rules before we make the request.
