### ISSUE TITLE
addition of best practices list

### ISSUE THREAD

**Issue by jcoady9** [sindresorhus/awesome#693]
Hello, I have been working on [awesome-best-practices](https://github.com/jcoady9/awesome-best-practices) an awesome list of best practices and style guides for various programming languages and I think it would be a good addition to your list. I was wondering what the admin thought before I make a pull request. Thank you for your time!

**Comment by sindresorhus** [comment]
There's already one for style guides: https://github.com/RichardLitt/awesome-styleguides Maybe if you focus just on best practices, but not sure there's enough content for that.
