### ISSUE TITLE
A single page application for awesome lists

### ISSUE THREAD

**Issue by ankitgyawali** [sindresorhus/awesome#703]
Thank you @sindresorhus and the community for creating such a useful resource. Last week I decided to create an interface for awesome lists by parsing all the lists using python and displaying them using angularJS as a SPA. 

The repository for the project and link to the interface can be found here: https://github.com/ankitgyawali/awesome-interface

I was able to parse most of the awesome lists as they followed the awesome manifesto although the parsers definitely has room for improvement. Now, I wanted to ask you if you had any advice on any changes I could make to this project. I have some ideas on expanding on the project but I thought it would be a good idea to see what you think before dedicating more time on it.

**Comment by sindresorhus** [comment]
Nice! :)

See https://github.com/sindresorhus/awesome/issues/427 for a similar discussion.

-

Some feedback:

- I would make the font larger.
- Items seems to be missing descriptions: https://ankitgyawali.github.io/awesome-interface/#/awesome/%20Platforms/Node.js
- This one didn't seem to parse: https://ankitgyawali.github.io/awesome-interface/#/awesome/%20Platforms/Heroku
- The awesome logo in the header is very blurry on high-DPI screens.

**Comment by ankitgyawali** [comment]
The missing descriptions are because my parser fails to extract data from some of the markdowns. I am looking into @wooorm 's markdown processor which seems to do a much better job.
Anyways, I don't see any point in maintaining this project since a similar project is already maintained by @lockys
I will however make the font & logo changes as you suggested. Thanks for your time!
