### ISSUE TITLE
Provide a TravisCI script that automatically adds/removes 'NEW' labels to awesome entries 

### ISSUE THREAD

**Issue by aschrijver** [sindresorhus/awesome#709]
Awesome project is awesome, but a big drawback to me is that it is hard to see which entries have been added since the last time I checked. So I often find myself checking the commits, and even the code changes if the commit message was unclear.

Just like the `awesome` badge there should be a script that marks entries with a consistent 'NEW' label when they are committed and subsequently checks whether other 'NEW' labels in the list still deserve that label. There could be a configurable time an entry is considered new (e.g. 30 days by default).

**Comment by sindresorhus** [comment]
Not something I want here, but would be a better fit on one of the Awesome websites, like https://github.com/lockys/AwesomeSearch Try requesting it there. See https://github.com/sindresorhus/awesome/issues/427.

**Comment by aschrijver** [comment]
Thanks, I will do that!
