### ISSUE TITLE
Add an Awesome Redux List

### ISSUE THREAD

**Issue by brillout** [sindresorhus/awesome#714]
I have a Redux List https://github.com/brillout/awesome-redux.
There is also https://github.com/xgrommx/awesome-redux.
I just recently made mine public and xgrommx's list is more "popular".
In that sense it is xgrommx`'s one that should be on the awesome list.

@xgrommx

Are you interested to be on the awesome list?

I'd be up for collaboration, if you are interested.
But I would be more strict about what resources should be on the list.
I consider many low quality / not useful enough.

**Comment by sindresorhus** [comment]
[My comments](https://github.com/sindresorhus/awesome/pull/348#issuecomment-146644959) about `xgrommx/awesome-redux` seems to still apply. It's messy and more of collection than a curation. Don't get me wrong, it's still a good resource, just not a good fit for this list.

@brillout I'm open to adding your list if you're committed to maintaining it. Your list could use more learning resources though, like blog posts, videos, talks, etc. @markerikson has a good resource on everything Redux: https://github.com/markerikson/react-redux-links

**Comment by brillout** [comment]
@sindresorhus Thanks for the link, it looks good.

Ok, I'll create a PR once I feel the list to be ready.
