### ISSUE TITLE
Proposal for adding TastyToast

### ISSUE THREAD

**Issue by yadav-rahul** [sindresorhus/awesome#731]
[TastyToast](https://github.com/yadav-rahul/TastyToast)  is an Android Library which helps an user to get rid of their native Android Toast.

TastyToast helps the user by characterising the type of Toast into five main category which are success, danger, warning, info and default.

For each default category, it not only changes background and text colour but also adds tasty Custom View on the left side of Toast.

**Comment by sindresorhus** [comment]
This is a list of awesome **lists**, not things.
