### ISSUE TITLE
Awesome code analysis

### ISSUE THREAD

**Issue by mr-karan** [sindresorhus/awesome#736]
>coala provides a unified command-line interface for linting and fixing all your code, regardless of the programming languages you use.
coala has a set of official bears (plugins) for several languages, including popular languages such as C/C++, Python, JavaScript, CSS, Java and many more, in addition to some generic language independent algorithms.

For more info: https://github.com/coala-analyzer/coala

**Comment by sindresorhus** [comment]
> Curated list of awesome **lists**
