### ISSUE TITLE
Please add Awesome Linux Software

### ISSUE THREAD

**Issue by VoLuong** [sindresorhus/awesome#752]
I made this [here](https://github.com/VoLuong/Awesome-Linux-Software) . I hope it will be put under Linux section. 
Thank you

**Comment by sindresorhus** [comment]
Read https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md, and ensure your list complies. Then do a pull request adding it :)
