### ISSUE TITLE
Link to awesome-postgres

### ISSUE THREAD

**Issue by lohfu** [sindresorhus/awesome#757]
hey, just found an awesome list (https://github.com/dhamaniasad/awesome-postgres) that is not listed here...

**Comment by sindresorhus** [comment]
Sure, do a pull request. Last time it was submitted (https://github.com/sindresorhus/awesome/pull/421), it didn't have a lot of content, but that seems to have changed.

Make sure to read https://github.com/sindresorhus/awesome/blob/master/contributing.md and https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

// @dhamaniasad
