### ISSUE TITLE
Front-end for Awesome lists

### ISSUE THREAD

**Issue by brillout** [sindresorhus/awesome#767]
I've built a frontend for a list of react components: [devarchy.com/react-components](http://devarchy.com/react-components). (The list on Github: [github.com/brillout/awesome-react-components](https://github.com/brillout/awesome-react-components).)

It is open source ([github.com/brillout/devarchy](https://github.com/brillout/devarchy)). Maybe it could be useful for other lists as well.

Especially for lists with many GitHub links since the frontend is largely based on information provided by GitHub (like last commit date, repository creation date, number of stars, readme, etc.).

The main focus of the frontend:
- Easier management of addition requests. (No PR conflicts, readme one click away.)
- The community can vote on addition requests.
- Better interface for the user. (The list is sorted by GitHub stars and repository creation date. Readme and last commit date one click away.)

**Comment by aleksandar-todorovic** [comment]
It's been tried multiple times. I think that http://awesomelists.top/ is the most feature complete one out there.

**Comment by brillout** [comment]
@aleksandar-todorovic 

I am aware of it and its corresponding ticket #427.

It is useful but it's not what I wanted. See the 3 bullet points of the OP.

You don't like [devarchy.com/react-components](http://devarchy.com/react-components)? Feel free to be negative. I've put lot's of effort in it and it would be really cool to have some feedback!

> mutliple times

What are the other projects?

**Comment by sindresorhus** [comment]
I personally think Awesome lists should stay on GitHub. The Markdown rendering here is great and it makes it super easy to contribute.
