### ISSUE TITLE
PR for awesome-flow

### ISSUE THREAD

**Issue by amilajack** [sindresorhus/awesome#772]
Would a PR for adding [awesome-flow](https://github.com/dustinspecker/awesome-flow) be welcome?

**Comment by sindresorhus** [comment]
Could use some more content first and should adhere to https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md

// @dustinspecker

**Comment by sindresorhus** [comment]
@thejameskyle might know about some more useful content.

**Comment by thejameskyle** [comment]
Starting on that over here https://github.com/dustinspecker/awesome-flow/pull/2
