### ISSUE TITLE
How to grow Awesome?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome#784]
The Awesome list concept has turned out to be very popular, with a great community ❤️ around it!

**I'm wondering what else we could do with the Awesome brand?** Would there be any interest in an Awesome meetup? Maybe a blog highlighting awesome things? Email newsletter? Twitter account? Would you follow it if so? Printed awesome socks? Because why not.

I'm open for ideas. No idea is too weird or crazy.
## 

Or maybe there's no need to do anything more. That's a valid comment too.

**Comment by Jogai** [comment]
I'm watching some lists just to see what gets submitted. A monthly update with things like added/denied submissions would be of interest to me..

**Comment by dashed** [comment]
> Email newsletter?

A curated newsletter of "This week in awesome.". 👍

**Comment by Sljux** [comment]
Twitter account would also be cool, "Today's most awesome awesome".

**Comment by cmmata** [comment]
A Twitter account / newsletter / blog showing new awesome additions or removals would be great. Right now, the only way is watching repositories and that creates a lot of noise.

Also, an Awesome meetup sounds nice, but where would it be? One or several countries? Maybe an annual event sounds better, with some people talking in awesome conferences.

An Awesome t-shirt would be funny too :)

**Comment by codevinsky** [comment]
Seconding the newsletter idea. 

I would also plaster my laptop with an Awesome sticker

**Comment by sindresorhus** [comment]
> I would also plaster my laptop with an Awesome sticker

https://www.stickermule.com/marketplace/10034-awesome

**Comment by janisozaur** [comment]
I watch this repo to know about new awesome lists, then if I find one interesting, start following it as well. I also subscribe to [GitHub's explore](https://github.com/explore), so I think weekly digest is a nice idea.

Perhaps doing something in likelihood of aforementioned [GitHub's explore](https://github.com/explore) would also be nice idea – think about new subscribers, they will have probably missed out on so much already, but you cannot send out duplicates of lists too often, as long-time subscribers would get annoyed.

The email could have a form of one (or more) highlights (perhaps in coordination with maintainer of list in question) and digest of recently accepted lists.

**Comment by nagygergo** [comment]
Yea, a weekly digest would be really nice.

**Comment by kevingo** [comment]
I love twitter account + weekly idea 👍

**Comment by JesseTG** [comment]
How about branded underwear?  So awesome, you'll shit your pants.

**Comment by guozheng** [comment]
1. when the list grows bigger and bigger, can we have some good ways to support search?

2. the pink glass icon is a bit strange to me, could be just me, looks like a pair of bra. Not saying that bra is not awesome ;P, just a bit strange...

**Comment by sindresorhus** [comment]
> when the list grows bigger and bigger, can we have some good ways to support search?

<kbd>Cmd</kbd> <kbd>f</kbd> is your friend.

> the pink glass icon is a bit strange to me, could be just me, looks like a pair of bra. Not saying that bra is not awesome ;P, just a bit strange...

I intentionally made it bright pink to troll people. :trollface:

**Comment by JesseTG** [comment]
> I intentionally made it bright pink to troll people. :trollface:

How?  I don't get it.  Just looks like a well-designed Hipster-Tech-Thing-201X logo.

**Comment by m1guelpiedrafita** [comment]
+1 for the newsletter

**Comment by kodie** [comment]
I love the logo. Going to buy one to put on my MacBook. I though this was a cool idea: https://github.com/AwesomeCities

**Comment by xin053** [comment]
+1 for  twitter account

**Comment by reclaimer** [comment]
@kodie Not a fan. The list for Berlin isn't bad. But the use case is better served via reviews on third-party services. (And I can't believe I'm suggesting Foursquare over an open-source list?)

**Comment by hungle88** [comment]
Beating Product Hunt? Not crazy enough? No? :)

**Comment by kevingo** [comment]
I also love T-shirt idea.

**Comment by lockys** [comment]
@guozheng,
To your first question, in addition to <kbd>cmd</kbd> + <kbd>f</kbd>, the [AwesomeSearch](https://github.com/lockys/AwesomeSearch) may be helpful for you!

**Comment by gauthamzz** [comment]
Wbt something like an awesome check list 
 Users can select which all categories they like and they will get something like a list randomly generated of their interest. One who reads the most links is the awesomest based on something like credit system or something. If you add more to any list credit increases . just a crazy idea :)

**Comment by tremblerz** [comment]
Let's have an app where people can subscribe and afterwards mention their interests, then automatically email should be sent to them if something "awesome" gets added which matches with their interest.

**Comment by SangramChavan** [comment]
Can include programming contest such as IEEEXtreme  https://github.com/IEEEXtreme
and 
https://github.com/lnishan/awesome-competitive-programming

**Comment by McFrankline** [comment]
Seeing how often items are going to be updated in the list, you might as well start a weekly/monthly newsletter that summarizes stuff. Awesome new additions etc

**Comment by hatzopoulos** [comment]
1) :newspaper_roll: The weekly digest and curated list some people here have described is a great idea.

2) :beer: The meetups idea is a good one too! Like an 'awesome workshop' for a perticular list where people can meet and talk about things related to the list. So for example the awesome-github-cheatsheet meetup at such and such bar or the 'Awesome-Macos' meetup. Or it doesn't have to be about one topic or list. It could be a meetup about a general topic or no topic at all is just as good too. I just think might be more successful if there was a topic or theme. Then perhaps if it kicks off nicely we can have an 'awesome-calendar' of tons of awesome-events on a wide range of topics to choose from (hopefully) all around the world.

3) :mag: That https://github.com/lockys/AwesomeSearch project is cool I just saw that now. How about just expaning that or rebranding it so it's more then just search. Perhaps I'm wrong but it seems to already parse all the lists and has a pretty cool user interface to search. So what if you folks expand the list details.  Add a 'explore feature' perhaps the same sorta way [github's explore](github.com/explore) repos works. Other things it could include is maybe screenshots of the links and some sort of stats. Using the github api you could also pull stats from the repos. Web stats, top charts, trends, etc. 

4) :link: Another idea would be a 404/301 checking bot that reported to the repos when things are broken or moved would be pretty cool.

**Comment by itsjtwright** [comment]
What if there was a website that sent you to a random awesome link, one of the resources, like a learn something random but its learn something awesome. I would use that

**Comment by xingh** [comment]
I think in addition to the Awesome Search  / Ctrl F search, we could index all the sites that the lists are linking to to make a real search. I'm working on this project and will publish the index in the next few weeks.

**Comment by sindresorhus** [comment]
I'm going to start with a weekly newsletter if there's enough interest:
### [Awesome Weekly](http://eepurl.com/cHorer)

*Sign up to show your interest and make it happen!*

**Comment by a7madgamal** [comment]
so many ideas <3
However, I think what we really need is just an awesome official API and the rest will just follow!
If we build and maintained an API to list and keep track of awesomeness we can easily build 100's of awesome products (social integrations, apps, websites.....)

**Comment by kminek** [comment]
Guys, if we would like to take the whole idea further, we should lay some rules how such awesome links documents should be structured. That would allow us write a parser and machine-process the data. This is my rough draft of such standard: 

[Marklink](https://github.com/kminek/marklink)

Suggestions are welcome.

**Comment by legodude17** [comment]
@kminek that sounds really cool.

@sindresorhus how many people have signed up for the newsletter?

**Comment by sindresorhus** [comment]
@legodude17 983! :) Getting close.

**Comment by legodude17** [comment]
@sindresorhus Really hope it gets to 1000. Really ❤️ this idea.

**Comment by kminek** [comment]
hi there,

i finished initial Marklink parser implementation. here is an example how this list is parsed:

[http://awesomelist.kminek.pl/marklink?url=https://raw.githubusercontent.com/kminek/awesome/master/readme.md](http://awesomelist.kminek.pl/marklink?url=https://raw.githubusercontent.com/kminek/awesome/master/readme.md)

:)

**Comment by denispeplin** [comment]
@sindresorhus, I've also tried to parse awesome list and found that deep parsing (even splitting by categories) is hard, because each list formatted differently.
My primary goal is to get start for every Github link, and also to mark outdated github repositories by number of years they outdated.
So I've created a parser that handles only github links, adding stars and marks outdated, and not more.
Result is here: https://awesomerank.github.io/
Stars and years you can found in one of the child lists, for example: https://awesomerank.github.io/lists/h4cc/awesome-elixir.html
I've made builder opensource: https://github.com/awesomerank/rank.
There some ideas in its TODO list inside readme. I'm sure that parsing, even that simple, opens opportunity for some more ideas.
Of course there are bugs, but generally it works.
Feedback is very welcome.

**Comment by mariobro** [comment]
Wait, so did the awesome twitter ever happen? Also how is progress on standardizing the list formats in order to develop the api? If any of those things still need to be done I wouldn't mind taking point on them (albeit with a little help on standardizing data and creating api's).

If awesome meet-ups still haven't taken off I would also be up for trying to organize some of that - one thing that could also be done is virtual meetups where people from different cities could still work together.

On another note, how is the email list doing? How many subscribers is it at now?

**Comment by InAnimaTe** [comment]
I just signed up for the newsletter...we'll see if I get any. Looks like a twitter did happen: https://twitter.com/awesome__re

I also think an API is really a sweet idea. Programmatic access to Awesome would be awesome! Really interested in the future of this in addition to hosting it etc..

**Comment by aschrijver** [comment]
**Idea**: Offer a branded template to expose awesome lists easily as HTML using GH Pages.

This awesome lists would get better exposure to a wider public than is now the case.
Example is React Native: http://www.awesome-react-native.com/

**Comment by sindresorhus** [comment]
@aschrijver I don't really see the point of those websites. The Markdown rendering on GitHub looks great. Much better than most of those websites.

**Comment by aschrijver** [comment]
Maybe, but that was why I was thinking of having a branded template.. an awesome branded template, just like the badge is also branded, and you have strict rules of inclusion for any awesome list to the list-of-lists..

**Comment by maltsev** [comment]
@Jogai, @cmmata, and other folks interested in getting lists updates. I created service [ListList](https://listlist.net) where you can subscribe to [this](https://listlist.net/user/sindresorhus/awesome) and other awesome lists and get new submissions via RSS or email (sent once a week).

**Comment by dexpota** [comment]
Maybe create an organization which collects all of the awesome lists on Github?

**Comment by sindresorhus** [comment]
@dexpota Awesome lists thrive better when the maintainers feel ownership of them. There's no good reason to move them to an org.

**Comment by dexpota** [comment]
I can see the reasoning on maintaining a 'decentralized' organization of the Awesome lists. It is my opinion that a downside of that is that the number of poorly maintained lists or duplicated ones will rise. This was the reasoning behind my proposal, but again I understand that this 'decentralization' is something wanted.

@sindresorhus thank you for the quick feedback.

**Comment by ArtemSer** [comment]
A website maybe? 
Something clean and modern on Github Pages with Jekyll.
If you want a website - just like this comment and I will fork this repo and add a docs folder where the website will be located. To save the original GitHub list.

**Comment by sindresorhus** [comment]
@ArtemSer I don’t really see the need for a website.

**Comment by Jogai** [comment]
@ArtemSer there are several already.

**Comment by busi-reddy-karnati** [comment]
How about sorting the README alphabetically?
I would do that, if you ask me to.
Cheers

**Comment by karx** [comment]
So when is the next (first) AwseomeFest ?
I am in!

We need more awesome in the world, and this delivers.

**Comment by BishikaSinha** [comment]
Make an Instagram, Twitter and Facebook pages for awsome

**Comment by pkgland** [comment]
Not a typical Awesome project per se, but [https://pkg.land](https://pkg.land) (beta, just launched!) is heavily inspired by the core concept of Awesome: "_curated suggestions_", to be exact: pkg.land will curate a list of similar npm packages based on what you search! 

Example: if you search "`moment`", [https://pkg.land/package/moment](https://pkg.land/package/moment) will suggest you "`dayjs`", "`date-fns`" and more...

Still in its early days so any feedbacks are welcome and will help the project grow 🪴

**Comment by Mrscherry** [comment]
SUN DEFI
 Today's top financial traders
 100% foreign capital is a reputable, reliable, high-security place for investors.
 Annual profit up to 1440%
 Profits will be transferred directly to investors' wallets every day.
 Zalo: 0584391289 meet Lily for guidance.
 Click the link for more details:
 https://www.funawealth.com?share_address=0x1813752628964484E01744527388ed5429024926

**Comment by riderx** [comment]
@sindresorhus website can allow you to rank better on SEO than just a GitHub repo, you can have page for all list, it will make the brand stronger

**Comment by Seank30** [comment]
Love Awesome. I have Awesome ICBPINDERSLOSH

**Comment by LimaniBhavik** [comment]
- LinkedIn Developer Community Owner Connect by Specific Topic to share on some period of time to check & add new resources here
- Twitter connect specific Industry owner to check our available resource & Tweet
- Add Discord Server based on Industry

**Comment by riderx** [comment]
- run lint and check on all sub awesome and auto open issue when not respecting rule anymore with a countdown before been removed to main one.
- force awesome list to have a cron check on they link
- find a way to make people rate the link inside a list, if below 4/5 auto remove it.

**Comment by PioneerPII** [comment]
The orders written on to the responsive or reactive presidential documents that excel has down to detailed record them and filed them will be awarded and the order that it spark me to issue upon the hovering government and impose are necessary as right to breath oxygen

**Comment by stark1tty** [comment]
A Mastodon account too with the Twitter account, even if it is just an auto posting from the Twitter please. A lot of us are leaving Twitter for reasons not relevant here.

Looking forward to making an Awesome page for my field when I have time. :) It's on my to do list.

**Comment by ConvincibleViln** [comment]
I want to help GitHub help me and if I knew how I would be doing everything in my power to do so any help is greatly appreciated 
[]()

**Comment by silopolis** [comment]
Further standardization like adopting marklink would certainly be, well, awesome, of course.
Projects like Awesome Tools/Viewer/Rank/Search would surely leverage this.

**Comment by Hawkeye123456** [comment]
Follow and support  me

**Comment by Raulj123** [comment]
Promoting on social media & sharing ideas on there.

**Comment by stark1tty** [comment]
> A Mastodon account too with the Twitter account, even if it is just an auto posting from the Twitter please. A lot of us are leaving Twitter for reasons not relevant here.
> 
> Looking forward to making an Awesome page for my field when I have time. :) It's on my to do list.

@sindresorhus I made one.

https://botsin.space/@awesome__re 

Happy to share the log on with you.

**Comment by EricTra** [comment]
The Awesome list concept has indeed become very popular and has a strong community around it. There are many possibilities for expanding the Awesome brand, and I'm happy to share some ideas with you.

Awesome Meetups: Hosting Awesome meetups could be a great way to bring people together and share knowledge, experiences, and ideas related to the topics covered by Awesome lists. Meetups could be organized around specific themes, such as Awesome Machine Learning or Awesome Web Development.

Awesome Blog: An Awesome blog could highlight various topics covered by Awesome lists, share news and updates related to the topics, and showcase interesting projects or initiatives related to the topics.

Awesome Newsletter: An Awesome newsletter could be a great way to keep people informed about updates to Awesome lists, new additions to the lists, and other relevant news and events related to the topics.

Awesome Twitter Account: An Awesome Twitter account could be used to share updates and news related to the Awesome lists and engage with the community of people interested in the topics.

Awesome Swag: There could be Awesome branded merchandise such as t-shirts, mugs, and yes, even printed socks! This could be a great way to promote the Awesome brand and build a sense of community around it.

Awesome Podcast: A podcast could be a great way to discuss topics covered by Awesome lists, interview experts in the field, and share insights and experiences related to the topics.

Awesome Courses: Creating online courses covering topics covered by Awesome lists could be a great way to provide comprehensive and structured learning experiences to people interested in the topics.

**Comment by sindresorhus** [comment]
@EricTra This is clearly ChatGPT output.

**Comment by NikkiHilton72** [comment]
Maybe we should stragically market awesome and make stickers or tshirts and also include very real awesome people with idea bubbles above their heads that should raise eyebrows or give these "memes" a specific idea or comment we could place these logos or ideas in the pepper or free times and blog about what kind of strategic planning we could barter by asking our grandmothers and all others that we live, sleep and work with and could really get jovial especially around Christmas Valentines and St Patrick's Day and bring in the New Year with Barmusvah's weddings and birthday parties and get someone like a clown to hand out balloons with our logo for a really awesome "awareness" day that we could attend to market our entity as a work place of kindness and forgiveness and we could bring awareness to people that just end up in strange places sometimes so that we as citizens of this very real trusted alien companion much like your featured ghost hassle done mut finding it interesting and willing to work would like to know more but you see I'm a stranger to how to do anything right so I need a class a workshop a good mind and a teacher to ghost me and teach me how to make list and what all of this attends to is a newcomer amongst you that just loves the computer and I got to mention you asked for ideas so I think that Stratocaster planning and maybe magnetic makings or things that advertise your logo or simply brainwashing everyone with implementing droids to share and care would help but if that doesn't work we could simply find people like me who are interested in your idea and want to know more. Sorry about the dribble but coming up with one while it's fresh is always a good idea to get it out while it's roasting instead of losing it and never being able to get back with ya wouldn't be very smart so anyway hope you liked the idea about all things that are the most awesome shared I've ever came scrosd and yes e could prolog the idea and do we grams across the board just in case you would wondering this ape should have a banana in the face. Cuz this shit is insane but I do love it so please give me something to do and please be aware that this is my very first voice but I am speaking and I am proud to be here with you all and I'll be checking by web or seminars often but could someone give me a little guidance here does anyone have the time? I'm not a programmer or an engineer but I love the advice but still searching. Thank you and have a nice night.

**Comment by X19i** [comment]
Social Media is definitely the way to go

**Comment by Athen-Player1** [comment]
rss feed would be cool

**Comment by virtadpt** [comment]
> rss feed would be cool

Here you go: https://github.com/sindresorhus/awesome/commits/main.atom

**Comment by artiomn** [comment]
I think the best idea on how to develop this project now is to remove @sindresorhus  and change the maintainer.
