### ISSUE TITLE
Broken links on http://awesomeawesome.party/

### ISSUE THREAD

**Issue by nighto** [sindresorhus/awesome#850]
http://awesomeawesome.party/awesome.md , for instance, is 404.

**Comment by davisonio** [comment]
As far as I know http://awesomeawesome.party is not affiliated with us. https://awesome.re redirects here though.

**Comment by davisonio** [comment]
Submit the issue on this repo: https://github.com/joehand/awesome-awesome :)

**Comment by nighto** [comment]
Sorry, wasn't aware. Thanks for pointing out.
