### ISSUE TITLE
Media > GIF link broken

### ISSUE THREAD

**Issue by joonaskaskisola** [sindresorhus/awesome#872]

**Comment by davisonio** [comment]
Seems like it was deleted. @ibaaj do you have a recent copy which someone else can put back online?
Would be a shame to loose a great resource.

**Comment by ibaaj** [comment]
@davisonio [yes](https://gist.github.com/ibaaj/95b47b146bf5c70f891ab1fe973330cb)

**Comment by ibaaj** [comment]
@davisonio you can do whatever you want with.

**Comment by davisonio** [comment]
> @davisonio you can do whatever you want with.

Ok, if you wouldn't like to continue the project I've created a replacement repository with the content you provided: https://github.com/davisonio/awesome-gif.

**Comment by ibaaj** [comment]
@davisonio perfect!

**Comment by davisonio** [comment]
Fixed in https://github.com/sindresorhus/awesome/commit/8617b899d8254963cdbe537a6f4c60cb6b7f57de ❤️
