### ISSUE TITLE
Meta list for programming libraries

### ISSUE THREAD

**Issue by brillout** [sindresorhus/awesome#873]
I find awesome lists particularly useful for finding libraries and I don't use the learning material part.

Making a meta list focusing on libraries and containing only awesome lists that curate libraries has following advantages

 - Better overview. ~4 times less lists.
 - Higher quality requirements. Many lists focus is on learning material and neglect the library part. These are not included in the meta list for programming libraries.
 - Improved UI. Since most libraries are hosted on GitHub, a tailored UI can be built, e.g. something like http://devarchy.com/react-components.

The obvious drawback is having two similar meta lists which may lead to confusion.

Beyond that the goal is to increase awareness that awesome lists are a good way to find libraries.
Most programmers I meet don't know about awesome lists so there is likely lot's of potential.

I've started creating such [programming library meta list](https://github.com/brillout/libraries/blob/ef94c565367b43fde69f8c40c9e6c2302fecab3c/README.md).

**Comment by sindresorhus** [comment]
I think great awesome lists have a good balance of libraries vs. learning material. I don't see why you would separate those things. Awesome lists are about quality, not quantity.

> Many lists focus is on learning material and neglect the library part.

Unless they're explicitly about learning, I would say those lists fail. Open an issue with the maintainer if you encounter that.

> Improved UI. Since most libraries are hosted on GitHub, a tailored UI can be built, e.g. something like http://devarchy.com/react-components.

Awesome lists are on GitHub. It would no longer be an Awesome list then.

**Comment by brillout** [comment]
> I don't see why you would separate those things

To focus on the quality. A poor library list without any learning material will not make it to a meta list. But a poor library list with great learning material would and does make it to a meta list.

> Awesome lists are on GitHub. It would no longer be an Awesome list then.

Same view here and devarchy is and will be two-way synced with GitHub.

> Open an issue with the maintainer

Yea and it's precisely what I'm doing with `awesome-vue`.
Sometimes it's not enough though and a fork is required and this is actually happening with `awesome-react`.

<br />

The overall goal is to improve the library curation situation.

Awesome lists have remarkable characteristics.

**Comment by itsjtwright** [comment]
I don't know if I am right, but are you talking about a best of the best list? Like a list that has higher standards then regular awesome lists?

**Comment by nikitavoloboev** [comment]
I have been curating my own version of awesome lists but I unify everything and distribute it as a mind map with an index.

[Take a look at it](https://github.com/nikitavoloboev/knowledge-map). I find there is still issue with discoverability and I feel like mind maps, at least for me, solve the issue of giving contextual knowledge of how each idea/topic relates to another idea/topic.

Each node in the mind map is another mind map and it can go as deep as needed. All in all its a more visual and approachable representation of knowledge, I feel like.

**Comment by brillout** [comment]
@itsjtwright I mean having lists focused on libraries only. E.g. [awesome-react](https://github.com/enaqx/awesome-react) VS [awesome-react-components](https://github.com/brillout/awesome-react-components) or [awesome-angular-components](https://github.com/brillout/awesome-angular-components) VS [awesome-angular](https://github.com/AngularClass/awesome-angular2).

@nikitavoloboev Oh wow nice.
