### ISSUE TITLE
This is awesome

### ISSUE THREAD

**Issue by clthck** [sindresorhus/awesome#891]

**Comment by Jogai** [comment]
Yes it is

**Comment by pokeball99** [comment]
what are you talking about this is the worse repo ever you baka!!!!!

**Comment by clthck** [comment]
@pokeball99 i don't get you. why are you saying this is bad collection?

**Comment by 8-uh** [comment]
![:iiam:](https://foxdeploy.files.wordpress.com/2016/09/iiam.gif?w=636)

**Comment by clthck** [comment]
@8-uh come on.. i am serious. what is going on with this repo?

**Comment by 8-uh** [comment]
I literally have no idea. It seemed to be a silly issue, so I decided to be silly along with it?

**Comment by schas002** [comment]
There's a short url to remember: https://awesome.re/. ;) Comfortably fits in your bookmarks menu, short and easy to remember. **awesome.re - happiness in your awesome**.

**Comment by nikitavoloboev** [comment]
I have been working on a more 'visual' version of this awesome list.

Perhaps you will find it interesting. [Here](https://github.com/nikitavoloboev/knowledge-map) is the link for it. :)

**Comment by clthck** [comment]
@nikitavoloboev https://my.mindnode.com/VfzgzqowJNSpCQYQNzJ4Ag2gm39QWqjXJXyvWq1M - is this ipfs?

**Comment by nikitavoloboev** [comment]
[This](https://my.mindnode.com/qVwyTNceorvb3bx2PdGMxwSgkquY5QgrfiVwS3kW#-192.7,-176.8,2) is IPFS. Where did you find that link?

**Comment by clthck** [comment]
Just that hash reminded me of IPFS. I was playing with it around for a while. But it's not mature yet. I tried to share some files and its loading time was so slow in other machine that is not on the same LAN.
