### ISSUE TITLE
Pi Dashboard

### ISSUE THREAD

**Issue by mikesmth** [sindresorhus/awesome#922]
Hi guys,
My only issue is, my project is not on the list ;-) ... yet.
You might find it interesting enough to list. 
I'm quite content with the result, if I may say so.
Check it [out](https://github.com/mikesmth/pi-dashboard)!

Greetings,

Mike

**Comment by davisonio** [comment]
Hey this is a curated list of awesome _lists_. Maybe this would be better suited for [awesome-python](https://github.com/vinta/awesome-python)?
