### ISSUE TITLE
chinese version?

### ISSUE THREAD

**Issue by deyuhua** [sindresorhus/awesome#929]
Is there chinese version? may i translate this list into chinese?

**Comment by shlomif** [comment]
On Mon, 03 Apr 2017 09:12:28 -0700
华德禹 <notifications@github.com> wrote:

> Is there chinese version? may i translate this list into chinese?
> 

hi!

I don't know if there's already a Chinese version, but the license at
https://github.com/sindresorhus/awesome#license is Public Domain/CC0 allows you
or anyone else to prepare one. If it gets an official endorsement is a
different matter.


-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Aphorisms - http://www.shlomifish.org/humour.html

When Chuck Norris disses your product, it’s not good publicity, even though
you can bet he’ll get the name right.
    — http://www.shlomifish.org/humour/bits/facts/Chuck-Norris/

**Comment by deyuhua** [comment]
@shlomif @sindresorhus  In fact, i want get an official endorsement, in order to introduce this resource to more chinese devloper, and let more people contribute to this list.

**Comment by sindresorhus** [comment]
Sure. Happy to link to it if you do a good job at translating and maintaining.

**Comment by deyuhua** [comment]
@sindresorhus Of course, I will try my best to translate and maintain this useful resource, and send pull request to you when translating is done.

**Comment by Ir1d** [comment]
@deyuhua I don't quite understand. What do you plan to translate?

**Comment by deyuhua** [comment]
@Ir1d 
1. Most of key words is elementary, but Just key words is not enough, i want to add useful comments for unfamiliar resource. At same time, i highly recommend adding english comments too.
2. Maybe i will try to create online chat for active topic.
