### ISSUE TITLE
Forking courtesy call, close after reading.

### ISSUE THREAD

**Issue by WillemMali** [sindresorhus/awesome#958]
Hi, I'm in the process of creating a similar project to yours but I have a few different priorities (creating open, machine-readable data and eventually ascending to P2P heaven). For this reason I'm forking your project and this is my courtesy call.

https://gitlab.com/willemmali/awesome-awesome

I wish you the best of luck with your project. I hope we might be able to consolidate our efforts in the future, or coexist peacefully.

**Comment by sindresorhus** [comment]
Cool. Have fun :) 🦄🌈

**Comment by OvermindDL1** [comment]
It might be nice to make a central data-store with all the data, metadata, and so forth.  Then various things can be generated for human readable for specific purposes or machine readable or so forth.

**Comment by WillemMali** [comment]
I'll be looking at making a decentralized data-store with the data and
metadata, but first I'm doing a conversion from Markdown to YAML.

I could notify you once I've done that?
