### ISSUE TITLE
Question: Descriptions

### ISSUE THREAD

**Issue by legodude17** [sindresorhus/awesome#961]
Should the all the items in places like `Platforms` and `Languages` have descriptions?

**Comment by sindresorhus** [comment]
Yes, ideally, but they should be succinct and good. So it's quite a lot of work.

**Comment by legodude17** [comment]
Ok, good to know

**Comment by sindresorhus** [comment]
Help more welcome though :)

**Comment by legodude17** [comment]
Good idea. :)
