### ISSUE TITLE
Where's Ada?

### ISSUE THREAD

**Issue by Lucretia** [sindresorhus/awesome#977]
Ada 2012 should be in this list. It's awesome! 👍 :)

**Comment by kevva** [comment]
Tell us why :).

**Comment by Lucretia** [comment]
Why? It's not like you have reasons for the other languages! :P

**Comment by 8-uh** [comment]
Uhhh. I'm right here :3    
  
  
  
  
  

  
  
>

**Comment by kevva** [comment]
> Why? It's not like you have reasons for the other languages! :P

Those lists follows the [requirements](https://github.com/sindresorhus/awesome/blob/master/create-list.md).

**Comment by Lucretia** [comment]
I knoew someone did it https://github.com/samuell/awesome-ada

**Comment by legodude17** [comment]
Open a PR then
